proxies:
- name: 2.31|美国2
  type: snell
  server: sha.diao.jimosaofu.xyz
  port: 8443
  psk: WoHaoKuaiLeA
  version: 1
  obfs-opts:
    mode: tls
    host: mirrorn.centos.org
- name: 2.15|美国1
  type: snell
  server: sha.bi.jimosaofu.xyz
  port: 8443
  psk: WoHaoKuaiLeA
  version: 1
  obfs-opts:
    mode: tls
    host: mirrorn.centos.org
