proxies:
- name: 更新地址reurlccW35gV71634
  server: hk2.np.qjnodeip.xyz
  type: vmess
  country: HK
  port: 80
  uuid: c129940e-0768-4e23-ab46-3b60633e4ad2
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /index
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' ITW高雄龍抬頭HiNetVC331321868'
  server: yqy33132.china-cdn-net.com
  port: 33132
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33132.china-cdn-net.com
- name: ' H3xHKHKTBGPVC363331858'
  server: yqy36333.china-cdn-net.com
  port: 36333
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36333.china-cdn-net.com
- name: ' H25xTW台北HiNetVC312321833'
  server: yqy31232.china-cdn-net.com
  port: 31232
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31232.china-cdn-net.com
- name: ' 中国台湾1 124Mbps 618ms 奈飞中国台湾1761'
  server: cu01.onon.cloud
  port: 13341
  type: vmess
  uuid: 9e9eabb7-3759-3627-b8b4-fc38995b0412
  alterId: 1
  cipher: auto
  tls: false
  network: ws
  ws-path: /db
  ws-headers:
    Host: tw.onon.cloud
- name: ' I6xTW台北HiNetVC311371889'
  server: yqy31137.china-cdn-net.com
  port: 31137
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31137.china-cdn-net.com
- name: ' JP50570'
  server: 139.162.123.161
  type: vmess
  country: ' JP'
  port: 65443
  uuid: 42cd918b-36b8-4c00-a58d-0a7fcf0b2df2
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /d39d32d2fd37/
  servername: jp2.piyou.cyou
  ws-headers:
    HOST: jp2.piyou.cyou
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' H3xHKHKTBGPVC362331857'
  server: yqy36233.china-cdn-net.com
  port: 36233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36233.china-cdn-net.com
- name: ' I6xHKHKTBGPVC362341885'
  server: yqy36234.china-cdn-net.com
  port: 36234
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36234.china-cdn-net.com
- name: ' H3xHKHKTBGPVC361331856'
  server: yqy36133.china-cdn-net.com
  port: 36133
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36133.china-cdn-net.com
- name: ' H25xTW台北HiNetVC311321832'
  server: yqy31132.china-cdn-net.com
  port: 31132
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31132.china-cdn-net.com
- name: ' H3xTW台北HiNetVC311351861'
  server: yqy31135.china-cdn-net.com
  port: 31135
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31135.china-cdn-net.com
- name: ' I6xTW台北HiNetVC311381890'
  server: yqy31138.china-cdn-net.com
  port: 31138
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31138.china-cdn-net.com
- name: ' 韩国1 117Mbps 660ms 奈飞自制剧1737'
  server: cn.cm01.onon.cloud
  port: 23351
  type: vmess
  uuid: 9e9eabb7-3759-3627-b8b4-fc38995b0412
  alterId: 1
  cipher: auto
  tls: false
  network: ws
  ws-path: /db
  ws-headers:
    Host: so01.onon.cloud
- name: ' H25xTW彰化HiNetVC322321837'
  server: yqy32232.china-cdn-net.com
  port: 32232
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32232.china-cdn-net.com
- name: ' I5xTW台北HiNetVC311311871'
  server: yqy31131.china-cdn-net.com
  port: 31131
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31131.china-cdn-net.com
- name: ' I5xTW彰化HiNetVC322331876'
  server: yqy32233.china-cdn-net.com
  port: 32233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32233.china-cdn-net.com
- name: ' H3xTW台北HiNetVC311361862'
  server: yqy31136.china-cdn-net.com
  port: 31136
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31136.china-cdn-net.com
- name: ' I5xTW台北HiNetVC312331872'
  server: yqy31233.china-cdn-net.com
  port: 31233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31233.china-cdn-net.com
- name: ' 新加坡小白1369'
  server: cm.syhwdz.top
  port: 40858
  type: vmess
  uuid: 5970926b-4765-3045-ab0f-099206e62032
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /cdnxxy
  ws-headers:
    Host: music.163.com
- name: ' 日本电信混淆1370'
  server: cm.syhwdz.top
  port: 40606
  type: vmess
  uuid: 5970926b-4765-3045-ab0f-099206e62032
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /cdnxy
  ws-headers:
    Host: a.189.cn
- name: US183512457
  server: 23.224.191.13
  type: vmess
  country: US
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.64212792.xyz
  ws-headers:
    HOST: www.64212792.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 35包括V2ray和Trojan1823
  server: yqy2335.china-cdn-net.com
  port: 2335
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2335.china-cdn-net.com
- name: RelayCNUS3067195
  server: 120.232.214.25
  type: vmess
  country: CN
  port: 115
  uuid: 579fb5e3-a2c2-4864-a49b-6f8967ec1f5b
  alterId: 0
  cipher: auto
  ws-path: /
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' HTW高雄龍抬頭HiNetVC331361852'
  server: yqy33136.china-cdn-net.com
  port: 33136
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33136.china-cdn-net.com
- name: 台湾011772
  type: vmess
  server: jike-cccn2.ddns-only.xyz
  port: 39205
  uuid: b8da3f41-58ec-3294-891e-cc27ecb1244a
  alterId: 2
  cipher: auto
  udp: true
  network: ws
  ws-path: /jike1
  ws-headers:
    Host: jike1-hinet03.ddns-only.xyz
- name: RelayUSUS17962 4245Mb718
  server: v2-xgc.cl123.xyz
  type: vmess
  country: US
  port: 80
  uuid: 6d3faf56-93b6-33ca-a57d-673bb6ab696f
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /hls/cctv5phd.m3u8
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 37长期套餐覆盖IPLC专线1825
  server: yqy2337.china-cdn-net.com
  port: 2337
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2337.china-cdn-net.com
- name: RelayKRKR6838231
  server: kr1.xh.qjnodeip.xyz
  type: vmess
  country: KR
  port: 20120
  uuid: 366d7513-7e22-353b-8ac3-412a16eb80a2
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 更新地址reurlccW35gV71679
  server: 158.247.209.122
  type: vmess
  country: US
  port: 443
  uuid: 54d48b3e-89f5-11eb-a57d-560003426bdc
  alterId: 12
  cipher: auto
  network: ws
  ws-path: /wyCnX5Dc/
  servername: bigsur.cf
  ws-headers:
    HOST: bigsur.cf
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' I6xHKHKTBGPVC361341884'
  server: yqy36134.china-cdn-net.com
  port: 36134
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36134.china-cdn-net.com
- name: 34捐赠解锁更多协议线路1822
  server: yqy2334.china-cdn-net.com
  port: 2334
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2334.china-cdn-net.com
- name: RelayCNHK3058186
  server: 120.232.214.25
  type: vmess
  country: CN
  port: 9443
  uuid: bbf7cbb3-0ea2-40b8-b549-c896783d258d
  alterId: 0
  cipher: auto
  ws-path: /
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' Relay日本69081739'
  server: free-jp01.starlink.cyou
  port: 11177
  type: vmess
  uuid: 809f0411-ff85-468a-b3bc-d80d730a9159
  alterId: 1
  cipher: auto
  tls: false
  network: ws
  ws-path: /
  ws-headers:
    Host: free-jp01.starlink.cyou
- name: US183242430
  server: 67.21.72.43
  type: vmess
  country: US
  port: 443
  uuid: 2566d00f-218c-48f7-9a36-13d3d6f1a724
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.17080100.xyz
  ws-headers:
    HOST: www.17080100.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 4326Mb1920
  server: 139.155.22.227
  port: 49110
  type: vmess
  uuid: f7675b7e-59bf-435c-ac03-dc2482f27e5d
  alterId: 64
  cipher: auto
  tls: false
  skip-cert-verify: false
- name: SG4882252
  server: 54.251.199.93
  type: vmess
  country: SG
  port: 443
  uuid: 067d5a53-47df-3faa-8982-8cf680918e68
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /xxx
  servername: sg.ecyjc.com
  ws-headers:
    HOST: sg.ecyjc.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: JP7208  236Mb2356
  server: af01.uwork.mobi
  type: vmess
  country: JP
  port: 80
  uuid: 00000000-0000-0000-0000-000000000001
  alterId: 64
  cipher: auto
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: US183492455
  server: 107.173.157.168
  type: vmess
  country: US
  port: 443
  uuid: 4f6aa0c3-7be1-4eaa-a64c-a23418070422
  alterId: 6
  cipher: auto
  network: ws
  ws-path: /b06fde1/
  servername: www.shunxin.ml
  ws-headers:
    HOST: www.shunxin.ml
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' 中国香港12 86Mbps 553ms 奈飞自制剧1746'
  server: cm01.onon.cloud
  port: 23311
  type: vmess
  uuid: 9e9eabb7-3759-3627-b8b4-fc38995b0412
  alterId: 1
  cipher: auto
  tls: false
  network: ws
  ws-path: /db
  ws-headers:
    Host: hk01.onon.cloud
- name: 更新地址reurlccW35gV71625
  server: 42.157.8.162
  type: vmess
  country: CN
  port: 46006
  uuid: 3959477e-55c4-453f-bc80-3b13e64891ac
  alterId: 64
  cipher: auto
  network: tcp
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' 俄罗斯 11932'
  server: 45.136.245.233
  port: 52306
  type: vmess
  uuid: c1a6d14f-fa43-4bf7-8882-d9eeb423e599
  alterId: 0
  cipher: auto
  tls: false
- name: 36中继中转隧道线路覆盖1824
  server: yqy2336.china-cdn-net.com
  port: 2336
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2336.china-cdn-net.com
- name: RelayUSUS363492581
  server: 23.224.30.36
  type: vmess
  country: US
  port: 443
  uuid: e4494518-74e8-4d6b-942a-6b332cce09ef
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.01902367.xyz
  ws-headers:
    HOST: www.01902367.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 更新地址reurlccW35gV71716
  server: 23.225.153.26
  type: vmess
  country: US
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.91852313.xyz
  ws-headers:
    HOST: www.91852313.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' 新加坡141744'
  server: gzcm.sspro.nl
  port: 10799
  type: vmess
  uuid: fd252902-aac0-36be-8420-a3b23fe803af
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-path: /ssrgr-sg3
  ws-headers:
    Host: none
- name: ' ITW高雄龍抬頭HiNetVC331381880'
  server: yqy33138.china-cdn-net.com
  port: 33138
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33138.china-cdn-net.com
- name: 9  俄罗斯 莫斯科1487
  type: vmess
  server: 45.140.169.224
  port: 52341
  uuid: 3f1079d6-998a-4d1b-98be-a7e9d5f30d07
  alterId: 0
  cipher: auto
  tls: false
- name: PoolUS11492329
  server: 192.74.238.112
  type: vmess
  country: US
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.17379738.xyz
  ws-headers:
    HOST: www.17379738.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: RelayUSUS354402579
  server: www.17080100.xyz
  type: vmess
  country: US
  port: 443
  uuid: 2566d00f-218c-48f7-9a36-13d3d6f1a724
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.17080100.xyz
  ws-headers:
    HOST: www.17080100.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
