proxies:
- name: ' 香港2 华南移动V31531'
  server: rxzgzq.moox.icu
  port: 34007
  type: vmess
  uuid: e94d3ed5-d94c-49ea-9a6c-830b247a1656
  alterId: 1
  cipher: auto
  tls: true
  skip-cert-verify: false
  network: ws
  ws-path: /
  ws-headers:
    Host: hkbgp.xlanfly.xyz
- name: RelayHKHK5757136
  server: hk2.xh.qjnodeip.xyz
  type: vmess
  country: HK
  port: 433
  uuid: 366d7513-7e22-353b-8ac3-412a16eb80a2
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US197372846
  server: 23.224.191.13
  type: vmess
  country: US
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.64212792.xyz
  ws-headers:
    HOST: www.64212792.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: JP80012782
  server: 45.66.134.219
  type: trojan
  country: JP
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  skip-cert-verify: true
  udp: true
- name: RelayJPJP7927852
  server: jp02cf.v2cdn.org
  type: vmess
  country: JP
  port: 443
  uuid: AF48C4B4-4FAD-5F53-0DF4-098B58190767
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ray
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' Game 3 PPhttp1986'
  type: trojan
  server: sg2-trojan.bonds.id
  port: 443
  password: 7d450710-f1ad-11eb-a226-1239d0255272
  udp: true
  sni: pmsc.pubgmobile.com
  alpn:
  - h2c
  - http/1.1
  skip-cert-verify: true
- name: RelayKRKR6932180
  server: kr1.xh.qjnodeip.xyz
  type: vmess
  country: KR
  port: 20120
  uuid: 366d7513-7e22-353b-8ac3-412a16eb80a2
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: SanJose1983
  server: sanjose.cscecsr.tk
  port: 443
  type: trojan
  password: abc123
  sni: sanjose.cscecsr.tk
  skip-cert-verify: true
  udp: true
- name: US197862895
  server: 67.21.72.38
  type: vmess
  country: US
  port: 443
  uuid: 2566d00f-218c-48f7-9a36-13d3d6f1a724
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.17080100.xyz
  ws-headers:
    HOST: www.17080100.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US197792888
  server: 23.224.69.20
  type: vmess
  country: US
  port: 443
  uuid: 946ba5df-5771-4873-a3cb-892378526147
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.76126449.xyz
  ws-headers:
    HOST: www.76126449.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: RO8800211
  server: 62.216.92.180
  type: trojan
  country: RO
  port: 443
  password: a3fa58b581353bb375d2ddad0f327938
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: SG121602828
  server: www.ligonwen.cf
  type: trojan
  country: SG
  port: 443
  password: 7836137d-2db0-4809-9b57-ed14cf2ed4ce
  skip-cert-verify: true
  udp: true
- name: US197292838
  server: 23.224.30.36
  type: vmess
  country: US
  port: 443
  uuid: e4494518-74e8-4d6b-942a-6b332cce09ef
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.01902367.xyz
  ws-headers:
    HOST: www.01902367.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: trojan1310
  type: trojan
  server: 65.49.196.246
  port: 443
  password: 123abc,./
  sni: ztinoz.com
  alpn:
  - h2
  - http/1.1
- name: US197462855
  server: 192.74.238.98
  type: vmess
  country: US
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.17379738.xyz
  ws-headers:
    HOST: www.17379738.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US198422951
  server: 72.167.45.6
  type: trojan
  country: US
  port: 443
  password: a3fa58b581353bb375d2ddad0f327938
  skip-cert-verify: true
  udp: true
- name: SG121552823
  server: sg2.xh.qjnodeip.xyz
  type: vmess
  country: SG
  port: 20102
  uuid: 366d7513-7e22-353b-8ac3-412a16eb80a2
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' 美国 03 Dedipath2297'
  server: 45.80.186.148
  port: 65443
  type: vmess
  uuid: 7043d711-8795-4940-8e54-1c269c2eba19
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /0069/
  ws-headers:
    Host: us1.piyou.cyou
- name: US198312940
  server: 72.167.33.106
  type: trojan
  country: US
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  skip-cert-verify: true
  udp: true
- name: 更新地址reurlccW35gV71820
  server: 192.74.238.112
  type: vmess
  country: US
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.17379738.xyz
  ws-headers:
    HOST: www.17379738.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US197982907
  server: 137.175.57.197
  type: vmess
  country: US
  port: 443
  uuid: 08fc4943-4c7a-4a69-9265-fb961eaea917
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.21377156.xyz
  ws-headers:
    HOST: www.21377156.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: JP80002781
  server: 5.183.177.111
  type: trojan
  country: JP
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  skip-cert-verify: true
  udp: true
- name: RelayUSUS117  943Mb2737
  server: bigsur.cf
  type: vmess
  country: US
  port: 443
  uuid: 54d48b3e-89f5-11eb-a57d-560003426bdc
  alterId: 12
  cipher: auto
  network: ws
  ws-path: /wyCnX5Dc/
  servername: bigsur.cf
  ws-headers:
    HOST: bigsur.cf
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 更新地址reurlccW35gV71854
  server: 192.74.238.111
  type: vmess
  country: US
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: DE3726 1111Mb2759
  server: 194.195.124.174
  type: trojan
  country: DE
  port: 4443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: NL89562817
  server: 89.31.127.151
  type: trojan
  country: NL
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  skip-cert-verify: true
  udp: true
- name: US197892898
  server: 158.247.209.122
  type: vmess
  country: US
  port: 443
  uuid: 54d48b3e-89f5-11eb-a57d-560003426bdc
  alterId: 12
  cipher: auto
  network: ws
  ws-path: /wyCnX5Dc/
  servername: bigsur.cf
  ws-headers:
    HOST: bigsur.cf
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: DE3722 5256Mb2755
  server: 139.59.209.152
  type: trojan
  country: DE
  port: 4443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: NL89602821
  server: 185.171.120.144
  type: trojan
  country: NL
  port: 443
  password: a3fa58b581353bb375d2ddad0f327938
  skip-cert-verify: true
  udp: true
- name: ' SSRSUB香港V12付费推荐suoytssrsub2073'
  server: v5.ssrsub.one
  port: 153
  type: vmess
  uuid: 2a37bd3a-f8c8-45e5-b05c-167f04159396
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /ssrsub
  ws-headers:
    Host: v5.ssrsub.one
- name: RelayCNHK2872117
  server: 120.232.214.25
  type: vmess
  country: CN
  port: 9444
  uuid: 47976098-16bd-4647-8c81-5b0bb812388a
  alterId: 0
  cipher: auto
  ws-path: /
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: RelayJPJP7929854
  server: jp06.v2net.top
  type: vmess
  country: JP
  port: 443
  uuid: C1F54227-5442-A7DD-D8CC-F77BECC09467
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ray
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: DE3721 4081Mb2754
  server: 5.183.179.138
  type: trojan
  country: DE
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  skip-cert-verify: true
  udp: true
- name: NL89322793
  server: 46.182.107.94
  type: vmess
  country: NL
  port: 443
  uuid: 743bdc87-1dea-41bf-aa0b-51dfbbfec8aa
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.54872833.xyz
  ws-headers:
    HOST: www.54872833.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: RO8796207
  server: 185.105.191.92
  type: trojan
  country: RO
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: RO8795206
  server: 185.126.116.235
  type: trojan
  country: RO
  port: 443
  password: a3fa58b581353bb375d2ddad0f327938
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: GB5830 1091Mb2761
  server: 138.68.179.78
  type: trojan
  country: GB
  port: 1443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: ' Russia1982'
  server: russia.cscecsr.tk
  port: 443
  type: trojan
  password: abc123
  sni: russia.cscecsr.tk
  skip-cert-verify: true
  udp: true
- name: NL89252786
  server: 46.182.107.93
  type: vmess
  country: NL
  port: 443
  uuid: 743bdc87-1dea-41bf-aa0b-51dfbbfec8aa
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.54872833.xyz
  ws-headers:
    HOST: www.54872833.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: NL89492810
  server: 178.62.201.120
  type: trojan
  country: NL
  port: 4443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: RelayININ18092418
  server: in1-1.noojat.com
  type: trojan
  country: IN
  port: 1443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: 虎窝vmess节点272270
  server: 172.67.114.2
  port: 443
  type: vmess
  uuid: 3b5e258e-8c5e-45d3-b7d2-02c8f5fc0bb2
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-path: /
  ws-headers:
    Host: cdnde.irteyz.today
- name: US197382847
  server: 198.211.30.163
  type: vmess
  country: US
  port: 443
  uuid: 6aaa2f9f-7c91-4b51-aa77-05a83a5d6a4d
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.93289686.xyz
  ws-headers:
    HOST: www.93289686.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' 美国 06 Cloudflare2301'
  server: uss222.liuwei01.tk
  port: 443
  type: vmess
  uuid: 1b93051f-c9ad-4908-874e-ccb5e8da27ef
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /liuwei
  ws-headers:
    Host: uss222.liuwei01.tk
- name: NL89392800
  server: 46.182.107.108
  type: vmess
  country: NL
  port: 443
  uuid: a6678d34-6aed-44bf-abc0-ad58de119c18
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.31976118.xyz
  ws-headers:
    HOST: www.31976118.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US197402849
  server: 173.82.19.59
  type: vmess
  country: US
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.38705043.xyz
  ws-headers:
    HOST: www.38705043.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 虎窝vmess节点212264
  server: v3.ssrsub.one
  port: 153
  type: vmess
  uuid: a88b0aa2-b6d3-487c-bada-5da80c3b928e
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /ssrsub
  ws-headers:
    Host: v3.ssrsub.one
- name: US197702879
  server: 173.82.46.67
  type: vmess
  country: US
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' 美国 圣路易斯  公益  湘北出口1934'
  server: apn-e.connect-node.xyz
  port: 45301
  type: vmess
  uuid: fb60eebc-9998-3cdf-a81a-a29a0b08d6f5
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /web
  ws-headers:
    Host: usa-12.connect-node.xyz
  udp: true
- name: ' 菲律宾 马尼拉  公益  湘北出口1935'
  server: apn-e.connect-node.xyz
  port: 45303
  type: vmess
  uuid: fb60eebc-9998-3cdf-a81a-a29a0b08d6f5
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /web
  ws-headers:
    Host: phi-20.connect-node.xyz
  udp: true
