proxies:
- name: JP  358Mb2177
  server: 45.66.134.219
  type: trojan
  country: JP
  port: 443
  password: a3fa58b581353bb375d2ddad0f327938
  skip-cert-verify: true
  udp: true
- name: JP74622173
  server: 139.162.123.246
  type: vmess
  country: JP
  port: 65443
  uuid: 9690fd84-9c5c-4cba-8a53-fb30bb8ae5c9
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /2defe1820b908f6/
  servername: jp4.piyou.cyou
  ws-headers:
    HOST: jp4.piyou.cyou
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: SG113282207
  server: 188.166.242.117
  type: trojan
  country: SG
  port: 4443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: ' Game 3 PPhttp1571'
  type: trojan
  server: sg2-trojan.bonds.id
  port: 443
  password: 7d450710-f1ad-11eb-a226-1239d0255272
  udp: true
  sni: pmsc.pubgmobile.com
  alpn:
  - h2c
  - http/1.1
  skip-cert-verify: true
- name: RelayHKUS8465632
  server: aga-sg.ddns.tjiasu.xyz
  type: vmess
  country: HK
  port: 443
  uuid: d3b96bac-b365-48fa-bbac-e23a58801dd2
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /api/rn
  servername: usbv2.ddns.tjiasu.xyz
  ws-headers:
    HOST: usbv2.ddns.tjiasu.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: RelayRURU31651955
  server: t6.ssrsub.com
  type: trojan
  country: RU
  port: 8443
  password: 2faeb94c-1be6-4e31-a30c-c0cbf5f4a1d5
  skip-cert-verify: true
  udp: true
- name: ' Russia1567'
  server: russia.cscecsr.tk
  port: 443
  type: trojan
  password: abc123
  sni: russia.cscecsr.tk
  skip-cert-verify: true
  udp: true
- name: ' mattkaydiarycom美国USUSASanta Clarita25392341'
  server: 173.82.55.94
  port: 443
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-path: /footers
  ws-headers:
    Host: www.01787634.xyz
- name: RelaySGSG12555693
  server: sg.ecyjc.com
  type: vmess
  country: SG
  port: 443
  uuid: 067d5a53-47df-3faa-8982-8cf680918e68
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /xxx
  servername: sg.ecyjc.com
  ws-headers:
    HOST: sg.ecyjc.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US182092319
  server: 72.167.33.106
  type: trojan
  country: US
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  skip-cert-verify: true
  udp: true
- name: 更新地址reurlccW35gV71466
  server: 67.21.72.35
  type: vmess
  country: US
  port: 443
  uuid: 2566d00f-218c-48f7-9a36-13d3d6f1a724
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' mattkaydiarycom美国USUSASanta Clarita23352338'
  server: 173.82.55.93
  port: 443
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-path: /footers
  ws-headers:
    Host: www.01787634.xyz
- name: 更新地址reurlccW35gV71463
  server: 67.21.72.43
  type: vmess
  country: US
  port: 443
  uuid: 2566d00f-218c-48f7-9a36-13d3d6f1a724
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.17080100.xyz
  ws-headers:
    HOST: www.17080100.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: JP10166640
  server: 18.179.20.178
  type: vmess
  country: JP
  port: 443
  uuid: 9e6ceeff-2546-3690-ac00-6fcdf31dec94
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /y284
  servername: cooa.xyz
  ws-headers:
    HOST: cooa.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: IN5990344
  server: 159.89.168.0
  type: trojan
  country: IN
  port: 1443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: RelayUSUS19739753
  server: 198.211.30.165
  type: vmess
  country: US
  port: 443
  uuid: 6aaa2f9f-7c91-4b51-aa77-05a83a5d6a4d
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.93289686.xyz
  ws-headers:
    HOST: www.93289686.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US181012211
  server: 104.251.233.106
  type: vmess
  country: US
  port: 13723
  uuid: a90597c1-bab3-4217-ad6f-0838675c8638
  alterId: 10
  cipher: auto
  network: ws
  ws-path: /ray
  servername: en.tgchannels.org/channel/vpnpool
  ws-headers:
    HOST: en.tgchannels.org/channel/vpnpool
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: DE  247Mb2155
  server: 194.195.124.174
  type: trojan
  country: DE
  port: 4443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: RelayININ21481937
  server: in1-1.noojat.com
  type: trojan
  country: IN
  port: 1443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: RelayRURU31571947
  server: v6.ssrsub.com
  type: vmess
  country: RU
  port: 156
  uuid: 2faeb94c-1be6-4e31-a30c-c0cbf5f4a1d5
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ssrsub
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: RelayUSUS13962130
  server: 173.82.150.26
  type: vmess
  country: US
  port: 443
  uuid: 1a116d02-5fca-47fa-a2a1-6e8d0f2f71cc
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.75287890.xyz
  ws-headers:
    HOST: www.75287890.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US181092219
  server: usa5b-node.3366test.com
  type: vmess
  country: US
  port: 13723
  uuid: a90597c1-bab3-4217-ad6f-0838675c8634
  alterId: 10
  cipher: auto
  network: ws
  ws-path: ray
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: RelayUSUS14002134
  server: 198.211.30.163
  type: vmess
  country: US
  port: 443
  uuid: 6aaa2f9f-7c91-4b51-aa77-05a83a5d6a4d
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.93289686.xyz
  ws-headers:
    HOST: www.93289686.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: NL 1437Mb2188
  server: 89.31.127.151
  type: trojan
  country: NL
  port: 443
  password: 36ebef7d1b1d6205fd0c55f28800e674
  skip-cert-verify: true
  udp: true
- name: ' 日本 东京  公益  湘北出口1508'
  server: apn-e.connect-node.xyz
  port: 45302
  type: vmess
  uuid: fb60eebc-9998-3cdf-a81a-a29a0b08d6f5
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /web
  ws-headers:
    Host: japan-49.connect-node.xyz
  udp: true
- name: RelayAUDE3491862
  server: 1.0.0.0
  type: vmess
  country: AU
  port: 443
  uuid: 3b5e258e-8c5e-45d3-b7d2-02c8f5fc0bb2
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /
  servername: cdnde.irteyz.today
  ws-headers:
    HOST: cdnde.irteyz.today
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' mattkaydiarycom美国USUSASan Jose25182340'
  server: 107.148.198.53
  port: 443
  type: vmess
  uuid: 4c7923df-700f-4bf2-918e-08c6e141037c
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-path: /footers
  ws-headers:
    Host: www.78577665.xyz
- name: RelayCACA5511899
  server: t8.ssrsub.com
  type: trojan
  country: CA
  port: 8443
  password: 40879770-9fd5-461b-928f-7688bfff6e42
  skip-cert-verify: true
  udp: true
- name: RelayCACA5481896
  server: v8.ssrsub.com
  type: vmess
  country: CA
  port: 156
  uuid: 2faeb94c-1be6-4e31-a30c-c0cbf5f4a1d5
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ssrsub
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: GB  651Mb2167
  server: 138.68.179.78
  type: trojan
  country: GB
  port: 1443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: NL 1484Mb2183
  server: 178.62.201.120
  type: trojan
  country: NL
  port: 4443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: RelayRURU12261670
  server: ru01.uuv2.uk
  type: vmess
  country: RU
  port: 2053
  uuid: c29ddcd2-5685-4132-a968-c0ef14b1cc53
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' 美国 圣路易斯  公益  湘北出口1509'
  server: apn-e.connect-node.xyz
  port: 45301
  type: vmess
  uuid: fb60eebc-9998-3cdf-a81a-a29a0b08d6f5
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /web
  ws-headers:
    Host: usa-12.connect-node.xyz
  udp: true
- name: RelayRURU31601950
  server: v3.ssrsub.com
  type: vmess
  country: RU
  port: 153
  uuid: 2faeb94c-1be6-4e31-a30c-c0cbf5f4a1d5
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ssrsub
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 更新地址reurlccW35gV71450
  server: nn-ssr4.feiclouddd.me
  type: vmess
  country: US
  port: 443
  uuid: 79214731-7f0c-4f2d-a894-13b7df293624
  alterId: 60
  cipher: auto
  network: ws
  ws-path: /sadfasdf
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' 菲律宾 马尼拉  公益  湘北出口1510'
  server: apn-e.connect-node.xyz
  port: 45303
  type: vmess
  uuid: fb60eebc-9998-3cdf-a81a-a29a0b08d6f5
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /web
  ws-headers:
    Host: phi-20.connect-node.xyz
  udp: true
- name: RelayRURU31691959
  server: t3.ssrsub.com
  type: trojan
  country: RU
  port: 8443
  password: 2faeb94c-1be6-4e31-a30c-c0cbf5f4a1d5
  skip-cert-verify: true
  udp: true
- name: RelayUSUS19712726
  server: vpnhat.yhdnwm.workers.dev
  type: vmess
  country: US
  port: 443
  uuid: 8f91b6a0-e8ee-11ea-adc1-0242ac120020
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /8f91b6a0-e8ee-11ea-adc1-0242ac120020-vmess
  servername: holy-pond-f89c.yhdnwm.workers.dev
  ws-headers:
    HOST: holy-pond-f89c.yhdnwm.workers.dev
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
