proxies:
- name: RO8911220
  server: 62.216.92.180
  type: trojan
  country: RO
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: RelayRORO8907216
  server: hk-server-01.selfupay.com
  type: trojan
  country: RO
  port: 443
  password: 36ebef7d1b1d6205fd0c55f28800e674
  sni: hk-server-01.selfupay.com
  skip-cert-verify: true
  udp: true
- name: US185962543
  server: 23.224.191.13
  type: vmess
  country: US
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.64212792.xyz
  ws-headers:
    HOST: www.64212792.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: JP7936848
  server: 45.66.134.219
  type: trojan
  country: JP
  port: 443
  password: 36ebef7d1b1d6205fd0c55f28800e674
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: RelayHKHK6177155
  server: hk2.xh.qjnodeip.xyz
  type: vmess
  country: HK
  port: 433
  uuid: 366d7513-7e22-353b-8ac3-412a16eb80a2
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: RelayCNHK3087120
  server: 120.232.214.25
  type: vmess
  country: CN
  port: 121
  uuid: c0f4e01c-540a-4962-9c5c-60d8772f7dcf
  alterId: 0
  cipher: auto
  ws-path: /
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US185942541
  server: 158.247.209.122
  type: vmess
  country: US
  port: 443
  uuid: 54d48b3e-89f5-11eb-a57d-560003426bdc
  alterId: 12
  cipher: auto
  network: ws
  ws-path: /wyCnX5Dc/
  servername: bigsur.cf
  ws-headers:
    HOST: bigsur.cf
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US185542501
  server: bigsur.cf
  type: vmess
  country: US
  port: 443
  uuid: 54d48b3e-89f5-11eb-a57d-560003426bdc
  alterId: 12
  cipher: auto
  network: ws
  ws-path: /wyCnX5Dc/
  servername: bigsur.cf
  ws-headers:
    HOST: bigsur.cf
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US19833989
  server: 184.168.127.50
  type: trojan
  country: US
  port: 443
  password: a3fa58b581353bb375d2ddad0f327938
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: RelayKRKR7120177
  server: kr1.xh.qjnodeip.xyz
  type: vmess
  country: KR
  port: 20120
  uuid: 366d7513-7e22-353b-8ac3-412a16eb80a2
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' Game 3 PPhttp1915'
  type: trojan
  server: sg2-trojan.bonds.id
  port: 443
  password: 7d450710-f1ad-11eb-a226-1239d0255272
  udp: true
  sni: pmsc.pubgmobile.com
  alpn:
  - h2c
  - http/1.1
  skip-cert-verify: true
- name: ' Game 1 PPhttp1913'
  type: trojan
  server: id1-trojan.bonds.id
  port: 443
  password: 9e266b10-f204-11eb-96b8-1239d0255272
  udp: true
  sni: pmsc.pubgmobile.com
  alpn:
  - h2
  - http/1.1
  skip-cert-verify: true
- name: RelaySGSG12183895
  server: sg2.xh.qjnodeip.xyz
  type: vmess
  country: SG
  port: 20102
  uuid: 366d7513-7e22-353b-8ac3-412a16eb80a2
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: SG115162489
  server: 188.166.242.117
  type: trojan
  country: SG
  port: 4443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: SG12186898
  server: 81.90.189.85
  type: trojan
  country: SG
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: SanJose1912
  server: sanjose.cscecsr.tk
  port: 443
  type: trojan
  password: abc123
  sni: sanjose.cscecsr.tk
  skip-cert-verify: true
  udp: true
- name: US186442591
  server: abnode17.makegamegoal.com
  type: trojan
  country: US
  port: 8443
  password: 4f4c470e-22e5-4929-bf87-c431538e8f5b
  skip-cert-verify: true
  udp: true
- name: US19834990
  server: 72.167.33.106
  type: trojan
  country: US
  port: 443
  password: a3fa58b581353bb375d2ddad0f327938
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: JP73592455
  server: au-server-01.f7256f.cn
  type: trojan
  country: JP
  port: 443
  password: a3fa58b581353bb375d2ddad0f327938
  skip-cert-verify: true
  udp: true
- name: ' Relay馃嚫馃嚞SG馃嚫馃嚞SG113551392'
  server: www.ligonwen.cf
  port: 443
  type: trojan
  password: 7836137d-2db0-4809-9b57-ed14cf2ed4ce
  sni: www.ligonwen.cf
- name: httpsgitiov9999 clash ip3 491280
  server: 192.74.238.99
  port: 443
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-path: /path/310910211916
  ws-headers:
    Host: www.17379738.xyz
- name: US186462593
  server: 45.33.28.243
  type: trojan
  country: US
  port: 8080
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: US185512498
  server: www.shunxin.ml
  type: vmess
  country: US
  port: 443
  uuid: 4f6aa0c3-7be1-4eaa-a64c-a23418070422
  alterId: 6
  cipher: auto
  network: ws
  ws-path: /b06fde1/
  servername: www.shunxin.ml
  ws-headers:
    HOST: www.shunxin.ml
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 更新地址reurlccW35gV71688
  server: v6.ssrsub.one
  type: vmess
  port: 156
  udp: true
  uuid: a88b0aa2-b6d3-487c-bada-5da80c3b928e
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ssrsub
  ws-headers:
    Host: v6.ssrsub.one
  http-opts: {}
  h2-opts: {}
  tls: true
- name: JP7934846
  server: 5.183.177.111
  type: trojan
  country: JP
  port: 443
  password: a3fa58b581353bb375d2ddad0f327938
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: 更新地址reurlccW35gV71769
  server: 137.175.57.197
  type: vmess
  country: US
  port: 443
  uuid: 08fc4943-4c7a-4a69-9265-fb961eaea917
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US185752522
  server: 107.173.157.168
  type: vmess
  country: US
  port: 443
  uuid: 4f6aa0c3-7be1-4eaa-a64c-a23418070422
  alterId: 6
  cipher: auto
  network: ws
  ws-path: /b06fde1/
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US186122559
  server: 104.251.233.106
  type: vmess
  country: US
  port: 13723
  uuid: a90597c1-bab3-4217-ad6f-0838675c8638
  alterId: 10
  cipher: auto
  network: ws
  ws-path: /ray
  servername: en.tgchannels.org/channel/vpnpool
  ws-headers:
    HOST: en.tgchannels.org/channel/vpnpool
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: DE32882372
  server: 194.195.124.174
  type: trojan
  country: DE
  port: 4443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: RelayRURU29222098
  server: t6.ssrsub.one
  type: trojan
  country: RU
  port: 8443
  password: a88b0aa2-b6d3-487c-bada-5da80c3b928e
  skip-cert-verify: true
  udp: true
- name: RelayININ18082027
  server: in1-1.noojat.com
  type: trojan
  country: IN
  port: 1443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: httpsgitiov9999 clash ip3 31234
  server: 192.74.238.111
  port: 443
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-path: /path/310910211916
  ws-headers:
    Host: www.17379738.xyz
- name: US185522499
  server: 173.82.150.26
  type: vmess
  country: US
  port: 443
  uuid: 1a116d02-5fca-47fa-a2a1-6e8d0f2f71cc
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.75287890.xyz
  ws-headers:
    HOST: www.75287890.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US185802527
  server: 173.82.19.59
  type: vmess
  country: US
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.38705043.xyz
  ws-headers:
    HOST: www.38705043.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: RO8901210
  server: 185.105.191.92
  type: trojan
  country: RO
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: NL8895878
  server: 185.171.120.144
  type: trojan
  country: NL
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: CA23812371
  server: 138.197.162.114
  type: trojan
  country: CA
  port: 4443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: ' Russia1911'
  server: russia.cscecsr.tk
  port: 443
  type: trojan
  password: abc123
  sni: russia.cscecsr.tk
  skip-cert-verify: true
  udp: true
- name: GB53972383
  server: 138.68.179.78
  type: trojan
  country: GB
  port: 1443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: RelayUSUS43802240
  server: t1.ssrsub.one
  type: trojan
  country: US
  port: 8443
  password: 2a37bd3a-f8c8-45e5-b05c-167f04159396
  skip-cert-verify: true
  udp: true
- name: bngancomUS美国831231414
  server: 172.67.126.56
  port: 443
  type: vmess
  uuid: 3b5e258e-8c5e-45d3-b7d2-02c8f5fc0bb2
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-path: /
  ws-headers:
    Host: cdnde.irteyz.today
- name: 更新地址reurlccW35gV71686
  server: v1.ssrsub.one
  type: vmess
  port: 156
  udp: true
  uuid: 2a37bd3a-f8c8-45e5-b05c-167f04159396
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ssrsub
  ws-headers:
    Host: v1.ssrsub.one
  http-opts: {}
  h2-opts: {}
  tls: true
- name: US185932540
  server: 173.82.46.67
  type: vmess
  country: US
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: DE3615770
  server: 5.183.179.138
  type: trojan
  country: DE
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: RelayRURU29232099
  server: t3.ssrsub.one
  type: trojan
  country: RU
  port: 8443
  password: a88b0aa2-b6d3-487c-bada-5da80c3b928e
  skip-cert-verify: true
  udp: true
- name: RelayRURU11947883
  server: v3.ssrsub.one
  type: vmess
  country: RU
  port: 153
  uuid: 2a37bd3a-f8c8-45e5-b05c-167f04159396
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ssrsub
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: RelayAUDE3441951
  server: 1.0.0.0
  type: vmess
  country: AU
  port: 443
  uuid: 3b5e258e-8c5e-45d3-b7d2-02c8f5fc0bb2
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /
  servername: cdnde.irteyz.today
  ws-headers:
    HOST: cdnde.irteyz.today
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 更新地址reurlccW35gV71692
  server: v4.ssrsub.one
  type: vmess
  port: 153
  udp: true
  uuid: a88b0aa2-b6d3-487c-bada-5da80c3b928e
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ssrsub
  ws-headers:
    Host: v4.ssrsub.one
  http-opts: {}
  h2-opts: {}
  tls: true
- name: RelayRURU11952888
  server: ru01.uuv2.uk
  type: vmess
  country: RU
  port: 2053
  uuid: 1d488ee0-5ce0-4211-9ed1-e0621eae2b63
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' 菲律宾 马尼拉  公益  湘北出口1858'
  server: apn-e.connect-node.xyz
  port: 45303
  type: vmess
  uuid: fb60eebc-9998-3cdf-a81a-a29a0b08d6f5
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /web
  ws-headers:
    Host: phi-20.connect-node.xyz
  udp: true
