proxies:
- name: RelayCNHK3111144
  server: 22872.cn-group-d-inbound-cnshdjsdv.loc.ddns.click
  type: vmess
  country: CN
  port: 8311
  uuid: 5f06ccd9-adff-65bc-0c27-8201aba7ab2b
  alterId: 0
  cipher: auto
  network: tcp
  ws-path: /device-control/stream/
  servername: cdn.remote-control.rscc1272900.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: RelayCNHK3107140
  server: 22872.cn-group-a-inbound-291shaud8n.loc.ddns.click
  type: vmess
  country: CN
  port: 8311
  uuid: 5f06ccd9-adff-65bc-0c27-8201aba7ab2b
  alterId: 0
  cipher: auto
  network: tcp
  ws-path: /device-control/stream/
  servername: cdn.remote-control.rscc1272900.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: RelayCNHK3100133
  server: 22872.cn-group-d-inbound-cnshdjsdv.loc.ddns.click
  type: vmess
  country: CN
  port: 8310
  uuid: 5f06ccd9-adff-65bc-0c27-8201aba7ab2b
  alterId: 0
  cipher: auto
  network: tcp
  ws-path: /device-control/stream/
  servername: cdn.remote-control.rscc1272900.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: RelayCNHK3081114
  server: 22872.cn-group-b-inbound-2bsdhasd.loc.ddns.click
  type: vmess
  country: CN
  port: 8311
  uuid: 5f06ccd9-adff-65bc-0c27-8201aba7ab2b
  alterId: 0
  cipher: auto
  network: tcp
  ws-path: /device-control/stream/
  servername: cdn.remote-control.rscc1272900.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: RelayUSUS19786942
  server: hk1.np.qjnodeip.xyz
  type: vmess
  country: US
  port: 80
  uuid: f0029e06-5afc-4a8b-b2b0-647e0318b0a4
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /index
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: RelayCNHK3108141
  server: 22872.cn-group-b-inbound-2bsdhasd.loc.ddns.click
  type: vmess
  country: CN
  port: 8310
  uuid: 5f06ccd9-adff-65bc-0c27-8201aba7ab2b
  alterId: 0
  cipher: auto
  network: tcp
  ws-path: /device-control/stream/
  servername: cdn.remote-control.rscc1272900.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' I6xTW台北HiNetVC311371891'
  server: yqy31137.china-cdn-net.com
  port: 31137
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31137.china-cdn-net.com
- name: RelayUSUS19746902
  server: hk1.xh.qjnodeip.xyz
  type: vmess
  country: US
  port: 20120
  uuid: 366d7513-7e22-353b-8ac3-412a16eb80a2
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /index
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 台湾011844
  type: vmess
  server: jike-cccn2.ddns-only.xyz
  port: 39205
  uuid: b8da3f41-58ec-3294-891e-cc27ecb1244a
  alterId: 2
  cipher: auto
  udp: true
  network: ws
  ws-path: /jike1
  ws-headers:
    Host: jike1-hinet03.ddns-only.xyz
- name: ' H25xTW台北HiNetVC312321868'
  server: yqy31232.china-cdn-net.com
  port: 31232
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31232.china-cdn-net.com
- name: ' I5xTW台北HiNetVC312331883'
  server: yqy31233.china-cdn-net.com
  port: 31233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31233.china-cdn-net.com
- name: ' I6xTW台北HiNetVC311381892'
  server: yqy31138.china-cdn-net.com
  port: 31138
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31138.china-cdn-net.com
- name: ' I6xHKHKTBGPVC362341889'
  server: yqy36234.china-cdn-net.com
  port: 36234
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36234.china-cdn-net.com
- name: ' HTW高雄龍抬頭HiNetVC332371866'
  server: yqy33237.china-cdn-net.com
  port: 33237
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33237.china-cdn-net.com
- name: ' H3xHKHKTBGPVC363331876'
  server: yqy36333.china-cdn-net.com
  port: 36333
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36333.china-cdn-net.com
- name: ' H3xHKHKTBGPVC361331874'
  server: yqy36133.china-cdn-net.com
  port: 36133
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36133.china-cdn-net.com
- name: ' H25xTW台北HiNetVC311321867'
  server: yqy31132.china-cdn-net.com
  port: 31132
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31132.china-cdn-net.com
- name: ' H3xTW台北HiNetVC311361878'
  server: yqy31136.china-cdn-net.com
  port: 31136
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31136.china-cdn-net.com
- name: 更新地址reurlccW35gV71707
  server: hk2.np.qjnodeip.xyz
  type: vmess
  country: HK
  port: 80
  uuid: c129940e-0768-4e23-ab46-3b60633e4ad2
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /index
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' I5xTW台北HiNetVC311311882'
  server: yqy31131.china-cdn-net.com
  port: 31131
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31131.china-cdn-net.com
- name: ' 新加坡小白1513'
  server: cm.syhwdz.top
  port: 40858
  type: vmess
  uuid: 5970926b-4765-3045-ab0f-099206e62032
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /cdnxxy
  ws-headers:
    Host: music.163.com
- name: ' 日本电信混淆1514'
  server: cm.syhwdz.top
  port: 40606
  type: vmess
  uuid: 5970926b-4765-3045-ab0f-099206e62032
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /cdnxy
  ws-headers:
    Host: a.189.cn
- name: ' H25xTW彰化HiNetVC322321870'
  server: yqy32232.china-cdn-net.com
  port: 32232
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32232.china-cdn-net.com
- name: 35包括V2ray和Trojan1862
  server: yqy2335.china-cdn-net.com
  port: 2335
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2335.china-cdn-net.com
- name: ' 韩国1 117Mbps 660ms 奈飞自制剧1810'
  server: cn.cm01.onon.cloud
  port: 23351
  type: vmess
  uuid: 9e9eabb7-3759-3627-b8b4-fc38995b0412
  alterId: 1
  cipher: auto
  tls: false
  network: ws
  ws-path: /db
  ws-headers:
    Host: so01.onon.cloud
- name: ' H3xTW台北HiNetVC311351877'
  server: yqy31135.china-cdn-net.com
  port: 31135
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31135.china-cdn-net.com
- name: ' I6xHKHKTBGPVC361341888'
  server: yqy36134.china-cdn-net.com
  port: 36134
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36134.china-cdn-net.com
- name: 跨越长城提供 直连 韩国13
  type: vmess
  server: 13.124.14.99
  port: 8888
  uuid: 6ae2e994-2018-4f9f-a5bb-4639c14ba05f
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  ws-headers:
    Host: 13.124.14.99
- name: 4326Mb1899
  server: 139.155.22.227
  port: 49110
  type: vmess
  uuid: f7675b7e-59bf-435c-ac03-dc2482f27e5d
  alterId: 64
  cipher: auto
  tls: false
  skip-cert-verify: false
- name: httpsgitiov9999 clash ip3 581289
  server: 66.ssrj.xyz
  port: 65166
  type: vmess
  uuid: 24ea3f63-d495-3a0a-a7de-f92a4e6fb9ae
  alterId: 2
  cipher: auto
  tls: false
- name: RelayCNDE2642763
  server: 22872.cn-group-a-inbound-291shaud8n.loc.ddns.click
  type: vmess
  country: CN
  port: 8301
  uuid: 5f06ccd9-adff-65bc-0c27-8201aba7ab2b
  alterId: 0
  cipher: auto
  network: tcp
  ws-path: /device-control/stream/
  servername: cdn.remote-control.rscc1272900.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 36中继中转隧道线路覆盖1863
  server: yqy2336.china-cdn-net.com
  port: 2336
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2336.china-cdn-net.com
- name: RelayCNDE2627755
  server: 22872.cn-group-d-inbound-cnshdjsdv.loc.ddns.click
  type: vmess
  country: CN
  port: 8301
  uuid: 5f06ccd9-adff-65bc-0c27-8201aba7ab2b
  alterId: 0
  cipher: auto
  network: tcp
  ws-path: /device-control/stream/
  servername: cdn.remote-control.rscc1272900.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' I5xTW彰化HiNetVC322331885'
  server: yqy32233.china-cdn-net.com
  port: 32233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32233.china-cdn-net.com
- name: ' ITW高雄龍抬頭HiNetVC331381887'
  server: yqy33138.china-cdn-net.com
  port: 33138
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33138.china-cdn-net.com
- name: RelayCNAU2626754
  server: 22872.cn-group-a-inbound-291shaud8n.loc.ddns.click
  type: vmess
  country: CN
  port: 8304
  uuid: 5f06ccd9-adff-65bc-0c27-8201aba7ab2b
  alterId: 0
  cipher: auto
  network: tcp
  ws-path: /device-control/stream/
  servername: cdn.remote-control.rscc1272900.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: RelayCNDE2624752
  server: 22872.cn-group-b-inbound-2bsdhasd.loc.ddns.click
  type: vmess
  country: CN
  port: 8301
  uuid: 5f06ccd9-adff-65bc-0c27-8201aba7ab2b
  alterId: 0
  cipher: auto
  network: tcp
  ws-path: /device-control/stream/
  servername: cdn.remote-control.rscc1272900.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 33公益等级線路嚴格限速1860
  server: yqy2333.china-cdn-net.com
  port: 2333
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /
  ws-headers:
    Host: yqy2333.china-cdn-net.com
- name: 跨越长城提供 直连 新加坡15
  type: vmess
  server: 165.22.61.210
  port: 21888
  uuid: 6ae2e994-2018-4f9f-a5bb-4639c14ba05f
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  ws-headers:
    Host: 165.22.61.210
- name: ' 中国台湾1 124Mbps 618ms 奈飞中国台湾1834'
  server: cu01.onon.cloud
  port: 13341
  type: vmess
  uuid: 9e9eabb7-3759-3627-b8b4-fc38995b0412
  alterId: 1
  cipher: auto
  tls: false
  network: ws
  ws-path: /db
  ws-headers:
    Host: tw.onon.cloud
- name: ' H3xHKHKTBGPVC362331875'
  server: yqy36233.china-cdn-net.com
  port: 36233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36233.china-cdn-net.com
- name: ' 新加坡141817'
  server: gzcm.sspro.nl
  port: 10799
  type: vmess
  uuid: fd252902-aac0-36be-8420-a3b23fe803af
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-path: /ssrgr-sg3
  ws-headers:
    Host: none
- name: 更新地址reurlccW35gV71698
  server: 42.157.8.162
  type: vmess
  country: CN
  port: 46006
  uuid: 3959477e-55c4-453f-bc80-3b13e64891ac
  alterId: 64
  cipher: auto
  network: tcp
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' 中国香港12 86Mbps 553ms 奈飞自制剧1819'
  server: cm01.onon.cloud
  port: 23311
  type: vmess
  uuid: 9e9eabb7-3759-3627-b8b4-fc38995b0412
  alterId: 1
  cipher: auto
  tls: false
  network: ws
  ws-path: /db
  ws-headers:
    Host: hk01.onon.cloud
- name: ' ITW高雄龍抬頭HiNetVC331371886'
  server: yqy33137.china-cdn-net.com
  port: 33137
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33137.china-cdn-net.com
- name: 34捐赠解锁更多协议线路1861
  server: yqy2334.china-cdn-net.com
  port: 2334
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2334.china-cdn-net.com
- name: ' 俄罗斯 11910'
  server: 45.136.245.233
  port: 52306
  type: vmess
  uuid: c1a6d14f-fa43-4bf7-8882-d9eeb423e599
  alterId: 0
  cipher: auto
  tls: false
- name: ' HTW高雄龍抬頭HiNetVC331311865'
  server: yqy33131.china-cdn-net.com
  port: 33131
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33131.china-cdn-net.com
- name: ' httpsgitiov9999 圣何塞1305'
  server: 198.200.51.28
  port: 21045
  type: vmess
  uuid: 1d219570-0d1b-11ec-a57e-00163ca76936
  alterId: 0
  cipher: auto
  tls: false
- name: RelayUSRU123 3527Mb2354
  server: 172.67.150.130
  type: vmess
  country: US
  port: 80
  uuid: 3d31728e-064d-42b8-b945-f79c008f73fc
  alterId: 233
  cipher: auto
  network: ws
  ws-path: /
  servername: free-russian01-cdn.xiaohouzi.club
  ws-headers:
    HOST: free-russian01-cdn.xiaohouzi.club
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
