proxies:
- name: ' githubcomfreefq  俄罗斯  2610'
  server: t6.ssrsub.one
  port: 8443
  type: trojan
  password: a88b0aa2-b6d3-487c-bada-5da80c3b928e
  sni: t6.ssrsub.one
- name: ' githubcomfreefq  美国加利福尼亚州洛杉矶MULTACOM数据中心 133'
  server: 173.82.150.26
  port: 443
  type: vmess
  uuid: 1a116d02-5fca-47fa-a2a1-6e8d0f2f71cc
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-path: /path/310910211916
  ws-headers:
    Host: www.75287890.xyz
- name: ' githubcomfreefq  俄罗斯新西伯利亚JustHost 249'
  server: t3.ssrsub.one
  port: 8443
  type: trojan
  password: a88b0aa2-b6d3-487c-bada-5da80c3b928e
  sni: t3.ssrsub.one
