proxies:
- name: ' SG1123322002033'
  server: hkml.jjyun.ren
  type: vmess
  country: ' SG'
  port: 88
  uuid: 46261109-aa54-47e7-8ad1-8e170af43af1
  alterId: 10
  cipher: auto
  network: ws
  ws-path: /jjyun
  servername: hkml.jjyun.ren
  ws-headers:
    HOST: hkml.jjyun.ren
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' 日本J03iepl11791968'
  server: front.sh.9929.nkeo.top
  port: 45178
  type: vmess
  uuid: 205c9676-57ec-31dd-b28b-21784535e18c
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /jp03
  ws-headers:
    Host: jp03.mypeter.icu
- name: ' H3xHKHKTBGPVC3633315281995'
  server: yqy36333.china-cdn-net.com
  port: 36333
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36333.china-cdn-net.com
- name: ' H25xTW彰化HiNetVC3223215221991'
  server: yqy32232.china-cdn-net.com
  port: 32232
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32232.china-cdn-net.com
- name: ' H3xTW彰化HiNetVC321351158'
  server: yqy32135.china-cdn-net.com
  port: 32135
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32135.china-cdn-net.com
- name: ' I5xTW台北HiNetVC3123315352000'
  server: yqy31233.china-cdn-net.com
  port: 31233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31233.china-cdn-net.com
- name: ' H25xTW台北HiNetVC3123215201989'
  server: yqy31232.china-cdn-net.com
  port: 31232
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31232.china-cdn-net.com
- name: ' ITW高雄龍抬頭HiNetVC3313215331999'
  server: yqy33132.china-cdn-net.com
  port: 33132
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33132.china-cdn-net.com
- name: ' HTW高雄龍抬頭HiNetVC3323715181987'
  server: yqy33237.china-cdn-net.com
  port: 33237
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33237.china-cdn-net.com
- name: ' H25xTW台北HiNetVC3113215191988'
  server: yqy31132.china-cdn-net.com
  port: 31132
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31132.china-cdn-net.com
- name: ' I5xTW彰化HiNetVC3223315372002'
  server: yqy32233.china-cdn-net.com
  port: 32233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32233.china-cdn-net.com
- name: ' H3xTW彰化HiNetVC3213615321998'
  server: yqy32136.china-cdn-net.com
  port: 32136
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32136.china-cdn-net.com
- name: ' Lv210x 韩国03IP均衡优化混合负载12221970'
  server: lv2bsdwasdwsa.v22222.xyz
  port: 11111
  type: vmess
  uuid: 7ca31999-3b03-3bc3-9e9e-c83865b4a96c
  alterId: 1
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /tnt-kr3
  ws-headers:
    Host: baidu.com
- name: ' 香港 04  Magic  VIP1  原生IP  1x12141969'
  server: magic.seeu.dasaric.pw
  port: 17014
  type: vmess
  uuid: 7e67383a-2c95-321c-ad43-f47d0dbf97ba
  alterId: 1
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /hls/ccav5phd.m3u8
  ws-headers:
    Host: magic.seeu.dasaric.pw
- name: ' H3xTW台北HiNetVC3113615301997'
  server: yqy31136.china-cdn-net.com
  port: 31136
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31136.china-cdn-net.com
- name: ' H25xTW彰化HiNetVC3213215211990'
  server: yqy32132.china-cdn-net.com
  port: 32132
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32132.china-cdn-net.com
- name: ' H3xHKHKTBGPVC3623315271994'
  server: yqy36233.china-cdn-net.com
  port: 36233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36233.china-cdn-net.com
- name: US182531810
  server: 3.36.48.102
  type: vmess
  country: US
  port: 8080
  uuid: 52ac1672-ca47-48e4-df3e-513bd1f301b1
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /白嫖节点分享Q群262349039
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' I5xTW彰化HiNetVC3213115362001'
  server: yqy32131.china-cdn-net.com
  port: 32131
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32131.china-cdn-net.com
- name: ' I6xTW台北HiNetVC3113815442008'
  server: yqy31138.china-cdn-net.com
  port: 31138
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31138.china-cdn-net.com
- name: ' I5xTW台北HiNetVC311311161'
  server: yqy31131.china-cdn-net.com
  port: 31131
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31131.china-cdn-net.com
- name: ' H3xTW台北HiNetVC3113515291996'
  server: yqy31135.china-cdn-net.com
  port: 31135
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31135.china-cdn-net.com
- name: ' I6xHKHKTBGPVC3613415402005'
  server: yqy36134.china-cdn-net.com
  port: 36134
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36134.china-cdn-net.com
- name: ' I6xHKHKTBGPVC3623415412006'
  server: yqy36234.china-cdn-net.com
  port: 36234
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36234.china-cdn-net.com
- name: ' 馃嚚馃嚦CN211418592012'
  server: 139.155.22.227
  port: 49110
  type: vmess
  uuid: f7675b7e-59bf-435c-ac03-dc2482f27e5d
  alterId: 64
  cipher: auto
  tls: false
- name: RelayCNUS4191251
  server: us1.np.qjnodeip.xyz
  type: vmess
  country: CN
  port: 10018
  uuid: f4517393-ad28-487b-9635-7734ec5b3561
  alterId: 1
  cipher: auto
  network: tcp
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: CN85719012016
  server: 42.157.8.162
  type: vmess
  country: CN
  port: 46006
  uuid: 3959477e-55c4-453f-bc80-3b13e64891ac
  alterId: 64
  cipher: auto
  network: tcp
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 36中继中转隧道线路覆盖1142
  server: yqy2336.china-cdn-net.com
  port: 2336
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2336.china-cdn-net.com
- name: ' H3xHKHKTBGPVC3613315261993'
  server: yqy36133.china-cdn-net.com
  port: 36133
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36133.china-cdn-net.com
- name: 33公益等级線路嚴格限速15121982
  server: yqy2333.china-cdn-net.com
  port: 2333
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /
  ws-headers:
    Host: yqy2333.china-cdn-net.com
- name: AU16681747
  server: 149.28.186.71
  type: vmess
  country: AU
  port: 80
  uuid: 772f88ea-f5a4-4b8d-b111-9de26f9ed024
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /sshstores
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: RelayGBGB8127260
  server: ukml.52jjyun.top
  type: vmess
  country: GB
  port: 88
  uuid: 3cfd53ab-ac20-4799-9024-0c2f3e217e3b
  alterId: 10
  cipher: auto
  network: ws
  ws-path: /jjyun
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' HTW高雄龍抬頭HiNetVC3313115171986'
  server: yqy33131.china-cdn-net.com
  port: 33131
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33131.china-cdn-net.com
- name: RelayGBGB8128261
  server: ukdll.52jjyun.top
  type: vmess
  country: GB
  port: 80
  uuid: 031d7c73-b2fe-4695-9e8a-3702bba3ea47
  alterId: 10
  cipher: auto
  network: ws
  ws-path: /jjyun
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: FR51401759
  server: 164.132.56.90
  type: vmess
  country: FR
  port: 80
  uuid: bd157194-66cb-4a17-9909-0acdecb469c5
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /sshstores
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: NL84651781
  server: 51.15.96.243
  type: vmess
  country: NL
  port: 80
  uuid: eecfcedc-ef58-4eae-95fd-bf1b256bc2b7
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /sshstores
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: US182541811
  server: 20.68.125.113
  type: vmess
  country: US
  port: 80
  uuid: 84c005e5-0cbb-4c60-9838-6af7256cc4af
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /sshstores
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: DE36721752
  server: 51.116.183.141
  type: vmess
  country: DE
  port: 80
  uuid: da7e32ba-5c26-4452-b13a-473bd2054f6c
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /sshstores
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' httpsgitiov9999 ip1莫斯科581'
  server: 176.32.35.228
  port: 28769
  type: vmess
  uuid: d7c2a604-0e55-11ec-a43a-7aec04f65127
  alterId: 0
  cipher: auto
  tls: false
- name: 34捐赠解锁更多协议线路15131983
  server: yqy2334.china-cdn-net.com
  port: 2334
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2334.china-cdn-net.com
