proxies:
- name: Ket YT877
  type: trojan
  server: sg6-trojan.bonds.id
  port: 443
  password: 7a80c340-f911-11eb-a7cb-1239d0255272
  udp: true
  sni: m.youtube.com
  alpn:
  - h2
  - http/1.1
  skip-cert-verify: true
- name: ' Game 3 PPhttp891'
  type: trojan
  server: sg2-trojan.bonds.id
  port: 443
  password: 7d450710-f1ad-11eb-a226-1239d0255272
  udp: true
  sni: pmsc.pubgmobile.com
  alpn:
  - h2c
  - http/1.1
  skip-cert-verify: true
- name: SanJose888
  server: sanjose.cscecsr.tk
  port: 443
  type: trojan
  password: abc123
  sni: sanjose.cscecsr.tk
  skip-cert-verify: true
  udp: true
- name: ' Game 1 PPhttp889'
  type: trojan
  server: id1-trojan.bonds.id
  port: 443
  password: 9e266b10-f204-11eb-96b8-1239d0255272
  udp: true
  sni: pmsc.pubgmobile.com
  alpn:
  - h2
  - http/1.1
  skip-cert-verify: true
- name: ' Russia887'
  server: russia.cscecsr.tk
  port: 443
  type: trojan
  password: abc123
  sni: russia.cscecsr.tk
  skip-cert-verify: true
  udp: true
- name: ' 美国 02 Multacom1341'
  server: 173.82.55.94
  port: 443
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-path: /footers
  ws-headers:
    Host: www.01787634.xyz
- alterId: 64
  cipher: auto
  name: 0928oslook美国USUSASanta Clarita28590
  network: ws
  port: 443
  server: 173.82.55.93
  tls: true
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  ws-headers:
    Host: www.01787634.xyz
  ws-path: /footers
- name: 虎窝vmess节点081397
  server: 96.43.91.59
  port: 443
  type: vmess
  uuid: 3bfb43e2-7dfe-4757-86ee-1ce9fb9fd13a
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-path: /path/310910211916
  ws-headers:
    Host: www.45218443.xyz
- name: 虎窝vmess节点071396
  server: 107.148.198.53
  port: 443
  type: vmess
  uuid: 4c7923df-700f-4bf2-918e-08c6e141037c
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-path: /footers
  ws-headers:
    Host: www.78577665.xyz
- name: SSRSUBV37付费推荐suoytssrsub981
  server: nn-ssr24.feiclouddd.me
  port: 443
  type: vmess
  uuid: 94d3ddba-3c75-4ddd-84c5-b859a30b1fb9
  alterId: 60
  cipher: auto
  tls: true
  network: ws
  ws-path: /dsafasdf
  ws-headers:
    Host: nn-ssr24.feiclouddd.me
- name: ' 日本 东京  公益  湘北出口836'
  server: apn-e.connect-node.xyz
  port: 45302
  type: vmess
  uuid: fb60eebc-9998-3cdf-a81a-a29a0b08d6f5
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /web
  ws-headers:
    Host: japan-49.connect-node.xyz
  udp: true
- name: SSRSUBV14付费推荐suoytssrsub958
  server: 45.80.186.148
  port: 65443
  type: vmess
  uuid: 7043d711-8795-4940-8e54-1c269c2eba19
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /0069/
  ws-headers:
    Host: us1.piyou.cyou
- name: NodeTest 89  18551 KB717
  server: us01.tencentlink.icu
  port: 10000
  type: trojan
  password: 42c2d9d7-d55c-4d6c-ba0a-47bf312b4ab6
  skip-cert-verify: false
  udp: true
  speedtest: 189959
- name: ' 美国 圣路易斯  公益  湘北出口837'
  server: apn-e.connect-node.xyz
  port: 45301
  type: vmess
  uuid: fb60eebc-9998-3cdf-a81a-a29a0b08d6f5
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /web
  ws-headers:
    Host: usa-12.connect-node.xyz
  udp: true
- name: ' 美国 03 Multacom1342'
  server: 173.82.150.26
  port: 443
  type: vmess
  uuid: 1a116d02-5fca-47fa-a2a1-6e8d0f2f71cc
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-path: /path/310910211916
  ws-headers:
    Host: www.75287890.xyz
- name: SSRSUBV17付费推荐suoytssrsub961
  server: azure-f4s-hk.transfer-xray.tk
  port: 53420
  type: vmess
  uuid: 1b93051f-c9ad-4908-874e-ccb5e8da27ef
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /liuwei
  ws-headers:
    Host: usss222.liuwei01.tk
- name: ' 菲律宾 马尼拉  公益  湘北出口838'
  server: apn-e.connect-node.xyz
  port: 45303
  type: vmess
  uuid: fb60eebc-9998-3cdf-a81a-a29a0b08d6f5
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /web
  ws-headers:
    Host: phi-20.connect-node.xyz
  udp: true
