proxies:
- name: ' HK52962127'
  server: 18.167.94.242
  port: 80
  type: vmess
  uuid: cec85927-8a7a-4866-df8c-27ed589de0ce
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-path: /TS/recharge/tzUrl.html
  ws-headers:
    Host: pull.free.video.10010.com
- name: ' 香港HK 01 Azure Game 3x1529'
  server: global-transit-01-hk.pucdn.me
  port: 16001
  type: vmess
  uuid: 782e9cbb-07f7-3c3f-a89d-d3047081578d
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /vvv
  ws-headers:
    Host: l2-azure-hk-01.pucdn.me
- name: ' I6xHKHKTBGPVC362341966'
  server: yqy36234.china-cdn-net.com
  port: 36234
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36234.china-cdn-net.com
- name: ' H25xTW台北HiNetVC311321944'
  server: yqy31132.china-cdn-net.com
  port: 31132
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31132.china-cdn-net.com
- name: ' ITW高雄龍抬頭HiNetVC331381964'
  server: yqy33138.china-cdn-net.com
  port: 33138
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33138.china-cdn-net.com
- name: ' H3xHKHKTBGPVC363331953'
  server: yqy36333.china-cdn-net.com
  port: 36333
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36333.china-cdn-net.com
- name: ' I5xTW彰化HiNetVC322331962'
  server: yqy32233.china-cdn-net.com
  port: 32233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32233.china-cdn-net.com
- name: ' I6xHKHKTBGPVC361341965'
  server: yqy36134.china-cdn-net.com
  port: 36134
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36134.china-cdn-net.com
- name: ' H25xTW台北HiNetVC312321945'
  server: yqy31232.china-cdn-net.com
  port: 31232
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31232.china-cdn-net.com
- name: ' ITW高雄龍抬頭HiNetVC331321958'
  server: yqy33132.china-cdn-net.com
  port: 33132
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33132.china-cdn-net.com
- name: ' I5xTW台北HiNetVC312331960'
  server: yqy31233.china-cdn-net.com
  port: 31233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31233.china-cdn-net.com
- name: ' H3xHKHKTBGPVC362331952'
  server: yqy36233.china-cdn-net.com
  port: 36233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36233.china-cdn-net.com
- name: ' I6xTW台北HiNetVC311381969'
  server: yqy31138.china-cdn-net.com
  port: 31138
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31138.china-cdn-net.com
- name: RelaySGSG12218928
  server: free-sg01.starlink.cyou
  type: vmess
  country: SG
  port: 15077
  uuid: ce7f2f61-2b39-434c-af10-3dbe3c0b6a6c
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' H25xTW彰化HiNetVC322321947'
  server: yqy32232.china-cdn-net.com
  port: 32232
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32232.china-cdn-net.com
- name: ' HTW高雄龍抬頭HiNetVC331311942'
  server: yqy33131.china-cdn-net.com
  port: 33131
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33131.china-cdn-net.com
- name: ' 韩国1 117Mbps 660ms 奈飞自制剧1868'
  server: cn.cm01.onon.cloud
  port: 23351
  type: vmess
  uuid: 9e9eabb7-3759-3627-b8b4-fc38995b0412
  alterId: 1
  cipher: auto
  tls: false
  network: ws
  ws-path: /db
  ws-headers:
    Host: so01.onon.cloud
- name: ' H3xTW台北HiNetVC311351954'
  server: yqy31135.china-cdn-net.com
  port: 31135
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31135.china-cdn-net.com
- name: RelayCNDE2688767
  server: 42.81.8.1
  type: vmess
  country: CN
  port: 80
  uuid: 8805adee-8efb-441a-bbbb-feb604fb7ba2
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  servername: 003.cdn.8x.cx.hit.edu.cn
  ws-headers:
    HOST: 003.cdn.8x.cx.hit.edu.cn
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 跨越长城提供 直连 新加坡15
  type: vmess
  server: 165.22.61.210
  port: 21888
  uuid: 6ae2e994-2018-4f9f-a5bb-4639c14ba05f
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  ws-headers:
    Host: 165.22.61.210
- name: ' H3xTW台北HiNetVC311361955'
  server: yqy31136.china-cdn-net.com
  port: 31136
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31136.china-cdn-net.com
- name: ' 香港AWS 10 Netflix 1x1527'
  server: global-transit-02-hk.pucdn.me
  port: 62009
  type: vmess
  uuid: 782e9cbb-07f7-3c3f-a89d-d3047081578d
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /vvv
  ws-headers:
    Host: L1-aws-hk-10.pucdn.me
- name: ' 新加坡AWS 06 Netflix 1x1512'
  server: global-transit-02-hk.pucdn.me
  port: 61005
  type: vmess
  uuid: 782e9cbb-07f7-3c3f-a89d-d3047081578d
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /vvv
  ws-headers:
    Host: l1-aws-sg-06.pucdn.me
- name: 34捐赠解锁更多协议线路1938
  server: yqy2334.china-cdn-net.com
  port: 2334
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2334.china-cdn-net.com
- name: ' HTW高雄龍抬頭HiNetVC332371943'
  server: yqy33237.china-cdn-net.com
  port: 33237
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33237.china-cdn-net.com
- name: ' 新加坡SG 04 AWS 1x1513'
  server: global-transit-01-hk.pucdn.me
  port: 31125
  type: vmess
  uuid: 782e9cbb-07f7-3c3f-a89d-d3047081578d
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /vvv
  ws-headers:
    Host: L2-aws-sg-04.pucdn.me
- name: ' 新加坡SG 08 AWS 1x1514'
  server: global-transit-01-hk.pucdn.me
  port: 31129
  type: vmess
  uuid: 782e9cbb-07f7-3c3f-a89d-d3047081578d
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /vvv
  ws-headers:
    Host: L2-aws-sg-08.pucdn.me
- name: ' HTW高雄龍抬頭HiNetVC331351949'
  server: yqy33135.china-cdn-net.com
  port: 33135
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33135.china-cdn-net.com
- name: ' 台湾5 原生广州移动V21533'
  server: icajm.moox.icu
  port: 34005
  type: vmess
  uuid: e94d3ed5-d94c-49ea-9a6c-830b247a1656
  alterId: 1
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /
  ws-headers:
    Host: icajm.moox.icu
- name: ' H3xHKHKTBGPVC361331951'
  server: yqy36133.china-cdn-net.com
  port: 36133
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36133.china-cdn-net.com
- name: ' ITW高雄龍抬頭HiNetVC331371963'
  server: yqy33137.china-cdn-net.com
  port: 33137
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33137.china-cdn-net.com
- name: ' 韩国AWS 05 Netflix 1x1522'
  server: global-transit-02-hk.pucdn.me
  port: 63005
  type: vmess
  uuid: 782e9cbb-07f7-3c3f-a89d-d3047081578d
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /vvv
  ws-headers:
    Host: L1-aws-kr-05.pucdn.me
- name: ' 香港HKT 08 PPCW Netflix 1x1530'
  server: global-transit-01-hk.pucdn.me
  port: 11115
  type: vmess
  uuid: 782e9cbb-07f7-3c3f-a89d-d3047081578d
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /vvv
  ws-headers:
    Host: l2-hkt-a-08.pucdn.me
- name: 36中继中转隧道线路覆盖1940
  server: yqy2336.china-cdn-net.com
  port: 2336
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2336.china-cdn-net.com
- name: 台湾011921
  type: vmess
  server: jike-cccn2.ddns-only.xyz
  port: 39205
  uuid: b8da3f41-58ec-3294-891e-cc27ecb1244a
  alterId: 2
  cipher: auto
  udp: true
  network: ws
  ws-path: /jike1
  ws-headers:
    Host: jike1-hinet03.ddns-only.xyz
- name: 虎窝vmess节点222265
  server: 139.155.22.227
  port: 49110
  type: vmess
  uuid: f7675b7e-59bf-435c-ac03-dc2482f27e5d
  alterId: 64
  cipher: auto
  tls: false
- name: RelaySG678721
  server: 8.ssrj.xyz
  type: vmess
  port: 65108
  uuid: 24ea3f63-d495-3a0a-a7de-f92a4e6fb9ae
  alterId: 2
  cipher: auto
  network: tcp
  ws-path: /
  http-opts: {}
  h2-opts: {}
- name: ' RelayRU6363  684Mb1555'
  server: els.jklist.ga
  port: 443
  type: vmess
  uuid: 25290405-8ef7-4561-acc0-0d234fe8d9da
  alterId: 1
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /TS/recharge/tzUrl.html
  ws-headers:
    Host: els.jklist.ga
- name: ' 日本AWS 05 Netflix 1x1515'
  server: global-transit-01-hk.pucdn.me
  port: 40005
  type: vmess
  uuid: 782e9cbb-07f7-3c3f-a89d-d3047081578d
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /vvv
  ws-headers:
    Host: l1-aws-jp-05.pucdn.me
- name: 33公益等级線路嚴格限速1937
  server: yqy2333.china-cdn-net.com
  port: 2333
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /
  ws-headers:
    Host: yqy2333.china-cdn-net.com
- name: ' 韩国AWS 01 Netflix 1x1521'
  server: global-transit-02-hk.pucdn.me
  port: 63001
  type: vmess
  uuid: 782e9cbb-07f7-3c3f-a89d-d3047081578d
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /vvv
  ws-headers:
    Host: L1-aws-kr-01.pucdn.me
- name: ' I6xTW台北HiNetVC311371968'
  server: yqy31137.china-cdn-net.com
  port: 31137
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31137.china-cdn-net.com
- name: ' 香港AWS 08 Netflix 1x1526'
  server: global-transit-02-hk.pucdn.me
  port: 62007
  type: vmess
  uuid: 782e9cbb-07f7-3c3f-a89d-d3047081578d
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /vvv
  ws-headers:
    Host: L1-aws-hk-08.pucdn.me
- name: 35包括V2ray和Trojan1939
  server: yqy2335.china-cdn-net.com
  port: 2335
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2335.china-cdn-net.com
- name: ' I5xTW台北HiNetVC311311959'
  server: yqy31131.china-cdn-net.com
  port: 31131
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31131.china-cdn-net.com
- name: ' TGNGK668 RelayCNUS26911537'
  server: us1.np.qjnodeip.xyz
  port: 10018
  type: vmess
  uuid: fcd5281b-fb21-48fc-bcbf-31cd4c441c86
  alterId: 1
  cipher: auto
  tls: false
  skip-cert-verify: false
- name: ' 中国香港12 86Mbps 553ms 奈飞自制剧1877'
  server: cm01.onon.cloud
  port: 23311
  type: vmess
  uuid: 9e9eabb7-3759-3627-b8b4-fc38995b0412
  alterId: 1
  cipher: auto
  tls: false
  network: ws
  ws-path: /db
  ws-headers:
    Host: hk01.onon.cloud
- name: ' 沪台HINET 07 Netflix  動畫瘋 1x1520'
  server: global-transit-01-hk.pucdn.me
  port: 21107
  type: vmess
  uuid: 782e9cbb-07f7-3c3f-a89d-d3047081578d
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /vvv
  ws-headers:
    Host: L2-tw-07.pucdn.me
- name: ' httpsgitiov9999 圣何塞 51297'
  server: 107.148.200.229
  port: 51267
  type: vmess
  uuid: dd6fc0ba-10ac-11ec-bb46-00163c0ad178
  alterId: 0
  cipher: auto
  tls: false
- name: ' 印度IN01 CDN加速 1x1509'
  server: global-transit-01-hn.pucdn.me
  port: 60001
  type: vmess
  uuid: 782e9cbb-07f7-3c3f-a89d-d3047081578d
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /vvv
  ws-headers:
    Host: l2-in-01.pucdn.me
