proxies:
- name: 6.94|香港阿伟科技TG油管 2
  server: 5.vpnbro.ml
  port: 6666
  type: trojan
  password: 04a2dba8-1af1-4b30-aabf-a2eeca2a3cb3
  sni: 5.vpnbro.ml
  skip-cert-verify: true
  udp: true
- name: 6.19|香港阿伟科技TG油管 3
  server: 3.vpnbro.ml
  port: 9999
  type: trojan
  password: 04a2dba8-1af1-4b30-aabf-a2eeca2a3cb3
  sni: 3.vpnbro.ml
  skip-cert-verify: true
  udp: true
- name: 5.31| githubcomfreefq  美国CloudFlare节点 19
  server: 198.41.212.9
  port: 443
  type: vmess
  uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /sakura/
  ws-headers:
    Host: zero1.a-yu.xyz
- name: 4.03|Relay7534Mb
  server: hkt.jslist.tk
  type: vmess
  country: US
  port: 8880
  uuid: efe08abe-e627-4f72-f02f-af00692a0bf4
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /api/images
  servername: hkt.jslist.tk
  ws-headers:
    HOST: hkt.jslist.tk
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 3.80|CYL科技20220213 92
  server: vds.sgp.tgproxy.wtf
  port: 21888
  type: vmess
  uuid: 061a5ca3-09f7-413e-8d4d-35775bb5c0eb
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /theuploadapi
  ws-headers:
    Host: t.me/lqmoe
  udp: true
- name: 3.58|Relay 650Mb
  server: arm.50k.one
  type: vmess
  country: JP
  port: 39966
  uuid: 608408f6-fd79-49a3-96ef-003266a773a0
  alterId: 0
  cipher: auto
  network: tcp
  ws-path: /
  servername: arm.50k.one
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 3.39| 韩国 2
  server: amd.50k.one
  port: 30943
  type: vmess
  uuid: a0654eba-7b58-4d64-cfdb-c006e5d38324
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: false
  udp: true
- name: 3.32| RelayUSZZ2841 2418Mb
  server: cloudflare.a-yu.xyz
  port: 443
  type: vmess
  uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /sakura/
  ws-headers:
    Host: zero2.a-yu.xyz
- name: 2.70| RelaySGSG1285 1819Mb
  server: do3.xjp.tgproxy.wtf
  port: 21888
  type: vmess
  uuid: 061a5ca3-09f7-413e-8d4d-35775bb5c0eb
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /theuploadapi
  ws-headers:
    Host: do3.xjp.tgproxy.wtf
- name: 2.52|CYL科技20220213 2
  server: oracle.kr.tgproxy.wtf
  port: 21888
  type: vmess
  uuid: 061a5ca3-09f7-413e-8d4d-35775bb5c0eb
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /theuploadapi
  ws-headers:
    Host: oracle.kr.tgproxy.wtf
  udp: true
- name: 2.11|Pool4145Mb
  server: 217.138.204.202
  type: vmess
  country: AU
  port: 443
  uuid: fa1eff46-f454-42d9-b881-90a102d5521d
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ray
  servername: govacaxixo.watchdoctor.xyz
  ws-headers:
    HOST: govacaxixo.watchdoctor.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 2.11|httpsgitiov9999ip39
  server: 104.16.181.103
  port: 443
  type: vmess
  uuid: 7be43971-52f1-48af-9036-454a94b4723a
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /ws/?ed=2048
    headers:
      Host: download.china666.ml
- name: 1.88|Relay1000Mb
  server: 69.64.248.199
  type: vmess
  country: JP
  port: 443
  uuid: 7235b329-e205-4fcb-bcd6-81c19fbb9e85
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ray
  servername: govacaxixo.watchdoctor.xyz
  ws-headers:
    HOST: govacaxixo.watchdoctor.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 1.75| RelaySESE1132
  server: se.oceancloud.asia
  port: 12100
  type: vmess
  uuid: adfc4bf6-8f7d-393e-9997-7dd969d9ea88
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-path: /se
  ws-headers:
    Host: se.oceancloud.asia
- name: 1.72| httpsgitiov9999ip3韩国2
  server: 128.1.125.164
  port: 443
  type: vmess
  uuid: 312c3de7-233e-4d72-b3dc-de0205083312
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /ray
    headers:
      Host: govacaxixo.watchdoctor.xyz
- name: 1.70|CYL科技20220213 81
  server: fg.jgw.tgproxy.wtf
  port: 443
  type: vmess
  uuid: 061a5ca3-09f7-413e-8d4d-35775bb5c0eb
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /theuploadapi
  ws-headers:
    Host: fg.jgw.tgproxy.wtf
  udp: true
- name: 1.66|美国阿伟科技TG油管 4
  server: ggz.jgw.tgproxy.wtf
  port: 80
  type: vmess
  uuid: 061a5ca3-09f7-413e-8d4d-35775bb5c0eb
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /theuploadapi
  ws-headers:
    Host: ggz.jgw.tgproxy.wtf
  udp: true
- name: 1.65|Pool1020Mb
  server: 37.61.213.94
  type: vmess
  country: DE
  port: 443
  uuid: 97ff78ea-8807-4c33-93e5-d8481ac0539e
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ray
  servername: govacaxixo.watchdoctor.xyz
  ws-headers:
    HOST: govacaxixo.watchdoctor.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 1.64|Relay3929Mb
  server: 45.76.127.189
  type: vmess
  country: AU
  port: 443
  uuid: 7fc6764a-6cba-4599-95d7-ac7617b7db0a
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ray
  servername: govacaxixo.watchdoctor.xyz
  ws-headers:
    HOST: govacaxixo.watchdoctor.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 1.57|德国阿伟科技TG油管 3
  server: dg.jgw.tgproxy.wtf
  port: 443
  type: vmess
  uuid: 061a5ca3-09f7-413e-8d4d-35775bb5c0eb
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /theuploadapi
  ws-headers:
    Host: dg.jgw.tgproxy.wtf
  udp: true
- name: 1.56|Pool 946Mb
  server: 92.223.72.42
  type: vmess
  country: RU
  port: 443
  uuid: ae08412f-5bb9-4be7-8560-1984976a1097
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ray
  servername: govacaxixo.watchdoctor.xyz
  ws-headers:
    HOST: govacaxixo.watchdoctor.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 1.55|新加坡阿伟科技TG油管 7
  server: 4.vpnbro.ml
  port: 9999
  type: trojan
  password: 04a2dba8-1af1-4b30-aabf-a2eeca2a3cb3
  sni: 4.vpnbro.ml
  skip-cert-verify: true
  udp: true
- name: 1.54|PoolRU8932011Mb
  server: 92.223.65.119
  type: vmess
  country: RU
  port: 443
  uuid: 3fd6713f-e036-4ba9-938a-da7843a17a15
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ray
  servername: govacaxixo.watchdoctor.xyz
  ws-headers:
    HOST: govacaxixo.watchdoctor.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 1.54|RU俄罗斯联邦Youtube技术分享室 3
  server: 146.185.218.171
  port: 443
  type: vmess
  uuid: 947af181-c509-4245-80de-9baf64f1aa51
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /ray
  ws-headers:
    Host: govacaxixo.watchdoctor.xyz
  udp: true
- name: 1.51|Pool2608Mb
  server: 37.120.134.207
  type: vmess
  country: GB
  port: 443
  uuid: 5c0beec7-9b91-4e28-85b0-e3ff49b4ac50
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ray
  servername: govacaxixo.watchdoctor.xyz
  ws-headers:
    HOST: govacaxixo.watchdoctor.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 1.49|CYL科技20220213 36
  server: niaop.tk
  port: 443
  type: vmess
  uuid: a0b0df87-bda2-440e-830f-347da6cc7760
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /wsssdr1
  ws-headers:
    Host: niaop.tk
  udp: true
- name: 1.48| 韩国 1
  server: vn.mumi.bid
  port: 10125
  type: vmess
  uuid: 83ae9f04-47f0-4e34-9a1c-9c2e5161f586
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: vn.mumi.bid
  udp: true
- name: 1.39|CYL科技20220213 147
  server: 162.159.204.177
  port: 443
  type: vmess
  uuid: 71d4f911-39c1-4f37-dc56-f893fab50e41
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /freebaipiao
  ws-headers:
    Host: haxovz.aifx.eu.org
  udp: true
- name: 1.34|AE193123951141244
  server: 193.123.95.114
  port: 21999
  type: vmess
  uuid: 061a5ca3-09f7-413e-8d4d-35775bb5c0eb
  alterId: 0
  cipher: auto
  skip-cert-vertify: false
  network: ws
  ws-path: /
  tls: false
  ws-headers:
    Host: 193.123.95.114
- name: 1.30| RelayUSRU2791  773Mb
  server: v6ru1.moonfree.top
  port: 443
  type: vmess
  uuid: 5638fc1a-c3c0-41fd-acb6-2e302e7be794
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /
  ws-headers:
    Host: v6ru.moonfree.top
- name: 1.27|CYL科技20220213 71
  server: gia.uk.tgproxy.wtf
  port: 443
  type: vmess
  uuid: 061a5ca3-09f7-413e-8d4d-35775bb5c0eb
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /theuploadapi
  ws-headers:
    Host: gia.uk.tgproxy.wtf
  udp: true
- name: 1.25|RelayCACA2861660Mb
  server: t1.ssrsub.com
  type: trojan
  country: CA
  port: 8443
  password: 21627f29-0d0f-4dfa-9740-b5ee360bf061
  skip-cert-verify: true
  udp: true
- name: 1.16|defaultname118
  server: test.0dc.cn
  port: 443
  type: vmess
  uuid: ebe5703b-c18e-4664-c3a7-9fcf52453898
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /
- name: 1.13|US24492389Mb
  server: 209.141.35.147
  type: trojan
  country: US
  port: 48919
  password: 52911320-db53-40ff-917a-e5de797c28e7
  skip-cert-verify: true
  udp: true
- name: 1.09|韩国阿伟科技TG油管 3
  server: v.mumi.bid
  port: 10121
  type: vmess
  uuid: 403acd13-9d60-44f1-ac2d-0359cd5e2d7e
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /
  ws-headers:
    Host: v.mumi.bid
  udp: true
- name: 1.03|RelayUAUA1299  641Mb
  server: lv.tgproxy.wtf
  port: 2052
  type: vmess
  uuid: ae7486f9-d7b7-4f26-97a0-dc5b093dfa89
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /theuploadapi
  ws-headers:
    Host: lv.tgproxy.wtf
