proxies:
- name: '124'
  server: 62.216.92.179
  type: trojan
  country: RO
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- alterId: 1
  cipher: auto
  name: 0924oslook中国香港特别行政区HKHongkong SAR ChinaHong Kong62844
  network: ws
  port: 2053
  server: hk01.uuv2.uk
  tls: true
  type: vmess
  uuid: f852dffa-8b5c-4bb0-9182-999465b79b91
  ws-headers:
    Host: hk01.uuv2.uk
  ws-path: /mftizi
- name: JP80012782982302
  server: 45.66.134.219
  type: trojan
  country: JP
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  skip-cert-verify: true
  udp: true
- name: JP74842087
  server: 139.162.123.246
  type: vmess
  country: JP
  port: 65443
  uuid: 9690fd84-9c5c-4cba-8a53-fb30bb8ae5c9
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /2defe1820b908f6/
  servername: jp4.piyou.cyou
  ws-headers:
    HOST: jp4.piyou.cyou
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: SG11295  268Mb2112
  server: 188.166.242.117
  type: trojan
  country: SG
  port: 4443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: ' JP90277'
  server: 139.162.123.161
  type: vmess
  country: ' JP'
  port: 65443
  uuid: 42cd918b-36b8-4c00-a58d-0a7fcf0b2df2
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /d39d32d2fd37/
  servername: jp2.piyou.cyou
  ws-headers:
    HOST: jp2.piyou.cyou
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: RelayUSUS107  768Mb2069
  server: agals03.cloudddns.icu
  type: trojan
  country: US
  port: 124
  password: f45d308f-d9bc-3954-982f-40883392fb8e
  skip-cert-verify: true
  udp: true
- name: ' HK欢迎订阅youtube8度科技 101067'
  server: agals04.cloudddns.icu
  port: 992
  type: trojan
  password: f45d308f-d9bc-3954-982f-40883392fb8e
  sni: agals04.cloudddns.icu
  skip-cert-verify: false
- name: RelayUSUS106  931Mb2068
  server: agals02.subyyds.xyz
  type: trojan
  country: US
  port: 124
  password: f45d308f-d9bc-3954-982f-40883392fb8e
  skip-cert-verify: true
  udp: true
- name: RelayUSUS13372026
  server: nn-ssr24.feiclouddd.me
  type: vmess
  country: US
  port: 443
  uuid: 94d3ddba-3c75-4ddd-84c5-b859a30b1fb9
  alterId: 60
  cipher: auto
  network: ws
  ws-path: /dsafasdf
  servername: nn-ssr24.feiclouddd.me
  ws-headers:
    HOST: nn-ssr24.feiclouddd.me
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: SanJose1983782288
  server: sanjose.cscecsr.tk
  port: 443
  type: trojan
  password: abc123
  sni: sanjose.cscecsr.tk
  skip-cert-verify: true
  udp: true
- name: ' Game 3 PPhttp1986792289'
  type: trojan
  server: sg2-trojan.bonds.id
  port: 443
  password: 7d450710-f1ad-11eb-a226-1239d0255272
  udp: true
  sni: pmsc.pubgmobile.com
  alpn:
  - h2c
  - http/1.1
  skip-cert-verify: true
- name: US180052137
  server: 173.82.55.94
  type: vmess
  country: US
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.01787634.xyz
  ws-headers:
    HOST: www.01787634.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: DE3726 1111Mb2759952299
  server: 194.195.124.174
  type: trojan
  country: DE
  port: 4443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: US1983129401192317
  server: 72.167.33.106
  type: trojan
  country: US
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  skip-cert-verify: true
  udp: true
- name: trojan735
  type: trojan
  server: 65.49.196.246
  port: 443
  password: 123abc,./
  sni: ztinoz.com
  alpn:
  - h2
  - http/1.1
- alterId: 64
  cipher: auto
  name: 0924oslook美国USUSASanta Clarita28827
  network: ws
  port: 443
  server: 173.82.55.93
  tls: true
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  ws-headers:
    Host: www.01787634.xyz
  ws-path: /footers
- name: ' Russia1982772287'
  server: russia.cscecsr.tk
  port: 443
  type: trojan
  password: abc123
  sni: russia.cscecsr.tk
  skip-cert-verify: true
  udp: true
- name: '1883'
  server: 67.21.72.41
  type: vmess
  country: US
  port: 443
  uuid: 2566d00f-218c-48f7-9a36-13d3d6f1a724
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.17080100.xyz
  ws-headers:
    HOST: www.17080100.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US19790509
  server: 96.45.187.26
  type: vmess
  country: US
  port: 443
  uuid: 6da431e4-d7b1-4f61-b3e2-f3f8d6f03bb8
  alterId: 60
  cipher: auto
  network: ws
  ws-path: /sdafasfsa
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: JP80002781972301
  server: 5.183.177.111
  type: trojan
  country: JP
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  skip-cert-verify: true
  udp: true
- name: '155'
  server: 67.21.72.35
  type: vmess
  country: US
  port: 443
  uuid: 2566d00f-218c-48f7-9a36-13d3d6f1a724
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: Ket YT1130
  type: trojan
  server: sg6-trojan.bonds.id
  port: 443
  password: 7a80c340-f911-11eb-a7cb-1239d0255272
  udp: true
  sni: m.youtube.com
  alpn:
  - h2
  - http/1.1
  skip-cert-verify: true
- name: GB5830 1091Mb2761962300
  server: 138.68.179.78
  type: trojan
  country: GB
  port: 1443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: US179962128
  server: 104.251.233.106
  type: vmess
  country: US
  port: 13723
  uuid: a90597c1-bab3-4217-ad6f-0838675c8638
  alterId: 10
  cipher: auto
  network: ws
  ws-path: /ray
  servername: en.tgchannels.org/channel/vpnpool
  ws-headers:
    HOST: en.tgchannels.org/channel/vpnpool
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US179872119
  server: 128.14.157.112
  type: vmess
  country: US
  port: 13723
  uuid: a90597c1-bab3-4217-ad6f-0838675c8634
  alterId: 10
  cipher: auto
  network: ws
  ws-path: /ray
  servername: en.tgchannels.org/channel/vpnpool
  ws-headers:
    HOST: en.tgchannels.org/channel/vpnpool
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: NL894928101022306
  server: 178.62.201.120
  type: trojan
  country: NL
  port: 4443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: RelayAUDE3492337892295
  server: 1.0.0.0
  type: vmess
  country: AU
  port: 443
  uuid: 3b5e258e-8c5e-45d3-b7d2-02c8f5fc0bb2
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /
  servername: cdnde.irteyz.today
  ws-headers:
    HOST: cdnde.irteyz.today
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: NL895628171032307
  server: 89.31.127.151
  type: trojan
  country: NL
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  skip-cert-verify: true
  udp: true
- name: RelayUSUS13392028
  server: 198.211.30.163
  type: vmess
  country: US
  port: 443
  uuid: 6aaa2f9f-7c91-4b51-aa77-05a83a5d6a4d
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.93289686.xyz
  ws-headers:
    HOST: www.93289686.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- alterId: 64
  cipher: auto
  name: 0924oslook美国USUSASan Jose25824
  network: ws
  port: 443
  server: 107.148.198.53
  tls: true
  type: vmess
  uuid: 4c7923df-700f-4bf2-918e-08c6e141037c
  ws-headers:
    Host: www.78577665.xyz
  ws-path: /footers
- name: '1832'
  server: t4.ssrsub.one
  type: trojan
  country: RU
  port: 8443
  password: 217010a3-c48d-4c42-9b99-c4dfc173ec78
  skip-cert-verify: true
  udp: true
- name: RO879620782250
  server: 185.105.191.92
  type: trojan
  country: RO
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: RelayRURU12356475
  server: ru01.uuv2.uk
  type: vmess
  country: RU
  port: 2053
  uuid: f852dffa-8b5c-4bb0-9182-999465b79b91
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: RelayUSUS105  884Mb2067
  server: us01.tencentlink.icu
  type: trojan
  country: US
  port: 10000
  password: 42c2d9d7-d55c-4d6c-ba0a-47bf312b4ab6
  skip-cert-verify: true
  udp: true
- name: ' githubcomfreefq  俄罗斯新西伯利亚JustHost 471524'
  server: t3.ssrsub.one
  port: 8443
  type: trojan
  password: ed4b6594-ea16-40f6-a935-f3985c433973
  sni: t3.ssrsub.one
- name: ' 香港 02 Microsoft1570'
  server: azure-f4s-hk.transfer-xray.tk
  port: 53420
  type: vmess
  uuid: 1b93051f-c9ad-4908-874e-ccb5e8da27ef
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /liuwei
  ws-headers:
    Host: usss222.liuwei01.tk
