proxies:
- name: 1.84|trojan
  type: trojan
  server: 65.49.196.246
  port: 443
  password: 123abc,./
  sni: ztinoz.com
  alpn:
  - h2
  - http/1.1
- name: 1.83|US16346
  server: 72.167.45.6
  type: trojan
  country: US
  port: 443
  password: a3fa58b581353bb375d2ddad0f327938
  skip-cert-verify: true
  udp: true
- name: 1.43|  292Mb
  server: 72.167.33.106
  type: trojan
  country: US
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  skip-cert-verify: true
  udp: true
- name: 1.42|659 10893Mb
  server: t6.ssrsub.com
  type: trojan
  port: 8443
  password: 360ecd87-72e8-4706-b252-79d0d0cfe6aa
  sni: t6.ssrsub.com
  udp: true
