proxies:
- name: RelayUS2016  460Mb653
  server: nna.boom.party
  type: ssr
  country: CN
  port: 49000
  password: Uk92CS
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 254637:Ol4zZv
  obfs: http_simple
  obfs-param: download.windowsupdate.com
- name: NodeTest 7  4129 KB1428
  server: ntemp04.boom.party
  port: 13000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
  udp: true
  speedtest: 422812
- name: NodeTest 42  30751 KB1461
  server: opt2.boom.party
  port: 12000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
  udp: true
  speedtest: 314887
- name: NodeTest 43  30567 KB1462
  server: opt7.boom.party
  port: 17000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
  udp: true
  speedtest: 313007
- name: NodeTest 30  33574 KB1450
  server: opt1.boom.party
  port: 11000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
  udp: true
  speedtest: 343795
- name: NodeTest 38  32405 KB1457
  server: n100.boom.party
  port: 15000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
  udp: true
  speedtest: 331827
- name: NodeTest 11  38067 KB1432
  server: nf2.boom.party
  port: 12000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
  udp: true
  speedtest: 389805
- name: RelayCNHK3022150
  server: ntemp08.boom.party
  type: ssr
  country: CN
  port: 17000
  password: Uk92CS
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 254637:Ol4zZv
  obfs: http_simple
  obfs-param: download.windowsupdate.com
- name: NodeTest 23  34247 KB1444
  server: nl2.boom.party
  port: 23000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
  udp: true
  speedtest: 350694
- name: NodeTest 13  37647 KB1434
  server: ntemp06.boom.party
  port: 15000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
  udp: true
  speedtest: 385505
- name: NodeTest 46  29854 KB1464
  server: opt11.boom.party
  port: 21000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
  udp: true
  speedtest: 305707
- name: RelayCNHK3037165
  server: n37.boom.party
  type: ssr
  country: CN
  port: 33300
  password: Uk92CS
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 254637:Ol4zZv
  obfs: http_simple
  obfs-param: download.windowsupdate.com
- name: NodeTest 77  21467 KB1478
  server: nl1.boom.party
  port: 22000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
  udp: true
  speedtest: 219827
- name: ' Relay馃嚚馃嚦CN馃嚟馃嚢HK2027 2159Mb1907'
  server: ntemp25.boom.party
  port: 11000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
- name: NodeTest 4  44912 KB1425
  server: nn8.boom.party
  port: 47000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
  udp: true
  speedtest: 459901
- name: NodeTest 56  27453 KB1470
  server: n116.boom.party
  port: 33200
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
  udp: true
  speedtest: 281119
- name: ' H3xTW台北HiNetRC311261860'
  server: yqy31126.china-cdn-net.com
  port: 31126
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' Relay馃嚚馃嚦CN馃嚞馃嚙GB2019 1011Mb1905'
  server: n06.boom.party
  port: 21000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
- name: NodeTest 27  33907 KB1447
  server: nl6.boom.party
  port: 27000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
  udp: true
  speedtest: 347210
- name: NodeTest 68  23649 KB1477
  server: opt10.boom.party
  port: 20000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
  udp: true
  speedtest: 242165
- name: ' Relay馃嚚馃嚦CN馃嚟馃嚢HK2020  356Mb1912'
  server: ntemp09.boom.party
  port: 18000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
- name: ' Relay馃嚚馃嚦CN馃嚟馃嚢HK2011  917Mb1902'
  server: njb.boom.party
  port: 21000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
- name: NodeTest 22  34362 KB1443
  server: opt23.boom.party
  port: 33000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
  udp: true
  speedtest: 351871
- name: ' I6xHKHKTBGPRC361241881'
  server: yqy36124.china-cdn-net.com
  port: 36124
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' Relay馃嚚馃嚦CN馃嚫馃嚞SG2021 1127Mb1903'
  server: n05.boom.party
  port: 30001
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
- name: NodeTest 64  24734 KB1475
  server: n30.boom.party
  port: 19000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
  udp: true
  speedtest: 253279
- name: NodeTest 18  36702 KB1439
  server: opt4.boom.party
  port: 14000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
  udp: true
  speedtest: 375833
- name: ' I6xTW台北HiNetRC311281888'
  server: yqy31128.china-cdn-net.com
  port: 31128
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: NodeTest 34  33355 KB1453
  server: nl5.boom.party
  port: 26000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
  udp: true
  speedtest: 341555
- name: ' ITW高雄龍抬頭HiNetRC331281878'
  server: yqy33128.china-cdn-net.com
  port: 33128
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' Relay馃嚚馃嚦CN馃嚟馃嚢HK2026  454Mb1908'
  server: n92.boom.party
  port: 16000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
- name: ' I6xHKHKTBGPRC362241882'
  server: yqy36224.china-cdn-net.com
  port: 36224
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' HTW高雄龍抬頭HiNetRC331211826'
  server: yqy33121.china-cdn-net.com
  port: 33121
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' H25xTW台北HiNetRC312221831'
  server: yqy31222.china-cdn-net.com
  port: 31222
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' I5xTW台北HiNetRC311221869'
  server: yqy31122.china-cdn-net.com
  port: 31122
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' H3xTW台北HiNetRC311251859'
  server: yqy31125.china-cdn-net.com
  port: 31125
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' Relay馃嚚馃嚦CN馃嚭馃嚫US2002 1743Mb1922'
  server: njc.boom.party
  port: 22000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
- name: ' Relay馃嚚馃嚦CN馃嚫馃嚞SG1991 1957Mb1906'
  server: opt22.boom.party
  port: 32000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
- name: CN3015143
  server: ntemp10.boom.party
  type: ssr
  country: CN
  port: 20000
  password: Uk92CS
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 254637:Ol4zZv
  obfs: http_simple
  obfs-param: download.windowsupdate.com
- name: ' HTW高雄龍抬頭HiNetRC332271827'
  server: yqy33227.china-cdn-net.com
  port: 33227
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: NodeTest 65  24038 KB1476
  server: ntemp15.boom.party
  port: 19000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
  udp: true
  speedtest: 246144
- name: ' H25xTW彰化HiNetRC322221835'
  server: yqy32222.china-cdn-net.com
  port: 32222
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' I5xTW台北HiNetRC312231870'
  server: yqy31223.china-cdn-net.com
  port: 31223
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' H3xHKHKTBGPRC362231854'
  server: yqy36223.china-cdn-net.com
  port: 36223
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' Game 3 PPhttp1937'
  type: trojan
  server: sg2-trojan.bonds.id
  port: 443
  password: 7d450710-f1ad-11eb-a226-1239d0255272
  udp: true
  sni: pmsc.pubgmobile.com
  alpn:
  - h2c
  - http/1.1
  skip-cert-verify: true
- name: ' H3xHKHKTBGPRC361231853'
  server: yqy36123.china-cdn-net.com
  port: 36123
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' I5xTW彰化HiNetRC322231874'
  server: yqy32223.china-cdn-net.com
  port: 32223
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' Relay馃嚚馃嚦CN馃嚫馃嚞SG2007 2053Mb1911'
  server: nl3.boom.party
  port: 24000
  type: ssr
  cipher: aes-256-cfb
  password: Uk92CS
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 254637:Ol4zZv
  obfs-param: download.windowsupdate.com
- name: SG8746265
  server: 81.90.189.85
  type: trojan
  country: SG
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: ' ITW高雄龍抬頭HiNetRC331221867'
  server: yqy33122.china-cdn-net.com
  port: 33122
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
