proxies:
- name: 5.42|httpsgitiov9999ip312
  server: 198.41.212.13
  port: 443
  type: vmess
  uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /sakura/
    headers:
      Host: zero1.a-yu.xyz
- name: 4.92| githubcomfreefq  美国CloudFlare节点 32
  server: 198.41.212.9
  port: 443
  type: vmess
  uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /sakura/
  ws-headers:
    Host: zero1.a-yu.xyz
- name: 3.21|CYL科技20220213 19
  server: aws.kr.tgproxy.wtf
  port: 21888
  type: vmess
  uuid: 061a5ca3-09f7-413e-8d4d-35775bb5c0eb
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /theuploadapi
  ws-headers:
    Host: aws.kr.tgproxy.wtf
  udp: true
- name: 2.91|CYL科技20220213 3
  server: oracle.kr.tgproxy.wtf
  port: 21888
  type: vmess
  uuid: 061a5ca3-09f7-413e-8d4d-35775bb5c0eb
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /theuploadapi
  ws-headers:
    Host: oracle.kr.tgproxy.wtf
  udp: true
- name: 2.32|RelayUSUS23601390Mb
  server: 56789.gq
  type: trojan
  country: US
  port: 443
  password: dc1453e4-e5c4-4b30-bee3-6ed2adce9ee3
  skip-cert-verify: true
  udp: true
- name: 2.29|CYL科技20220213 28
  server: tfn.tw.tgproxy.wtf
  port: 8888
  type: vmess
  uuid: 061a5ca3-09f7-413e-8d4d-35775bb5c0eb
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /theuploadapi
  ws-headers:
    Host: tfn.tw.tgproxy.wtf
  udp: true
- name: 1.99|CYL科技20220213 134
  server: 72.11.136.212
  port: 443
  type: vmess
  uuid: 6b02b504-ead6-4939-ba1c-afa5b92a6f6d
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /ray
  ws-headers:
    Host: govacaxixo.watchdoctor.xyz
  udp: true
- name: 1.97|CYL科技20220213 138
  server: ce.xjp.tgproxy.wtf
  port: 21888
  type: vmess
  uuid: aeaaff19-bb0b-434d-b206-0f2a3f4d90e9
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /theuploadapi
  ws-headers:
    Host: ce.xjp.tgproxy.wtf
  udp: true
- name: 1.88|USwmt212111
  server: 6.lyzghim.com
  port: 443
  type: vmess
  uuid: 2bb8823b-6938-4c82-87dc-0dee4c118b2d
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /qwe
    host: 6.lyzghim.com
- name: 1.87|RelayRURU8511224Mb
  server: 5.188.35.120
  type: vmess
  country: RU
  port: 443
  uuid: 0c7a06d0-8061-4df7-b521-960e2b9ce0f7
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ray
  servername: govacaxixo.watchdoctor.xyz
  ws-headers:
    HOST: govacaxixo.watchdoctor.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 1.84|US15420810120810
  server: ceraus.moonfree.top
  port: 443
  type: vmess
  uuid: 00c4674c-3c41-4b77-909e-feed63066b91
  alterId: 0
  cipher: auto
  skip-cert-vertify: false
  network: ws
  ws-path: /
  tls: true
  ws-headers:
    Host: ceraus.moonfree.top
- name: 1.79|Relay2369Mb
  server: 45.76.127.189
  type: vmess
  country: AU
  port: 443
  uuid: 7fc6764a-6cba-4599-95d7-ac7617b7db0a
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ray
  servername: govacaxixo.watchdoctor.xyz
  ws-headers:
    HOST: govacaxixo.watchdoctor.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 1.75| httpsgitiov9999ip3美国2
  server: 192.3.145.143
  port: 443
  type: vmess
  uuid: f2ac5a3b-575f-4888-8997-43958deda5a4
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /ray
    headers:
      Host: govacaxixo.watchdoctor.xyz
- name: 1.74|小汐搬运04承接灰产代收付回U对接API支付通道电报httpstmemengmenng
  server: v2ray.ifuckgfw.ga
  port: 8443
  type: vmess
  uuid: a1effd82-8a11-11ec-9aeb-52ac0014346a
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /nBaG3RmV/
  ws-headers:
    Host: v2ray.ifuckgfw.ga
- name: 1.72| httpsgitiov9999ip3韩国2
  server: 128.1.125.164
  port: 443
  type: vmess
  uuid: 312c3de7-233e-4d72-b3dc-de0205083312
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /ray
    headers:
      Host: govacaxixo.watchdoctor.xyz
- name: 1.70| httpsgitiov9999ip3法国51 2
  server: fg.jgw.tgproxy.wtf
  port: 443
  type: vmess
  uuid: 061a5ca3-09f7-413e-8d4d-35775bb5c0eb
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /theuploadapi
    headers:
      Host: fg.jgw.tgproxy.wtf
- name: 1.69|CYL科技20220213 64
  server: aws.us.tgproxy.wtf
  port: 21888
  type: vmess
  uuid: aeaaff19-bb0b-434d-b206-0f2a3f4d90e9
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /theuploadapi
  ws-headers:
    Host: aws.us.tgproxy.wtf
  udp: true
- name: 1.62|CYL科技20220213 58
  server: 134.119.176.171
  port: 443
  type: vmess
  uuid: b1a868c2-cba7-42c5-bba5-ae158894402e
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /ray
  ws-headers:
    Host: govacaxixo.watchdoctor.xyz
  udp: true
- name: 1.61| httpsgitiov9999ip3美国1
  server: 196.247.24.156
  port: 443
  type: vmess
  uuid: c028c1ff-c006-4dc7-bd7e-a61c99b4f306
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /ray
    headers:
      Host: govacaxixo.watchdoctor.xyz
- name: 1.58|RelayUSUS23541286Mb
  server: www.darkwater.xyz
  type: trojan
  country: US
  port: 41759
  password: ixkIc4mCzH
  skip-cert-verify: true
  udp: true
- name: 1.55| US186 TGpeekfun
  server: 209.141.35.147
  port: 48919
  type: trojan
  country: ' US'
  password: 52911320-db53-40ff-917a-e5de797c28e7
  skip-cert-verify: true
  udp: true
- name: 1.55|httpsgitiov9999ip3瑞典35
  server: dg.jgw.tgproxy.wtf
  port: 443
  type: vmess
  uuid: 061a5ca3-09f7-413e-8d4d-35775bb5c0eb
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /theuploadapi
    headers:
      Host: dg.jgw.tgproxy.wtf
- name: 1.54|CYL科技20220213 101
  server: gia.uk.tgproxy.wtf
  port: 443
  type: vmess
  uuid: 061a5ca3-09f7-413e-8d4d-35775bb5c0eb
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /theuploadapi
  ws-headers:
    Host: gia.uk.tgproxy.wtf
  udp: true
- name: 1.53|CYL科技20220213 36
  server: aws.in.tgproxy.wtf
  port: 21888
  type: vmess
  uuid: 061a5ca3-09f7-413e-8d4d-35775bb5c0eb
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /theuploadapi
  ws-headers:
    Host: aws.in.tgproxy.wtf
  udp: true
- name: 1.53|Relay  717Mb
  server: 162.159.204.77
  port: 443
  type: vmess
  uuid: 3646a0c9-69b0-4cf9-c262-890ab5466d35
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /freebaipiao
  ws-headers:
    Host: haxca.aifx.eu.org
- name: 1.52|Pool1817Mb
  server: 107.155.83.152
  type: vmess
  country: US
  port: 443
  uuid: 8f469f1b-1fd3-433b-9fd9-b4e041b9df16
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ray
  servername: govacaxixo.watchdoctor.xyz
  ws-headers:
    HOST: govacaxixo.watchdoctor.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 1.51|Pool 800Mb
  server: 198.148.92.246
  type: vmess
  country: US
  port: 443
  uuid: 4f4c3fc0-888d-414e-9965-a41c627fab53
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ray
  servername: govacaxixo.watchdoctor.xyz
  ws-headers:
    HOST: govacaxixo.watchdoctor.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 1.51|RUJH21397
  server: 92.223.72.42
  port: 443
  type: vmess
  uuid: ae08412f-5bb9-4be7-8560-1984976a1097
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /ray
  ws-headers:
    Host: govacaxixo.watchdoctor.xyz
  udp: true
- name: 1.45|CYL科技20220213 43
  server: tw.main.tgproxy.wtf
  port: 30002
  type: vmess
  uuid: d064d11b-477c-4c5d-a2d8-9fd599ef8e79
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /theuploadapi
  ws-headers:
    Host: tw.main.tgproxy.wtf
  udp: true
- name: 1.44|Pool 1056Mb
  server: 92.223.65.119
  port: 443
  type: vmess
  uuid: 3fd6713f-e036-4ba9-938a-da7843a17a15
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /ray
  ws-headers:
    Host: govacaxixo.watchdoctor.xyz
- name: 1.44| 德国阿伟科技TG油管 3
  server: 37.61.213.94
  port: 443
  type: vmess
  uuid: 97ff78ea-8807-4c33-93e5-d8481ac0539e
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: false
  network: ws
  ws-path: /ray
  ws-headers:
    Host: govacaxixo.watchdoctor.xyz
- name: 1.44|Relay 962Mb
  server: 144.168.228.188
  type: vmess
  country: CA
  port: 443
  uuid: 8809f39b-82de-4c44-a047-74d4890bf1c5
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ray
  servername: govacaxixo.watchdoctor.xyz
  ws-headers:
    HOST: govacaxixo.watchdoctor.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 1.42|Pool2389Mb
  server: 37.120.134.207
  type: vmess
  country: GB
  port: 443
  uuid: 5c0beec7-9b91-4e28-85b0-e3ff49b4ac50
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ray
  servername: govacaxixo.watchdoctor.xyz
  ws-headers:
    HOST: govacaxixo.watchdoctor.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 1.41|RelayUSUS23571879Mb
  server: 198.52.125.218
  type: trojan
  country: US
  port: 55432
  password: bab4574d-dd84-4003-8926-f45512c39aa3
  skip-cert-verify: true
  udp: true
- name: 1.37| githubcomfreefq  美国内华达州拉斯维加斯BuyVM 20
  server: us.lv.buyvm.tgproxy.wtf
  port: 21888
  type: vmess
  uuid: d064d11b-477c-4c5d-a2d8-9fd599ef8e79
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /theuploadapi
  ws-headers:
    Host: us.lv.buyvm.tgproxy.wtf
- name: 1.16|CYL科技20220213 59
  server: niaop.tk
  port: 443
  type: vmess
  uuid: a0b0df87-bda2-440e-830f-347da6cc7760
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /wsssdr1
  ws-headers:
    Host: niaop.tk
  udp: true
