proxies:
- name: SanJose8882950
  server: sanjose.cscecsr.tk
  port: 443
  type: trojan
  password: abc123
  sni: sanjose.cscecsr.tk
  skip-cert-verify: true
  udp: true
- name: 4566157195tcp8
  server: 45.66.157.195
  port: 7596
  type: vmess
  uuid: 4cbb0ce4-1ec3-11ec-b76f-00163c06ad53
  alterId: 0
  cipher: auto
  tls: false
- name: PoolUS19981592
  server: 67.21.72.35
  type: vmess
  country: US
  port: 443
  uuid: 2566d00f-218c-48f7-9a36-13d3d6f1a724
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' 美国 02 Multacom13412963'
  server: 173.82.55.94
  port: 443
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-path: /footers
  ws-headers:
    Host: www.01787634.xyz
- name: ' 美国 03 Multacom13422964'
  server: 173.82.150.26
  port: 443
  type: vmess
  uuid: 1a116d02-5fca-47fa-a2a1-6e8d0f2f71cc
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-path: /path/310910211916
  ws-headers:
    Host: www.75287890.xyz
- name: US185152842
  server: 72.167.33.106
  type: trojan
  country: US
  port: 443
  password: 36ebef7d1b1d6205fd0c55f28800e674
  skip-cert-verify: true
  udp: true
- name: RelayUSUS14512581
  server: 107.167.9.122
  type: vmess
  country: US
  port: 443
  uuid: 2566d00f-218c-48f7-9a36-13d3d6f1a724
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.17080100.xyz
  ws-headers:
    HOST: www.17080100.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US184632790
  server: 96.43.91.58
  type: vmess
  country: US
  port: 443
  uuid: 3bfb43e2-7dfe-4757-86ee-1ce9fb9fd13a
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.45218443.xyz
  ws-headers:
    HOST: www.45218443.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US184552782
  server: 149.248.19.78
  type: vmess
  country: US
  port: 443
  uuid: 79214731-7f0c-4f2d-a894-13b7df293624
  alterId: 60
  cipher: auto
  network: ws
  ws-path: /sadfasdf
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: RelayUSUS19993604
  server: 198.211.30.165
  type: vmess
  country: US
  port: 443
  uuid: 6aaa2f9f-7c91-4b51-aa77-05a83a5d6a4d
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.93289686.xyz
  ws-headers:
    HOST: www.93289686.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- alterId: 64
  cipher: auto
  name: 0928oslook美国USUSASanta Clarita285902919
  network: ws
  port: 443
  server: 173.82.55.93
  tls: true
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  ws-headers:
    Host: www.01787634.xyz
  ws-path: /footers
- name: RelayUSUS14582588
  server: nn-ssr4.feiclouddd.me
  type: vmess
  country: US
  port: 443
  uuid: 79214731-7f0c-4f2d-a894-13b7df293624
  alterId: 60
  cipher: auto
  network: ws
  ws-path: /sadfasdf
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US184602787
  server: 128.14.157.112
  type: vmess
  country: US
  port: 13723
  uuid: a90597c1-bab3-4217-ad6f-0838675c8634
  alterId: 10
  cipher: auto
  network: ws
  ws-path: /ray
  servername: en.tgchannels.org/channel/vpnpool
  ws-headers:
    HOST: en.tgchannels.org/channel/vpnpool
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US184592786
  server: 104.251.233.106
  type: vmess
  country: US
  port: 13723
  uuid: a90597c1-bab3-4217-ad6f-0838675c8638
  alterId: 10
  cipher: auto
  network: ws
  ws-path: /ray
  servername: en.tgchannels.org/channel/vpnpool
  ws-headers:
    HOST: en.tgchannels.org/channel/vpnpool
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: SSRSUBV37付费推荐suoytssrsub9812959
  server: nn-ssr24.feiclouddd.me
  port: 443
  type: vmess
  uuid: 94d3ddba-3c75-4ddd-84c5-b859a30b1fb9
  alterId: 60
  cipher: auto
  tls: true
  network: ws
  ws-path: /dsafasdf
  ws-headers:
    Host: nn-ssr24.feiclouddd.me
- name: 830 1209Mb2632
  server: t1.ssrsub.com
  type: trojan
  port: 8443
  password: 2faeb94c-1be6-4e31-a30c-c0cbf5f4a1d5
  sni: t1.ssrsub.com
  udp: true
- name: US184702797
  server: 198.211.30.163
  type: vmess
  country: US
  port: 443
  uuid: 6aaa2f9f-7c91-4b51-aa77-05a83a5d6a4d
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.93289686.xyz
  ws-headers:
    HOST: www.93289686.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' mattkaydiarycom美国USUSALas Vegas221739'
  server: 209.141.35.45
  port: 80
  type: vmess
  uuid: 732ada90-3ad1-45bd-bd37-fb5fe1b9007c
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-path: /
  ws-headers:
    Host: pull.free.video.10010.com
- name: NodeTest 89  18551 KB7172923
  server: us01.tencentlink.icu
  port: 10000
  type: trojan
  password: 42c2d9d7-d55c-4d6c-ba0a-47bf312b4ab6
  skip-cert-verify: false
  udp: true
  speedtest: 189959
- name: ' US124812774'
  server: 192.74.254.112
  type: vmess
  country: ' US'
  port: 58719
  uuid: ae1048eb-a962-48f6-b15f-013d83d0b6c7
  alterId: 64
  cipher: auto
  network: tcp
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: trojan1250
  type: trojan
  server: 65.49.196.246
  port: 443
  password: 123abc,./
  sni: ztinoz.com
  alpn:
  - h2
  - http/1.1
