proxies:
- name: 5.90| 香港1小浪浪
  server: shonlinecu.proconcn.xyz
  port: 560
  type: ssr
  cipher: chacha20-ietf
  password: mblank1port
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 50374:ff112233
  obfs-param: ''
- name: 5.75|ss
  type: ss
  server: fkgfw-prod.i.sxl.cn
  port: 443
  cipher: aes-256-cfb
  password: E4DNMf73kHPrd8Qq7aqGPf7f
  _index: 0
- name: 4.84|CN中国US美国11
  server: w5.v2mmy.xyz
  port: 44823
  type: ss
  cipher: aes-128-gcm
  password: 96a8a81d-6180-48ae-aef0-0214c1e7e2ac
- name: 4.73|RelayCNDE294
  server: gz2.52168.xyz
  type: ssr
  country: CN
  port: 2106
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
- name: 4.59|Relay1654Mb
  server: w1.v2mmy.xyz
  type: ss
  country: CN
  port: 44811
  password: 96a8a81d-6180-48ae-aef0-0214c1e7e2ac
  cipher: aes-128-gcm
- name: 3.89|Relay1092Mb
  server: w5.v2mmy.xyz
  type: ss
  country: CN
  port: 44821
  password: 96a8a81d-6180-48ae-aef0-0214c1e7e2ac
  cipher: aes-128-gcm
- name: 2.92|上海CN2
  type: ss
  server: cn2.gzhpxb.com
  port: 20166
  cipher: aes-128-gcm
  password: yangchaoyue
  udp: true
  skip-cert-verify: true
- name: 2.84| 香港2小浪浪
  server: shonlinecu.proconcn.xyz
  port: 561
  type: ssr
  cipher: chacha20-ietf
  password: mblank1port
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 50374:ff112233
  obfs-param: ''
- name: 2.36|Relay1968Mb
  server: w3.v2mmy.xyz
  type: ss
  country: CN
  port: 44817
  password: 96a8a81d-6180-48ae-aef0-0214c1e7e2ac
  cipher: aes-128-gcm
- name: 2.35|Relay1379Mb
  server: w2.v2mmy.xyz
  type: ss
  country: CN
  port: 44815
  password: 96a8a81d-6180-48ae-aef0-0214c1e7e2ac
  cipher: aes-128-gcm
- name: 2.30|RelayCNPH2941310Mb
  server: gz1.52168.xyz
  type: ssr
  country: CN
  port: 1101
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
- name: 2.28|CN中国JP日本105
  server: w7.v2mmy.xyz
  port: 44827
  type: ss
  cipher: aes-128-gcm
  password: 96a8a81d-6180-48ae-aef0-0214c1e7e2ac
- name: 2.25|RelayCNJP303 2831Mb
  server: gz2.52168.xyz
  type: ssr
  country: CN
  port: 2107
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
- name: 2.07| 香港4小浪浪
  server: shcris02stand.proconcn.xyz
  port: 562
  type: ssr
  cipher: chacha20-ietf
  password: mblank1port
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 50374:ff112233
  obfs-param: ''
- name: 2.01|Relay1489Mb
  server: w1.v2mmy.xyz
  type: ss
  country: CN
  port: 44812
  password: 96a8a81d-6180-48ae-aef0-0214c1e7e2ac
  cipher: aes-128-gcm
- name: 1.94|RelayCNGB2991178Mb
  server: gz1.52168.xyz
  type: ssr
  country: CN
  port: 1116
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
- name: 1.92|RelayCNDE3041024Mb
  server: gz2.52168.xyz
  type: ssr
  country: CN
  port: 2101
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
- name: 1.88|RelayCNGB2951847Mb
  server: gz1.52168.xyz
  type: ssr
  country: CN
  port: 1117
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
- name: 1.81|Relay 1718Mb
  server: w2.v2mmy.xyz
  type: ss
  country: CN
  port: 44825
  password: 96a8a81d-6180-48ae-aef0-0214c1e7e2ac
  cipher: aes-128-gcm
- name: 1.80| httpsgitiov9999ip1美国30
  server: 38.121.43.182
  port: 8091
  type: ss
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 1.78|Relay1478Mb
  server: w5.v2mmy.xyz
  type: ss
  country: CN
  port: 44820
  password: 96a8a81d-6180-48ae-aef0-0214c1e7e2ac
  cipher: aes-128-gcm
- name: 1.69|RelayCNDE292
  server: gz1.52168.xyz
  type: ssr
  country: CN
  port: 1102
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
- name: 1.65| httpsgitiov9999ip1法国181
  server: 149.202.82.172
  port: 7306
  type: ss
  cipher: aes-256-gcm
  password: FoOiGlkAA9yPEGP
- name: 1.65| httpsgitiov9999ip3加拿大4
  server: 134.195.196.147
  port: 8888
  type: ss
  cipher: aes-256-gcm
  password: Y6R9pAtvxxzmGC
- name: 1.60| 香港3小浪浪
  server: shonlinesandcu03.proconcn.xyz
  port: 561
  type: ssr
  cipher: chacha20-ietf
  password: mblank1port
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 50374:ff112233
  obfs-param: ''
- name: 1.54|Relay 846Mb
  server: 117.28.243.220
  type: ss
  country: CN
  port: 8076
  password: passinfo123
  cipher: rc4-md5
- name: 1.54|CYL科技20220213 16
  server: 117.28.243.220
  port: 8254
  type: ss
  cipher: rc4-md5
  password: passinfo123
  udp: true
- name: 1.51|RelayCNRU297 912Mb
  server: gz1.52168.xyz
  type: ssr
  country: CN
  port: 1109
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
- name: 1.50|RelayCNUS302 380Mb
  server: gz1.52168.xyz
  type: ssr
  country: CN
  port: 1115
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
- name: 1.48| httpsgitiov9999ip1法国172
  server: 149.202.82.172
  port: 2376
  type: ss
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 1.45| httpsgitiov9999ip3加拿大5
  server: 134.195.196.147
  port: 7001
  type: ss
  cipher: aes-256-gcm
  password: RexnBgU7EV5ADxG
- name: 1.43|RelayCNDE289
  server: gz2.52168.xyz
  type: ssr
  country: CN
  port: 2104
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
- name: 1.39| httpsgitiov9999ip3加拿大3
  server: 134.195.196.147
  port: 5000
  type: ss
  cipher: aes-256-gcm
  password: Y6R9pAtvxxzmGC
- name: 1.28| httpsgitiov9999ip1加拿大143
  server: 134.195.196.147
  port: 5600
  type: ss
  cipher: aes-256-gcm
  password: Y6R9pAtvxxzmGC
- name: 1.26|RelayCNRU305 751Mb
  server: gz2.52168.xyz
  type: ssr
  country: CN
  port: 2103
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
- name: 1.26|RelayCNNL3011732Mb
  server: gz2.52168.xyz
  type: ssr
  country: CN
  port: 2109
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
- name: 1.20| httpsgitiov9999ip1加拿大106
  server: 134.195.196.193
  port: 5000
  type: ss
  cipher: aes-256-gcm
  password: Y6R9pAtvxxzmGC
- name: 1.19| httpsgitiov9999ip1加拿大61
  server: 134.195.196.147
  port: 8882
  type: ss
  cipher: aes-256-gcm
  password: kDWvXYZoTBcGkC4
- name: 1.03|RelayCNUS281 527Mb
  server: w2.v2mmy.xyz
  type: ss
  country: CN
  port: 44814
  password: 96a8a81d-6180-48ae-aef0-0214c1e7e2ac
  cipher: aes-128-gcm
- name: 1.02| httpsgitiov9999ip1加拿大59
  server: 134.195.196.147
  port: 4444
  type: ss
  cipher: aes-256-gcm
  password: pKEW8JPByTVTLtM
- name: 0.99| httpsgitiov9999ip5英国52
  server: 172.99.190.149
  port: 5500
  type: ss
  cipher: aes-256-gcm
  password: KixLvKzwjekG00rm
- name: 0.96|Relay2292Mb
  server: w5.v2mmy.xyz
  type: ss
  country: CN
  port: 44822
  password: 96a8a81d-6180-48ae-aef0-0214c1e7e2ac
  cipher: aes-128-gcm
- name: 0.95|RelayCNTW100
  server: gz2.52168.xyz
  type: ssr
  country: CN
  port: 2105
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
- name: 0.94| httpsgitiov9999ip3英国125
  server: 172.99.190.149
  port: 9102
  type: ss
  cipher: aes-256-gcm
  password: e4FCWrgpkji3QY
- name: 0.83|Relay 969Mb
  server: 117.28.243.220
  type: ss
  country: CN
  port: 8186
  password: passinfo123
  cipher: rc4-md5
- name: 0.81| httpsgitiov9999ip3加拿大13
  server: 134.195.196.200
  port: 8882
  type: ss
  cipher: aes-256-gcm
  password: kDWvXYZoTBcGkC4
- name: 0.72|Relay 733Mb
  server: w3.v2mmy.xyz
  type: ss
  country: CN
  port: 44816
  password: 96a8a81d-6180-48ae-aef0-0214c1e7e2ac
  cipher: aes-128-gcm
- name: 0.67|RelayCNJP288  241Mb
  server: w2.v2mmy.xyz
  type: ss
  country: CN
  port: 44813
  password: 96a8a81d-6180-48ae-aef0-0214c1e7e2ac
  cipher: aes-128-gcm
- name: 0.64|Relay 483Mb
  server: 117.28.243.154
  type: ss
  country: CN
  port: 6145
  password: passinfo123
  cipher: rc4-md5
- name: 0.62| CN32 TGpeekfun
  server: 117.28.243.173
  port: 4173
  type: ss
  country: ' CN'
  password: passinfo123
  cipher: rc4-md5
