proxies:
- name: RO8331100
  server: 62.216.92.180
  type: trojan
  country: RO
  port: 443
  password: 36ebef7d1b1d6205fd0c55f28800e674
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: JP746221732029
  server: 139.162.123.246
  type: vmess
  country: JP
  port: 65443
  uuid: 9690fd84-9c5c-4cba-8a53-fb30bb8ae5c9
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /2defe1820b908f6/
  servername: jp4.piyou.cyou
  ws-headers:
    HOST: jp4.piyou.cyou
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' JP47191'
  server: 139.162.123.161
  type: vmess
  country: ' JP'
  port: 65443
  uuid: 42cd918b-36b8-4c00-a58d-0a7fcf0b2df2
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /d39d32d2fd37/
  servername: jp2.piyou.cyou
  ws-headers:
    HOST: jp2.piyou.cyou
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: JP10152280
  server: 203.137.160.157
  type: trojan
  country: JP
  port: 443
  password: 18e513fe-f7f4-353d-84ca-bc9646fb2528mielink
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: SG1132822072037
  server: 188.166.242.117
  type: trojan
  country: SG
  port: 4443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: JP10149277
  server: 210.129.13.101
  type: trojan
  country: JP
  port: 443
  password: 18e513fe-f7f4-353d-84ca-bc9646fb2528mielink
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: ' Game 1 PPhttp1188'
  type: trojan
  server: id1-trojan.bonds.id
  port: 443
  password: 9e266b10-f204-11eb-96b8-1239d0255272
  udp: true
  sni: pmsc.pubgmobile.com
  alpn:
  - h2
  - http/1.1
  skip-cert-verify: true
- name: Ket YT1176
  type: trojan
  server: sg6-trojan.bonds.id
  port: 443
  password: 7a80c340-f911-11eb-a7cb-1239d0255272
  udp: true
  sni: m.youtube.com
  alpn:
  - h2
  - http/1.1
  skip-cert-verify: true
- name: ' Game 3 PPhttp15712010'
  type: trojan
  server: sg2-trojan.bonds.id
  port: 443
  password: 7d450710-f1ad-11eb-a226-1239d0255272
  udp: true
  sni: pmsc.pubgmobile.com
  alpn:
  - h2c
  - http/1.1
  skip-cert-verify: true
- name: US182841841
  server: 96.43.91.59
  type: vmess
  country: US
  port: 443
  uuid: 3bfb43e2-7dfe-4757-86ee-1ce9fb9fd13a
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.45218443.xyz
  ws-headers:
    HOST: www.45218443.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US182801837
  server: 67.21.72.37
  type: vmess
  country: US
  port: 443
  uuid: 2566d00f-218c-48f7-9a36-13d3d6f1a724
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.17080100.xyz
  ws-headers:
    HOST: www.17080100.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' Russia15672009'
  server: russia.cscecsr.tk
  port: 443
  type: trojan
  password: abc123
  sni: russia.cscecsr.tk
  skip-cert-verify: true
  udp: true
- name: US182751832
  server: 107.167.9.122
  type: vmess
  country: US
  port: 443
  uuid: 2566d00f-218c-48f7-9a36-13d3d6f1a724
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.17080100.xyz
  ws-headers:
    HOST: www.17080100.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US1820923192040
  server: 72.167.33.106
  type: trojan
  country: US
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  skip-cert-verify: true
  udp: true
- name: US182691826
  server: nn-ssr24.feiclouddd.me
  type: vmess
  country: US
  port: 443
  uuid: 94d3ddba-3c75-4ddd-84c5-b859a30b1fb9
  alterId: 60
  cipher: auto
  network: ws
  ws-path: /dsafasdf
  servername: nn-ssr24.feiclouddd.me
  ws-headers:
    HOST: nn-ssr24.feiclouddd.me
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' HK欢迎订阅youtube8度科技 101121'
  server: agals04.cloudddns.icu
  port: 992
  type: trojan
  password: f45d308f-d9bc-3954-982f-40883392fb8e
  sni: agals04.cloudddns.icu
  skip-cert-verify: false
- name: 更新地址reurlccW35gV714631974
  server: 67.21.72.43
  type: vmess
  country: US
  port: 443
  uuid: 2566d00f-218c-48f7-9a36-13d3d6f1a724
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.17080100.xyz
  ws-headers:
    HOST: www.17080100.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' mattkaydiarycom美国USUSASanta Clarita233523382042'
  server: 173.82.55.93
  port: 443
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-path: /footers
  ws-headers:
    Host: www.01787634.xyz
- name: NodeTest 96  15015 KB813
  server: agals01.cloudddns.icu
  port: 1123
  type: trojan
  password: f45d308f-d9bc-3954-982f-40883392fb8e
  skip-cert-verify: false
  udp: true
  speedtest: 153750
- name: CA23831750
  server: 138.197.162.114
  type: trojan
  country: CA
  port: 4443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: SSRSUBV14付费推荐suoytssrsub1204
  server: 45.80.186.148
  port: 65443
  type: vmess
  uuid: 7043d711-8795-4940-8e54-1c269c2eba19
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /0069/
  ws-headers:
    Host: us1.piyou.cyou
- name: ' mattkaydiarycom美国USUSASanta Clarita253923412044'
  server: 173.82.55.94
  port: 443
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-path: /footers
  ws-headers:
    Host: www.01787634.xyz
- name: RelayUSUS197397531966
  server: 198.211.30.165
  type: vmess
  country: US
  port: 443
  uuid: 6aaa2f9f-7c91-4b51-aa77-05a83a5d6a4d
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.93289686.xyz
  ws-headers:
    HOST: www.93289686.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: CH4156234
  server: 185.126.116.235
  type: trojan
  country: CH
  port: 443
  password: a3fa58b581353bb375d2ddad0f327938
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: RelayUSUS140021342023
  server: 198.211.30.163
  type: vmess
  country: US
  port: 443
  uuid: 6aaa2f9f-7c91-4b51-aa77-05a83a5d6a4d
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.93289686.xyz
  ws-headers:
    HOST: www.93289686.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: DE5605255
  server: 54.93.236.239
  type: trojan
  country: DE
  port: 443
  password: 18e513fe-f7f4-353d-84ca-bc9646fb2528mielink
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: AU1910226
  server: 3.24.217.191
  type: trojan
  country: AU
  port: 443
  password: 18e513fe-f7f4-353d-84ca-bc9646fb2528mielink
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: GB  651Mb21672028
  server: 138.68.179.78
  type: trojan
  country: GB
  port: 1443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: RelayAUDE34918622013
  server: 1.0.0.0
  type: vmess
  country: AU
  port: 443
  uuid: 3b5e258e-8c5e-45d3-b7d2-02c8f5fc0bb2
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /
  servername: cdnde.irteyz.today
  ws-headers:
    HOST: cdnde.irteyz.today
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: RelayUSUS139621302022
  server: 173.82.150.26
  type: vmess
  country: US
  port: 443
  uuid: 1a116d02-5fca-47fa-a2a1-6e8d0f2f71cc
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.75287890.xyz
  ws-headers:
    HOST: www.75287890.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US182771834
  server: 149.248.19.78
  type: vmess
  country: US
  port: 443
  uuid: 79214731-7f0c-4f2d-a894-13b7df293624
  alterId: 60
  cipher: auto
  network: ws
  ws-path: /sadfasdf
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: NodeTest 30  20645 KB811
  server: us01.tencentlink.icu
  port: 10000
  type: trojan
  password: 42c2d9d7-d55c-4d6c-ba0a-47bf312b4ab6
  skip-cert-verify: false
  udp: true
  speedtest: 211406
- name: JP10161289
  server: 210.152.81.192
  type: trojan
  country: JP
  port: 443
  password: 18e513fe-f7f4-353d-84ca-bc9646fb2528mielink
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: JP76341778
  server: 5.183.177.111
  type: trojan
  country: JP
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  skip-cert-verify: true
  udp: true
- name: SanJose1187
  server: sanjose.cscecsr.tk
  port: 443
  type: trojan
  password: abc123
  sni: sanjose.cscecsr.tk
  skip-cert-verify: true
  udp: true
- name: DE36781758
  server: 5.183.179.138
  type: trojan
  country: DE
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  skip-cert-verify: true
  udp: true
- name: US182591816
  server: 128.14.157.112
  type: vmess
  country: US
  port: 13723
  uuid: a90597c1-bab3-4217-ad6f-0838675c8634
  alterId: 10
  cipher: auto
  network: ws
  ws-path: /ray
  servername: en.tgchannels.org/channel/vpnpool
  ws-headers:
    HOST: en.tgchannels.org/channel/vpnpool
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: GB8132265
  server: 3.9.180.176
  type: trojan
  country: GB
  port: 443
  password: 18e513fe-f7f4-353d-84ca-bc9646fb2528mielink
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: JP10148276
  server: 52.197.88.224
  type: trojan
  country: JP
  port: 443
  password: 18e513fe-f7f4-353d-84ca-bc9646fb2528mielink
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
