proxies:
- name: ' 日本J03iepl6672920'
  server: front.sh.9929.nkeo.top
  port: 45178
  type: vmess
  uuid: 205c9676-57ec-31dd-b28b-21784535e18c
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /jp03
  ws-headers:
    Host: jp03.mypeter.icu
- name: ' H3xHKHKTBGPVC363338562937'
  server: yqy36333.china-cdn-net.com
  port: 36333
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36333.china-cdn-net.com
- name: HK60592708
  server: 13.75.50.22
  type: vmess
  country: HK
  port: 80
  uuid: 3d7a9fb4-0d29-3833-8a6c-32ed80b7f908
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: HK60582707
  server: 52.175.121.142
  type: vmess
  country: HK
  port: 80
  uuid: 3d7a9fb4-0d29-3833-8a6c-32ed80b7f908
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: HK60662715
  server: 207.46.136.212
  type: vmess
  country: HK
  port: 80
  uuid: 3d7a9fb4-0d29-3833-8a6c-32ed80b7f908
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 台湾018242924
  type: vmess
  server: jike-cccn2.ddns-only.xyz
  port: 39205
  uuid: b8da3f41-58ec-3294-891e-cc27ecb1244a
  alterId: 2
  cipher: auto
  udp: true
  network: ws
  ws-path: /jike1
  ws-headers:
    Host: jike1-hinet03.ddns-only.xyz
- name: HK60612710
  server: 23.99.112.143
  type: vmess
  country: HK
  port: 80
  uuid: 3d7a9fb4-0d29-3833-8a6c-32ed80b7f908
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /
  servername: pull.free.video.10010.com
  ws-headers:
    HOST: pull.free.video.10010.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' H3xTW彰化HiNetVC321361620'
  server: yqy32136.china-cdn-net.com
  port: 32136
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32136.china-cdn-net.com
- name: ' H3xTW台北HiNetVC311358572938'
  server: yqy31135.china-cdn-net.com
  port: 31135
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31135.china-cdn-net.com
- name: ' H25xTW彰化HiNetVC322328502934'
  server: yqy32232.china-cdn-net.com
  port: 32232
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32232.china-cdn-net.com
- name: 33公益等级線路嚴格限速1600
  server: yqy2333.china-cdn-net.com
  port: 2333
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /
  ws-headers:
    Host: yqy2333.china-cdn-net.com
- name: ' HTW高雄龍抬頭HiNetVC331358522935'
  server: yqy33135.china-cdn-net.com
  port: 33135
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33135.china-cdn-net.com
- name: ' I6xTW台北HiNetVC311378712946'
  server: yqy31137.china-cdn-net.com
  port: 31137
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31137.china-cdn-net.com
- name: RelayCNHK20 2204Mb2598
  server: ngzyd-1.okex-tradebot.xyz
  type: vmess
  country: CN
  port: 30002
  uuid: d6f3760e-361b-466d-af79-9f953cff1192
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' ITW高雄龍抬頭HiNetVC331328612941'
  server: yqy33132.china-cdn-net.com
  port: 33132
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33132.china-cdn-net.com
- name: RelayHKUS19602366
  server: azure-f4s-hk.transfer-xray.tk
  type: vmess
  country: HK
  port: 23000
  uuid: 2502f647-ab72-4e02-f3a5-d2bf200cab34
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' Lv210x 韩国03IP均衡优化混合负载7102922'
  server: lv2bsdwasdwsa.v22222.xyz
  port: 11111
  type: vmess
  uuid: 7ca31999-3b03-3bc3-9e9e-c83865b4a96c
  alterId: 1
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /tnt-kr3
  ws-headers:
    Host: baidu.com
- name: HK60642713
  server: cw.cwzz.tk
  type: vmess
  country: HK
  port: 18045
  uuid: 3d7a9fb4-0d29-3833-8a6c-32ed80b7f908
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: RelayCNTW3162543
  server: icajm.moox.icu
  type: vmess
  country: CN
  port: 34005
  uuid: bc32f11c-ccf4-4c4b-aa0e-82569b0425b3
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' I6xTW台北HiNetVC311388722947'
  server: yqy31138.china-cdn-net.com
  port: 31138
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31138.china-cdn-net.com
- name: ' H25xTW彰化HiNetVC321328492933'
  server: yqy32132.china-cdn-net.com
  port: 32132
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32132.china-cdn-net.com
- name: 更新地址reurlccW35gV79402956
  server: 3.36.48.102
  type: vmess
  country: US
  port: 8080
  uuid: 52ac1672-ca47-48e4-df3e-513bd1f301b1
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /白嫖节点分享Q群262349039
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' ITW高雄龍抬頭HiNetVC331388672945'
  server: yqy33138.china-cdn-net.com
  port: 33138
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33138.china-cdn-net.com
- name: US184722799
  server: 20.205.231.148
  type: vmess
  country: US
  port: 80
  uuid: 3d7a9fb4-0d29-3833-8a6c-32ed80b7f908
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' I5xTW彰化HiNetVC321318642944'
  server: yqy32131.china-cdn-net.com
  port: 32131
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32131.china-cdn-net.com
- name: ' H3xTW台北HiNetVC311368582939'
  server: yqy31136.china-cdn-net.com
  port: 31136
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31136.china-cdn-net.com
- name: ' 香港 14 Microsoft11942960'
  server: azhk.xiaoyizi.in
  port: 80
  type: vmess
  uuid: 2849b9fb-ffce-47e4-8113-89754073e106
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-path: /sg1
  ws-headers:
    Host: azhk.xiaoyizi.in
- name: ' H3xTW彰化HiNetVC321358592940'
  server: yqy32135.china-cdn-net.com
  port: 32135
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32135.china-cdn-net.com
- name: ' 香港 04  Magic  VIP1  原生IP  1x7022921'
  server: magic.seeu.dasaric.pw
  port: 17014
  type: vmess
  uuid: 7e67383a-2c95-321c-ad43-f47d0dbf97ba
  alterId: 1
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /hls/ccav5phd.m3u8
  ws-headers:
    Host: magic.seeu.dasaric.pw
- name: ' I5xTW台北HiNetVC312338632943'
  server: yqy31233.china-cdn-net.com
  port: 31233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31233.china-cdn-net.com
- name: ' I5xTW台北HiNetVC311318622942'
  server: yqy31131.china-cdn-net.com
  port: 31131
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31131.china-cdn-net.com
- name: ' H25xTW台北HiNetVC312328482932'
  server: yqy31232.china-cdn-net.com
  port: 31232
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31232.china-cdn-net.com
- name: HK60622711
  server: 65.52.170.120
  type: vmess
  country: HK
  port: 80
  uuid: 2849b9fb-ffce-47e4-8113-89754073e106
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /sgdo1
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' H25xTW台北HiNetVC311328472931'
  server: yqy31132.china-cdn-net.com
  port: 31132
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31132.china-cdn-net.com
- name: ' I5xTW彰化HiNetVC322331625'
  server: yqy32233.china-cdn-net.com
  port: 32233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32233.china-cdn-net.com
- name: ' H3xHKHKTBGPVC361338542936'
  server: yqy36133.china-cdn-net.com
  port: 36133
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36133.china-cdn-net.com
- name: 4566157195tcp8
  server: 45.66.157.195
  port: 7596
  type: vmess
  uuid: 4cbb0ce4-1ec3-11ec-b76f-00163c06ad53
  alterId: 0
  cipher: auto
  tls: false
- name: 34捐赠解锁更多协议线路1601
  server: yqy2334.china-cdn-net.com
  port: 2334
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2334.china-cdn-net.com
- name: ' 馃嚚馃嚦CN211413892967'
  server: 139.155.22.227
  port: 49110
  type: vmess
  uuid: f7675b7e-59bf-435c-ac03-dc2482f27e5d
  alterId: 64
  cipher: auto
  tls: false
- name: 37长期套餐覆盖IPLC专线8442930
  server: yqy2337.china-cdn-net.com
  port: 2337
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2337.china-cdn-net.com
- name: 更新地址reurlccW35gV79252953
  server: 51.15.96.243
  type: vmess
  country: NL
  port: 80
  uuid: eecfcedc-ef58-4eae-95fd-bf1b256bc2b7
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /sshstores
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: RelayCNJP3142541
  server: icajm.moox.icu
  type: vmess
  country: CN
  port: 34004
  uuid: bc32f11c-ccf4-4c4b-aa0e-82569b0425b3
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: RelayGBGB8228452
  server: ukml.52jjyun.top
  type: vmess
  country: GB
  port: 88
  uuid: be04b13b-a137-4c33-9ff6-a0289c47aa59
  alterId: 10
  cipher: auto
  network: ws
  ws-path: /jjyun
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' HTW高雄龍抬頭HiNetVC331311605'
  server: yqy33131.china-cdn-net.com
  port: 33131
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33131.china-cdn-net.com
- name: RelayGBGB8227451
  server: ukdll.52jjyun.top
  type: vmess
  country: GB
  port: 80
  uuid: af3b0f75-9507-4c58-9ed0-7cc1bc25f373
  alterId: 10
  cipher: auto
  network: ws
  ws-path: /jjyun
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: NL85162738
  server: 132.226.169.93
  type: vmess
  country: NL
  port: 24353
  uuid: 0453154b-db51-4a66-8f7c-0887878cb9a3
  alterId: 0
  cipher: auto
  network: tcp
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 4513513516tcp9
  server: 45.135.135.16
  port: 22111
  type: vmess
  uuid: 5958e1e6-10af-11ec-9a8f-1aa60786834b
  alterId: 0
  cipher: auto
  tls: false
- name: 更新地址reurlccW35gV79372955
  server: 20.68.125.113
  type: vmess
  country: US
  port: 80
  uuid: 84c005e5-0cbb-4c60-9838-6af7256cc4af
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /sshstores
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' HTW高雄龍抬頭HiNetVC332371606'
  server: yqy33237.china-cdn-net.com
  port: 33237
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33237.china-cdn-net.com
- name: 259214249tcp10
  server: 2.59.214.249
  port: 49043
  type: vmess
  uuid: aaad4b5a-1f4f-11ec-a856-82b57278959a
  alterId: 0
  cipher: auto
  tls: false
