proxies:
- name: 0.52| 广东省广州市腾讯云 9
  server: 106.52.33.67
  port: 40394
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.48| 广东省广州市腾讯云 6
  server: 159.75.50.77
  port: 40065
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.48| 广东省广州市腾讯云 1
  server: 159.75.50.77
  port: 40026
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.47| 广东省广州市腾讯云 11
  server: 106.52.33.67
  port: 40306
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.47| 广东省广州市腾讯云 14
  server: 159.75.50.77
  port: 40099
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.47| 广东省广州市腾讯云 26
  server: 159.75.50.77
  port: 40095
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.47| 广东省广州市腾讯云 34
  server: 159.75.50.77
  port: 40016
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.47| 广东省广州市腾讯云 27
  server: 106.52.33.67
  port: 40368
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.47| 广东省广州市腾讯云 29
  server: 1.14.165.96
  port: 40262
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.47| 广东省广州市腾讯云 3
  server: 106.52.33.67
  port: 40322
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.47| 广东省广州市腾讯云 22
  server: 1.14.165.96
  port: 40259
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.47| 广东省广州市腾讯云 30
  server: 1.14.165.96
  port: 40254
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.47| 广东省广州市腾讯云 31
  server: 159.75.50.77
  port: 40091
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.47| 广东省广州市腾讯云 10
  server: 1.14.165.96
  port: 40247
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.47| 广东省广州市腾讯云 24
  server: 159.75.50.77
  port: 40060
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.47| 广东省广州市腾讯云 37
  server: 106.52.33.67
  port: 40396
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.47| 广东省广州市腾讯云 17
  server: 106.52.33.67
  port: 40371
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.47| 广东省广州市腾讯云 19
  server: 159.75.50.77
  port: 40038
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.47| 广东省广州市腾讯云 28
  server: 1.14.165.96
  port: 40297
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.47| 广东省广州市腾讯云 4
  server: 1.14.165.96
  port: 40252
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.47| 广东省广州市腾讯云 20
  server: 106.52.33.67
  port: 40325
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.47| 广东省广州市腾讯云 7
  server: 106.52.33.67
  port: 40326
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.46| 广东省广州市腾讯云 25
  server: 1.14.165.96
  port: 40207
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.44| 广东省广州市腾讯云 16
  server: 159.75.50.77
  port: 40097
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.44| 广东省广州市腾讯云 5
  server: 106.52.33.67
  port: 40344
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.43| 广东省广州市腾讯云 21
  server: 159.75.50.77
  port: 40051
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.40| 广东省广州市腾讯云 35
  server: 159.75.50.77
  port: 40092
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.37| 广东省广州市腾讯云 2
  server: 106.52.33.67
  port: 40374
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.35| 广东省广州市腾讯云 32
  server: 106.52.33.67
  port: 40378
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.29| 广东省广州市腾讯云 12
  server: 1.14.165.96
  port: 40263
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.27| 广东省广州市腾讯云 23
  server: 159.75.50.77
  port: 40028
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.19| 广东省广州市腾讯云 8
  server: 1.14.165.96
  port: 40281
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.14| 广东省广州市腾讯云 36
  server: 159.75.50.77
  port: 40020
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
- name: 0.13| 广东省广州市腾讯云 18
  server: 1.14.165.96
  port: 40277
  type: ss
  cipher: aes-128-cfb
  password: QazEdcTgb159@$*
