proxies:
- name: RelayRORO7911257292030983363
  server: hk-server-01.selfupay.com
  type: trojan
  country: RO
  port: 443
  password: a3fa58b581353bb375d2ddad0f327938
  skip-cert-verify: true
  udp: true
- name: bngancomHK香港289172530013286
  server: hk-server-02.selfupay.com
  port: 443
  type: trojan
  password: a3fa58b581353bb375d2ddad0f327938
- name: ' H3xTW彰化HiNetRC32125219930403316'
  server: yqy32125.china-cdn-net.com
  port: 32125
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' H25xTW台北HiNetRC31222216730213298'
  server: yqy31222.china-cdn-net.com
  port: 31222
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' I6xHKHKTBGPRC36224221830543329'
  server: yqy36224.china-cdn-net.com
  port: 36224
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' I6xTW台北HiNetRC31127222330583333'
  server: yqy31127.china-cdn-net.com
  port: 31127
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' H25xTW彰化HiNetRC32222217130253302'
  server: yqy32222.china-cdn-net.com
  port: 32222
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' I5xTW彰化HiNetRC32223221030493325'
  server: yqy32223.china-cdn-net.com
  port: 32223
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' I5xTW台北HiNetRC31122220530443320'
  server: yqy31122.china-cdn-net.com
  port: 31122
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' H3xHKHKTBGPRC36223219030323308'
  server: yqy36223.china-cdn-net.com
  port: 36223
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' H3xTW台北HiNetRC31126219630373313'
  server: yqy31126.china-cdn-net.com
  port: 31126
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' I6xHKHKTBGPRC36324221930553330'
  server: yqy36324.china-cdn-net.com
  port: 36324
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' H3xHKHKTBGPRC36123218930313307'
  server: yqy36123.china-cdn-net.com
  port: 36123
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: SG11228114129743263
  server: 188.166.242.117
  type: trojan
  country: SG
  port: 4443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: ' I6xTW台北HiNetRC31128222430593334'
  server: yqy31128.china-cdn-net.com
  port: 31128
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' I5xTW台北HiNetRC31223220630453321'
  server: yqy31223.china-cdn-net.com
  port: 31223
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' H25xTW彰化HiNetRC32121217030243301'
  server: yqy32121.china-cdn-net.com
  port: 32121
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' H3xTW台北HiNetRC31125219530363312'
  server: yqy31125.china-cdn-net.com
  port: 31125
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' I5xTW彰化HiNetRC32122220930483324'
  server: yqy32122.china-cdn-net.com
  port: 32122
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' ITW高雄龍抬頭HiNetRC331282331'
  server: yqy33128.china-cdn-net.com
  port: 33128
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' H25xTW台北HiNetRC31121216630203297'
  server: yqy31121.china-cdn-net.com
  port: 31121
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' H3xTW彰化HiNetRC32126220030413317'
  server: yqy32126.china-cdn-net.com
  port: 32126
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: RelayJPJP7319110029663255
  server: jp-server-02.selfupay.com
  type: trojan
  country: JP
  port: 443
  password: 36ebef7d1b1d6205fd0c55f28800e674
  skip-cert-verify: true
  udp: true
- name: JP6492  636Mb2890
  server: 13.231.43.203
  type: ssr
  country: JP
  port: 8081
  password: 3H2aN5Gnm
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: Conference PPhttp2374
  type: trojan
  server: id1-trojan.bonds.id
  port: 443
  password: 60b0a8c0-03fb-11ec-9a71-1239d0255272
  udp: true
  sni: talkgadget.google.com
  alpn:
  - h2
  - http/1.1
  skip-cert-verify: true
- name: ' H26xUS舊金山DigitalOceanRC3312223218230293306'
  server: SCDN.3312223.BPQZDO.China-nCDN-nRDS.com
  port: 12223
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' Russia225030643339'
  server: russia.cscecsr.tk
  port: 443
  type: trojan
  password: abc123
  sni: russia.cscecsr.tk
  skip-cert-verify: true
  udp: true
- name: ' HTW高雄龍抬頭HiNetRC332272280'
  server: yqy33227.china-cdn-net.com
  port: 33227
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' Game 3 PPhttp2371'
  type: trojan
  server: sg2-trojan.bonds.id
  port: 443
  password: 7d450710-f1ad-11eb-a226-1239d0255272
  udp: true
  sni: pmsc.pubgmobile.com
  alpn:
  - h2
  - http/1.1
  skip-cert-verify: true
- name: RelayCNRU240210123200
  server: dog.gkd.world
  type: ssr
  country: CN
  port: 10686
  password: tFlIIS
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 11752:CbQhlx
  obfs: http_simple
  obfs-param: .www.bing.com
- name: ' 美国011903'
  server: usa-server-01.f7256f.cn
  port: 443
  type: trojan
  password: a3fa58b581353bb375d2ddad0f327938
  sni: usa-server-01.f7256f.cn
  skip-cert-verify: false
- name: SanJose225130653340
  server: sanjose.cscecsr.tk
  port: 443
  type: trojan
  password: abc123
  sni: sanjose.cscecsr.tk
  skip-cert-verify: true
  udp: true
- name: RelayJPRU206423453222
  server: t6.ssrsub.one
  type: trojan
  country: JP
  port: 8443
  password: fe74a1aa-4849-4239-838e-1e7d9f6e975d
  skip-cert-verify: true
  udp: true
- name: ' I6xTW彰化HiNetRC32128222830633338'
  server: yqy32128.china-cdn-net.com
  port: 32128
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: httpsgitiov9999 clash ip3 21152529873276
  server: www.ligonwen.cf
  port: 443
  type: trojan
  password: 7836137d-2db0-4809-9b57-ed14cf2ed4ce
  sni: www.ligonwen.cf
- name: US17906124829853274
  server: 45.33.28.243
  type: trojan
  country: US
  port: 8080
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: DE2997 2143Mb2880
  server: 194.195.124.174
  type: trojan
  country: DE
  port: 4443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: 中国福建厦门ssr120414121543552200230083290
  port: 43552
  obfs: plain
  protocol: origin
  password: GUTGQJ
  server: 120.41.41.215
  cipher: aes-256-cfb
  protocol-param: ''
  obfs-param: ''
  type: ssr
- name: bngancomUS美国124191174630033287
  server: usa-server-02.selfupay.com
  port: 443
  type: trojan
  password: 36ebef7d1b1d6205fd0c55f28800e674
  sni: usa-server-02.selfupay.com
- name: ' ITW高雄龍抬頭HiNetRC331222320'
  server: yqy33122.china-cdn-net.com
  port: 33122
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: ' ITW高雄龍抬頭HiNetRC331272330'
  server: yqy33127.china-cdn-net.com
  port: 33127
  type: ssr
  cipher: aes-256-cfb
  password: http://cc.ax/
  protocol: auth_aes128_md5
  obfs: plain
  protocol-param: 48529:tCIwlf
  obfs-param: data.bilibili.com/8d41348529
- name: US15550  824Mb3014
  server: 18.236.120.96
  type: ssr
  country: US
  port: 8081
  password: YFVrXZgRo
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: RelayJPJP7320110129673256
  server: au-server-01.f7256f.cn
  type: trojan
  country: JP
  port: 443
  password: a3fa58b581353bb375d2ddad0f327938
  skip-cert-verify: true
  udp: true
- name: DE3362103229583248
  server: 139.59.209.152
  type: trojan
  country: DE
  port: 4443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: RelayUSUS17904124629843273
  server: ust-1.opensvr.net
  type: trojan
  country: US
  port: 443
  password: opentunnel.net-hdkshak
  skip-cert-verify: true
  udp: true
- name: RelayUS824  538Mb713
  server: cu.newhost.cc
  type: ssr
  country: CN
  port: 10694
  password: tFlIIS
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 11752:CbQhlx
  obfs: http_simple
  obfs-param: .www.bing.com
- name: RelayUSUS441425123223
  server: t2.ssrsub.one
  type: trojan
  country: US
  port: 8443
  password: fe74a1aa-4849-4239-838e-1e7d9f6e975d
  skip-cert-verify: true
  udp: true
- name: httpsgitiov9999 clash ip3 2150629863275
  server: in1-1.noojat.com
  port: 1443
  type: trojan
  password: 7x42LetRa0
  sni: in1-1.noojat.com
- name: RelayNLNL8205113729733262
  server: ned-server-01.selfupay.com
  type: trojan
  country: NL
  port: 443
  password: a3fa58b581353bb375d2ddad0f327938
  skip-cert-verify: true
  udp: true
- name: 中国福建厦门ssr12041415643552200330093291
  port: 43552
  obfs: plain
  protocol: origin
  password: GUTGQJ
  server: 120.41.41.56
  cipher: aes-256-cfb
  protocol-param: ''
  obfs-param: ''
  type: ssr
