proxies:
- name: PoolUS119872396915939
  server: 23.224.191.13
  type: vmess
  country: US
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.64212792.xyz
  ws-headers:
    HOST: www.64212792.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: RelayHKHK6165976754933
  server: hk2.xh.qjnodeip.xyz
  type: vmess
  country: HK
  port: 433
  uuid: 366d7513-7e22-353b-8ac3-412a16eb80a2
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: JP70041326805236
  server: 45.66.134.219
  type: trojan
  country: JP
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: SG90951641510
  server: 188.166.242.117
  type: trojan
  country: SG
  port: 4443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: RelayCNHK3073816674429
  server: 120.232.214.25
  type: vmess
  country: CN
  port: 122
  uuid: 7bd09130-af71-42cf-b878-fc2e5039db8e
  alterId: 0
  cipher: auto
  ws-path: /
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: Relay USUS98791841712
  server: bigsur.cf
  type: vmess
  country: ' US'
  port: 443
  uuid: 54d48b3e-89f5-11eb-a57d-560003426bdc
  alterId: 12
  cipher: auto
  network: ws
  ws-path: /wyCnX5Dc/
  servername: bigsur.cf
  ws-headers:
    HOST: bigsur.cf
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US120852381913
  server: 158.247.209.122
  type: vmess
  country: US
  port: 443
  uuid: 54d48b3e-89f5-11eb-a57d-560003426bdc
  alterId: 12
  cipher: auto
  network: ws
  ws-path: /wyCnX5Dc/
  servername: bigsur.cf
  ws-headers:
    HOST: bigsur.cf
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US43125373623
  server: 192.74.238.98
  type: vmess
  country: US
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.17379738.xyz
  ws-headers:
    HOST: www.17379738.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: IN64981106785135
  server: 159.89.168.0
  type: trojan
  country: IN
  port: 1443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: US119972496956340
  server: 107.173.157.168
  type: vmess
  country: US
  port: 443
  uuid: 4f6aa0c3-7be1-4eaa-a64c-a23418070422
  alterId: 6
  cipher: auto
  network: ws
  ws-path: /b06fde1/
  servername: www.shunxin.ml
  ws-headers:
    HOST: www.shunxin.ml
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: PoolUS119732256885737
  server: 192.74.238.112
  type: vmess
  country: US
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.17379738.xyz
  ws-headers:
    HOST: www.17379738.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: RO8844159129
  server: 185.105.191.92
  type: trojan
  country: RO
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: DE3858906734731
  server: 194.195.124.174
  type: trojan
  country: DE
  port: 4443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: RelayININ64971096775034
  server: in1-1.noojat.com
  type: trojan
  country: IN
  port: 1443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: DE3857896724630
  server: 5.183.179.138
  type: trojan
  country: DE
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  sni: t.me/vpnhat
  skip-cert-verify: true
  udp: true
- name: RelayNLNL24074533122
  server: 46.182.107.108
  type: vmess
  country: NL
  port: 443
  uuid: a6678d34-6aed-44bf-abc0-ad58de119c18
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.31976118.xyz
  ws-headers:
    HOST: www.31976118.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: RelayAUDE3433193021
  server: 1.0.0.0
  type: vmess
  country: AU
  port: 443
  uuid: 3b5e258e-8c5e-45d3-b7d2-02c8f5fc0bb2
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /
  servername: cdnde.irteyz.today
  ws-headers:
    HOST: cdnde.irteyz.today
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: GB5899956744832
  server: 138.68.179.78
  type: trojan
  country: GB
  port: 1443
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
- name: US120122646966441
  server: 45.33.28.243
  type: trojan
  country: US
  port: 8080
  password: 7x42LetRa0
  skip-cert-verify: true
  udp: true
