proxies:
- name: 3.28| 美国 01
  type: ss
  server: 162.14.8.16
  port: '9100'
  cipher: chacha20-ietf
  password: AmyTelecom_11451419I981O
  udp: true
  plugin: obfs
  plugin-opts:
    mode: http
    host: 34021-R5Kk8y5xu8.download.microsoft.com
- name: 3.26| 美国 08
  type: ss
  server: 162.14.15.168
  port: '9135'
  cipher: chacha20-ietf
  password: AmyTelecom_11451419I981O
  udp: true
  plugin: obfs
  plugin-opts:
    mode: http
    host: 34021-R5Kk8y5xu8.download.microsoft.com
- name: 3.25| 美国 02
  type: ss
  server: 162.14.8.16
  port: '9105'
  cipher: chacha20-ietf
  password: AmyTelecom_11451419I981O
  udp: true
  plugin: obfs
  plugin-opts:
    mode: http
    host: 34021-R5Kk8y5xu8.download.microsoft.com
- name: 3.23| 美国 05
  type: ss
  server: 162.14.8.16
  port: '9120'
  cipher: chacha20-ietf
  password: AmyTelecom_11451419I981O
  udp: true
  plugin: obfs
  plugin-opts:
    mode: http
    host: 34021-R5Kk8y5xu8.download.microsoft.com
- name: 3.19| 美国 12
  type: ss
  server: 162.14.8.16
  port: '9155'
  cipher: chacha20-ietf
  password: AmyTelecom_11451419I981O
  udp: true
  plugin: obfs
  plugin-opts:
    mode: http
    host: 34021-R5Kk8y5xu8.download.microsoft.com
- name: 3.17| 美国 04
  type: ss
  server: 162.14.8.16
  port: '9115'
  cipher: chacha20-ietf
  password: AmyTelecom_11451419I981O
  udp: true
  plugin: obfs
  plugin-opts:
    mode: http
    host: 34021-R5Kk8y5xu8.download.microsoft.com
- name: 2.80| 美国 06
  type: ss
  server: 162.14.15.168
  port: '9125'
  cipher: chacha20-ietf
  password: AmyTelecom_11451419I981O
  udp: true
  plugin: obfs
  plugin-opts:
    mode: http
    host: 34021-R5Kk8y5xu8.download.microsoft.com
- name: 2.77| 美国 07
  type: ss
  server: 162.14.15.168
  port: '9130'
  cipher: chacha20-ietf
  password: AmyTelecom_11451419I981O
  udp: true
  plugin: obfs
  plugin-opts:
    mode: http
    host: 34021-R5Kk8y5xu8.download.microsoft.com
- name: 2.42| 美国 10
  type: ss
  server: 162.14.15.168
  port: '9145'
  cipher: chacha20-ietf
  password: AmyTelecom_11451419I981O
  udp: true
  plugin: obfs
  plugin-opts:
    mode: http
    host: 34021-R5Kk8y5xu8.download.microsoft.com
- name: 2.37| 美国 03
  type: ss
  server: 162.14.8.16
  port: '9110'
  cipher: chacha20-ietf
  password: AmyTelecom_11451419I981O
  udp: true
  plugin: obfs
  plugin-opts:
    mode: http
    host: 34021-R5Kk8y5xu8.download.microsoft.com
- name: 2.29| 美国 11
  type: ss
  server: 162.14.15.168
  port: '9150'
  cipher: chacha20-ietf
  password: AmyTelecom_11451419I981O
  udp: true
  plugin: obfs
  plugin-opts:
    mode: http
    host: 34021-R5Kk8y5xu8.download.microsoft.com
- name: 2.27| 美国 13
  type: ss
  server: 162.14.8.16
  port: '9160'
  cipher: chacha20-ietf
  password: AmyTelecom_11451419I981O
  udp: true
  plugin: obfs
  plugin-opts:
    mode: http
    host: 34021-R5Kk8y5xu8.download.microsoft.com
- name: 2.23| 美国 09
  type: ss
  server: 162.14.15.168
  port: '9140'
  cipher: chacha20-ietf
  password: AmyTelecom_11451419I981O
  udp: true
  plugin: obfs
  plugin-opts:
    mode: http
    host: 34021-R5Kk8y5xu8.download.microsoft.com
- name: 2.19| US20191
  server: 79.110.54.133
  port: 38742
  type: ss
  cipher: aes-256-gcm
  password: DKXfWwc4ebscpXTKpbt85rSH
- name: 1.98| 美国 3
  server: 84.17.41.83
  port: 43893
  type: ss
  cipher: aes-256-gcm
  password: YyCBeDdYX4cadHpCkkmdJLq8
- name: 1.94| US20192
  server: 79.110.54.133
  port: 49126
  type: ss
  cipher: aes-256-gcm
  password: wrCaGtrUbzeRqQLdc8Kmk3Nd
- port: 7306
  password: FoOiGlkAA9yPEGP
  type: ss
  cipher: aes-256-gcm
  server: 167.88.63.74
  name: 1.92|美国佐治亚亚特兰大ss1678863747306
- name: 1.90| 美国洛杉矶欢迎订阅youtube8度科 40
  server: 167.88.63.50
  port: 2375
  type: ss
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 1.85| 美国洛杉矶欢迎订阅youtube8度科 3
  server: 167.88.63.107
  port: 7307
  type: ss
  cipher: aes-256-gcm
  password: FoOiGlkAA9yPEGP
- name: 1.82|1.84|trojan
  type: trojan
  server: 65.49.196.246
  port: 443
  password: 123abc,./
  sni: ztinoz.com
  alpn:
  - h2
  - http/1.1
- name: 1.80| 美国洛杉矶欢迎订阅youtube8度科 38
  server: 167.88.63.61
  port: 8090
  type: ss
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 1.76|1.83|US16346
  server: 72.167.45.6
  type: trojan
  country: US
  port: 443
  password: a3fa58b581353bb375d2ddad0f327938
  skip-cert-verify: true
  udp: true
- port: 33148
  password: CMduaFXddcQbwNAAs7xFDnc8
  type: ss
  cipher: aes-256-gcm
  server: 79.110.54.133
  name: 1.76|美国加利福尼亚0ss791105413333148
- name: 1.76| US20188
  server: 79.110.54.133
  port: 34815
  type: ss
  cipher: aes-256-gcm
  password: LkFAzkzXkSCRYa2CsRdL8cGb
- name: 1.73| US20211
  server: 79.110.54.133
  port: 33998
  type: ss
  cipher: aes-256-gcm
  password: NHwQTPLCfaTMSqTnU3mjcSxe
- name: 1.73|US NodeTest 100  17124 KB
  server: 199.10.64.243
  port: 33992
  type: ss
  cipher: aes-256-gcm
  password: 8n6pwAcrrv2pj6tFY2p3TbQ6
  udp: true
  speedtest: 175347
- name: 1.71| 美国洛杉矶欢迎订阅youtube8度科 4
  server: 167.88.63.60
  port: 8090
  type: ss
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 1.71| 美国洛杉矶欢迎订阅youtube8度科 39
  server: 167.88.63.28
  port: 8090
  type: ss
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 1.70|1.43|  292Mb
  server: 72.167.33.106
  type: trojan
  country: US
  port: 443
  password: 28d98f761aca9d636f44db62544628eb
  skip-cert-verify: true
  udp: true
- port: 8090
  password: PCnnH6SQSnfoS27
  type: ss
  cipher: aes-256-gcm
  server: 167.88.63.89
  name: 1.69|美国佐治亚亚特兰大ss1678863898090
- name: 1.68|githubcomfreefq  瑞典  60
  server: 167.88.63.107
  port: 2375
  type: ss
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 1.67| 美国洛杉矶欢迎订阅youtube8度科 35
  server: 167.88.63.107
  port: 8090
  type: ss
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 1.65| 美国洛杉矶欢迎订阅youtube8度科 29
  server: 167.88.63.74
  port: 2375
  type: ss
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 1.65| US20230
  server: 79.110.54.133
  port: 46642
  type: ss
  cipher: aes-256-gcm
  password: gYL83DQWXuDbxmZAVVtUTXaK
- name: 1.64| githubcomfreefq  美国华盛顿Cogent通信公司 24
  server: 38.107.226.149
  port: 2376
  type: ss
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 1.62|US  Las Vegas 1
  server: 79.110.54.133
  port: 31369
  type: ss
  cipher: aes-256-gcm
  password: nCjhBSdrUqQxra8kyKzjTjm8
  udp: true
- name: 1.60|githubcomfreefq  瑞典  51
  server: 167.88.63.99
  port: 2376
  type: ss
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 1.60|githubcomfreefq  瑞典  29
  server: 167.88.63.28
  port: 7307
  type: ss
  cipher: aes-256-gcm
  password: FoOiGlkAA9yPEGP
- port: 45329
  password: CXSjgD7u7Ar7GxkZ4CgTMUsj
  type: ss
  cipher: aes-256-gcm
  server: 79.110.54.133
  name: 1.59|美国加利福尼亚0ss791105413345329
- name: 1.58| githubcomfreefq  美国华盛顿Cogent通信公司 52
  server: 38.107.226.146
  port: 8090
  type: ss
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 1.56|8417358343893
  server: 84.17.35.83
  port: 43893
  type: ss
  cipher: aes-256-gcm
  password: YyCBeDdYX4cadHpCkkmdJLq8
- port: 48938
  password: 4ejJ8n5ddLuYDUHGXJre2ufJ
  type: ss
  cipher: aes-256-gcm
  server: 66.115.177.143
  name: 1.55|美国佐治亚亚特兰大ss6611517714348938
- name: 1.55| 美国洛杉矶欢迎订阅youtube8度科 34
  server: 38.107.226.149
  port: 8090
  type: ss
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 1.53| 美国洛杉矶欢迎订阅youtube8度科 8
  server: 167.88.63.108
  port: 8090
  type: ss
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 1.49|githubcomfreefq  瑞典  38
  server: 167.88.63.108
  port: 8091
  type: ss
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- port: 38742
  password: DKXfWwc4ebscpXTKpbt85rSH
  type: ss
  cipher: aes-256-gcm
  server: 64.44.42.60
  name: 1.47|美国伊利诺伊芝加哥ss6444426038742
- name: 1.47| 美国洛杉矶欢迎订阅youtube8度科技
  server: 38.107.226.149
  port: 2375
  type: ss
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 1.47| 美国洛杉矶欢迎订阅youtube8度科 6
  server: 167.88.63.74
  port: 7307
  type: ss
  cipher: aes-256-gcm
  password: FoOiGlkAA9yPEGP
- name: 1.45|美国04
  server: 64.44.42.60
  port: 31944
  type: ss
  cipher: aes-256-gcm
  password: aYNeKDMzYQYw4KbUbJA8Wszq
- name: 1.44|US NodeTest 42  21927 KB
  server: 64.44.42.60
  port: 45329
  type: ss
  cipher: aes-256-gcm
  password: CXSjgD7u7Ar7GxkZ4CgTMUsj
  udp: true
  speedtest: 224534
