proxies:
- name: 3.30|Relay1105Mb
  server: shonlinecu.proconcn.xyz
  type: ssr
  country: CN
  port: 560
  password: mblank1port
  cipher: chacha20-ietf
  protocol: auth_aes128_md5
  protocol-param: 50374:ff112233
  obfs: plain
- name: 1.70| 美国 15
  server: 42.157.195.233
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.68| 美国 19
  server: 42.157.195.232
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.66| 美国 11
  server: 42.157.195.230
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.64| 日本 16
  server: 42.157.195.244
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.64| 日本 4
  server: 14.152.92.77
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.64| 日本 5
  server: 42.157.195.245
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.64| 日本 6
  server: 14.152.92.78
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.62| 日本 8
  server: 14.152.92.75
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.62| 日本 3
  server: 42.157.195.243
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.57| 日本 1
  server: 14.152.92.80
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.57|Relay 380Mb
  server: gz1.52168.xyz
  type: ssr
  country: CN
  port: 1115
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
- name: 1.50| 美国 14
  server: 42.157.195.240
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.50| 美国 18
  server: 42.157.195.242
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.50| 美国 16
  server: 14.152.92.70
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.50| 美国 20
  server: 14.152.92.74
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.50| 美国 22
  server: 14.152.92.71
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.49| 美国 13
  server: 42.157.195.238
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.43| 日本 7
  server: 14.152.92.79
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.40| 美国 17
  server: 42.157.195.231
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.34| 美国 12
  server: 42.157.195.229
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.32| 美国 24
  server: 42.157.195.239
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.15| 美国 21
  server: 42.157.195.234
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 1.14|Relay 1638Mb
  server: gz2.52168.xyz
  type: ssr
  country: CN
  port: 2109
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
- name: 1.07| 新加坡 1
  server: 14.152.92.81
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 0.89| 美国 32
  server: 42.157.195.241
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 0.84| 美国 23
  server: 14.152.92.73
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 0.64|Relay1271Mb
  server: gz1.52168.xyz
  type: ssr
  country: CN
  port: 1111
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
- name: 0.60|Relay 840Mb
  server: shonlinecu.proconcn.xyz
  type: ssr
  country: CN
  port: 561
  password: mblank1port
  cipher: chacha20-ietf
  protocol: auth_aes128_md5
  protocol-param: 50374:ff112233
  obfs: plain
- name: 0.58| 日本 2
  server: 14.152.92.76
  port: 12127
  type: ssr
  cipher: aes-256-cfb
  password: 68xdgu9eyif
  protocol: auth_aes128_sha1
  obfs: http_simple
  protocol-param: 600777:154T8b
  obfs-param: 0f099600777.v23f7nM0
  udp: true
- name: 0.56|Relay 979Mb
  server: shonlinesandcu03.proconcn.xyz
  type: ssr
  country: CN
  port: 561
  password: mblank1port
  cipher: chacha20-ietf
  protocol: auth_aes128_md5
  protocol-param: 50374:ff112233
  obfs: plain
- name: 0.45|Relay1046Mb
  server: gz1.52168.xyz
  type: ssr
  country: CN
  port: 1117
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
- name: 0.41|Relay1248Mb
  server: gz2.52168.xyz
  type: ssr
  country: CN
  port: 2102
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
