proxies:
- alterId: 64
  cipher: auto
  country: NL
  h2-opts: {}
  http-opts: {}
  name: RelayNLNL1194
  network: ws
  port: 443
  server: 46.182.107.93
  servername: www.54872833.xyz
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 743bdc87-1dea-41bf-aa0b-51dfbbfec8aa
  ws-headers:
    HOST: www.54872833.xyz
  ws-path: /footers
- alterId: 64
  cipher: auto
  country: US
  h2-opts: {}
  http-opts: {}
  name: PoolUS2683344
  network: ws
  port: 443
  server: 23.224.101.101
  servername: www.76126449.xyz
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 946ba5df-5771-4873-a3cb-892378526147
  ws-headers:
    HOST: www.76126449.xyz
  ws-path: /footers
- alterId: 0
  cipher: auto
  country: ZZ
  h2-opts: {}
  http-opts: {}
  name: RelayZZUS2924045
  network: ws
  port: 443
  server: 162.159.211.73
  servername: shrill-lake-68c5.ihabney7.workers.dev
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 790d2324-0a2c-4d2d-b35c-985c387dbd09
  ws-headers:
    HOST: shrill-lake-68c5.ihabney7.workers.dev
  ws-path: /790d2324-0a2c-4d2d-b35c-985c387dbd09-vmess
- alterId: 0
  cipher: auto
  country: ZZ
  h2-opts: {}
  http-opts: {}
  name: RelayZZUS2934146
  network: ws
  port: 443
  server: 162.159.209.84
  servername: shrill-lake-68c5.ihabney7.workers.dev
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 790d2324-0a2c-4d2d-b35c-985c387dbd09
  ws-headers:
    HOST: shrill-lake-68c5.ihabney7.workers.dev
  ws-path: /790d2324-0a2c-4d2d-b35c-985c387dbd09-vmess
- alterId: 4
  cipher: auto
  country: US
  h2-opts: {}
  http-opts: {}
  name: RelayUSUS25324564748
  network: ws
  port: 443
  server: v3.coding996.com
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 02929ff2-2de0-4be9-940b-fc3bf7ea3a72
  ws-path: /baidu
- alterId: 4
  cipher: auto
  country: US
  h2-opts: {}
  http-opts: {}
  name: RelayUSUS25425574849
  network: ws
  port: 443
  server: v2.coding996.com
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: d0b0220b-0704-452a-b7f8-46f158091493
  ws-path: /baidu
- alterId: 4
  cipher: auto
  country: US
  h2-opts: {}
  http-opts: {}
  name: RelayUSUS25526584950
  network: ws
  port: 443
  server: v1.coding996.com
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: da46b8ad-7837-4ff6-ad10-0e9c3a0d630d
  ws-path: /baidu
- alterId: 4
  cipher: auto
  country: US
  h2-opts: {}
  http-opts: {}
  name: RelayUSUS26536615151
  network: ws
  port: 443
  server: v6.coding996.com
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 1e7aca54-979a-40b0-9d1c-d7ef65a3d665
  ws-path: /wechat
- alterId: 4
  cipher: auto
  country: US
  h2-opts: {}
  http-opts: {}
  name: RelayUSUS27243635252
  network: ws
  port: 443
  server: v7.coding996.com
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 3095ccd7-cb4d-4229-98d3-fde96aa37906
  ws-path: /baidu
- alterId: 8
  cipher: auto
  country: US
  h2-opts: {}
  http-opts: {}
  name: RelayUSUS2763751665453
  network: tcp
  port: 19970
  server: c1s3.jamjams.net
  skip-cert-verify: true
  type: vmess
  uuid: 6213d0c0-432f-445c-8a47-f58b9152b212
  ws-path: /
- alterId: 64
  cipher: auto
  country: US
  h2-opts: {}
  http-opts: {}
  name: RelayUSUS2773852675554
  network: ws
  port: 443
  server: 23.224.30.36
  servername: www.01902367.xyz
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: e4494518-74e8-4d6b-942a-6b332cce09ef
  ws-headers:
    HOST: www.01902367.xyz
  ws-path: /path/310910211916
- alterId: 6
  cipher: auto
  country: US
  h2-opts: {}
  http-opts: {}
  name: RelayUSUS2804153685655
  network: ws
  port: 443
  server: www.shunxin.ml
  servername: www.shunxin.ml
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 4f6aa0c3-7be1-4eaa-a64c-a23418070422
  ws-headers:
    HOST: www.shunxin.ml
  ws-path: /b06fde1/
