proxies:
- name: CN3065572216
  server: nna.boom.party
  type: ssr
  country: CN
  port: 49000
  password: Uk92CS
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 254637:Ol4zZv
  obfs: http_simple
  obfs-param: download.windowsupdate.com
- name: RelayCNSG305866661382432
  server: n30.boom.party
  type: ssr
  country: CN
  port: 19000
  password: Uk92CS
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 254637:Ol4zZv
  obfs: http_simple
  obfs-param: download.windowsupdate.com
- name: RelayCNHK3063551115
  server: n93.boom.party
  type: ssr
  country: CN
  port: 28000
  password: Uk92CS
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 254637:Ol4zZv
  obfs: http_simple
  obfs-param: download.windowsupdate.com
- name: RelayCNSG305967662392533
  server: nl4.boom.party
  type: ssr
  country: CN
  port: 25000
  password: Uk92CS
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 254637:Ol4zZv
  obfs: http_simple
  obfs-param: download.windowsupdate.com
- name: RelayCNUS306573665422735
  server: us1.edge.boom.party
  type: ssr
  country: CN
  port: 40000
  password: Uk92CS
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 254637:Ol4zZv
  obfs: http_simple
  obfs-param: download.windowsupdate.com
