proxies:
- name: RelayAUAU1694991294832402938
  server: blog.chaoge.cool
  type: vmess
  country: AU
  port: 29543
  uuid: 8d9184d2-ec19-47d3-81a1-a3f43cf40bd9
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /
  servername: pull.free.video.10010.com
  ws-headers:
    HOST: pull.free.video.10010.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: bngancomHK香港320153529502933310533703031
  server: 18.167.94.242
  port: 80
  type: vmess
  uuid: cec85927-8a7a-4866-df8c-27ed589de0ce
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-path: /TS/recharge/tzUrl.html
- name: RelayUSHK105333072921309933643028
  server: gyc.cloudddns.icu
  type: vmess
  country: US
  port: 123
  uuid: d32d8723-5983-3ecc-8e9f-8b57bab1a584
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /public
  servername: gyc.cloudddns.icu
  ws-headers:
    HOST: gyc.cloudddns.icu
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' vip3v2rayIplc专线 深圳香港 ⑥ DMITNETFLIXHULUHBO1697'
  server: 8.ssrj.xyz
  port: 65108
  type: vmess
  uuid: 24ea3f63-d495-3a0a-a7de-f92a4e6fb9ae
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
- name: RelayHKJP5839976
  server: 3.ssrj.xyz
  type: vmess
  country: HK
  port: 65103
  uuid: 24ea3f63-d495-3a0a-a7de-f92a4e6fb9ae
  alterId: 2
  cipher: auto
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 台湾01203532142918
  type: vmess
  server: jike-cccn2.ddns-only.xyz
  port: 39205
  uuid: b8da3f41-58ec-3294-891e-cc27ecb1244a
  alterId: 2
  cipher: auto
  udp: true
  network: ws
  ws-path: /jike1
  ws-headers:
    Host: jike1-hinet03.ddns-only.xyz
- name: ' H3xTW台北HiNetVC311362198303933152993'
  server: yqy31136.china-cdn-net.com
  port: 31136
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31136.china-cdn-net.com
- name: ' H3xHKHKTBGPVC362332193303433102988'
  server: yqy36233.china-cdn-net.com
  port: 36233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36233.china-cdn-net.com
- name: ' HTW高雄龍抬頭HiNetVC332372042'
  server: yqy33237.china-cdn-net.com
  port: 33237
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33237.china-cdn-net.com
- name: ' JP64709'
  server: 139.162.123.161
  type: vmess
  country: ' JP'
  port: 65443
  uuid: 42cd918b-36b8-4c00-a58d-0a7fcf0b2df2
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /d39d32d2fd37/
  servername: jp2.piyou.cyou
  ws-headers:
    HOST: jp2.piyou.cyou
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' HTW高雄龍抬頭HiNetVC331362065'
  server: yqy33136.china-cdn-net.com
  port: 33136
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33136.china-cdn-net.com
- name: ' H25xTW彰化HiNetVC322322173302733042983'
  server: yqy32232.china-cdn-net.com
  port: 32232
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32232.china-cdn-net.com
- name: JP65352602
  server: 172.105.223.13
  type: vmess
  country: JP
  port: 443
  uuid: 88116C24-1050-D5BD-5F30-411F32B6042A
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ray
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' I6xTW台北HiNetVC311382226306133363013'
  server: yqy31138.china-cdn-net.com
  port: 31138
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31138.china-cdn-net.com
- name: ' H3xHKHKTBGPVC363332194303533112989'
  server: yqy36333.china-cdn-net.com
  port: 36333
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36333.china-cdn-net.com
- name: RelayCNJP2625946
  server: gzyd.anoob.top
  type: vmess
  country: CN
  port: 49456
  uuid: db4b8c73-b23e-3c6f-a28c-2228320bba4c
  alterId: 2
  cipher: auto
  network: tcp
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: RelayCNHK3069200
  server: 120.232.214.25
  type: vmess
  country: CN
  port: 9444
  uuid: 47976098-16bd-4647-8c81-5b0bb812388a
  alterId: 0
  cipher: auto
  ws-path: /
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' H25xTW台北HiNetVC312322169302333002979'
  server: yqy31232.china-cdn-net.com
  port: 31232
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31232.china-cdn-net.com
- name: ' 中国台湾15 14Mbps 631ms 奈飞自制剧19172873'
  server: 35.201.218.125
  port: 28879
  type: vmess
  uuid: 8f55c99d-d400-47d5-a949-638204907e0b
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: false
- name: ' H3xHKHKTBGPVC361332192303333092987'
  server: yqy36133.china-cdn-net.com
  port: 36133
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36133.china-cdn-net.com
- name: ' 日本电信混淆1710'
  server: cm.syhwdz.top
  port: 40606
  type: vmess
  uuid: 5970926b-4765-3045-ab0f-099206e62032
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /cdnxy
  ws-headers:
    Host: a.189.cn
- name: ' I5xTW台北HiNetVC312332208304733233001'
  server: yqy31233.china-cdn-net.com
  port: 31233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31233.china-cdn-net.com
- name: ' H3xTW台北HiNetVC311352197303833142992'
  server: yqy31135.china-cdn-net.com
  port: 31135
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31135.china-cdn-net.com
- name: ' I6xTW台北HiNetVC311372225306033353012'
  server: yqy31137.china-cdn-net.com
  port: 31137
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31137.china-cdn-net.com
- name: ' 新加坡小白61029592938310933743033'
  server: cm.syhwdz.top
  port: 40858
  type: vmess
  uuid: 7cb95511-67e5-35a0-a093-96fde16be539
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /cdnxxy
  ws-headers:
    Host: music.163.com
- name: RelayJPJP75101037
  server: jp02cf.v2cdn.org
  type: vmess
  country: JP
  port: 443
  uuid: 25FB7976-F0F7-FC38-1389-472ABE331D57
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ray
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 37长期套餐覆盖IPLC专线83829832959312933913049
  server: yqy2337.china-cdn-net.com
  port: 2337
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2337.china-cdn-net.com
- name: ' H25xTW台北HiNetVC311322168302232992978'
  server: yqy31132.china-cdn-net.com
  port: 31132
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31132.china-cdn-net.com
- name: CN30242162824
  server: 120.232.214.25
  type: vmess
  country: CN
  port: 115
  uuid: 906fe42d-51a1-4f05-bc55-d4301fece17e
  alterId: 0
  cipher: auto
  network: tcp
  ws-path: /
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' HTW高雄龍抬頭HiNetVC3313122812885'
  server: yqy33131.china-cdn-net.com
  port: 33131
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33131.china-cdn-net.com
- name: ' I5xTW彰化HiNetVC322332212305133273005'
  server: yqy32233.china-cdn-net.com
  port: 32233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32233.china-cdn-net.com
- name: ' 印度1 107Mbps 729ms 奈飞自制剧63129712950312133843043'
  server: gzcm.sspro.nl
  port: 10799
  type: vmess
  uuid: fd252902-aac0-36be-8420-a3b23fe803af
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /ssrgr-in02
  ws-headers:
    Host: none
- name: ' I5xTW台北HiNetVC311312207304633223000'
  server: yqy31131.china-cdn-net.com
  port: 31131
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31131.china-cdn-net.com
- name: US156742687
  server: bigsur.cf
  type: vmess
  country: US
  port: 443
  uuid: 54d48b3e-89f5-11eb-a57d-560003426bdc
  alterId: 12
  cipher: auto
  network: ws
  ws-path: /wyCnX5Dc/
  servername: bigsur.cf
  ws-headers:
    HOST: bigsur.cf
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' 台湾  21744'
  server: cn1.relay.starlink.st
  port: 65013
  type: vmess
  uuid: 8ee1ee4e-b65a-4238-ac88-d1429c018e58
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: false
- name: ' I6xHKHKTBGPVC362342221305733323009'
  server: yqy36234.china-cdn-net.com
  port: 36234
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36234.china-cdn-net.com
- name: 34捐赠解锁更多协议线路83529802957312733893047
  server: yqy2334.china-cdn-net.com
  port: 2334
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2334.china-cdn-net.com
- name: 33公益等级線路嚴格限速83429792956312633883046
  server: yqy2333.china-cdn-net.com
  port: 2333
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /
  ws-headers:
    Host: yqy2333.china-cdn-net.com
- name: CN255016531972911
  server: 139.155.22.227
  type: vmess
  country: CN
  port: 49110
  uuid: f7675b7e-59bf-435c-ac03-dc2482f27e5d
  alterId: 64
  cipher: auto
  network: tcp
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: JP65412608
  server: 140.227.124.168
  type: vmess
  country: JP
  port: 443
  uuid: D32D45E3-9AC9-3145-BD45-73ACC20DB1CF
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /ray
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: RelayCNUS2648954
  server: 120.232.214.25
  type: vmess
  country: CN
  port: 113
  uuid: 906fe42d-51a1-4f05-bc55-d4301fece17e
  alterId: 0
  cipher: auto
  network: tcp
  ws-path: /
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 36中继中转隧道线路覆盖83729822958312833903048
  server: yqy2336.china-cdn-net.com
  port: 2336
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2336.china-cdn-net.com
- name: JP65312598
  server: jp1.mfv2ray.top
  type: vmess
  country: JP
  port: 443
  uuid: 461a1bf9-0c11-30cf-93fa-0a8de2ad0f33
  alterId: 5
  cipher: auto
  network: ws
  ws-path: /logs
  servername: jp1.mfv2ray.top
  ws-headers:
    HOST: jp1.mfv2ray.top
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US156042801309033563025
  server: 23.224.191.13
  type: vmess
  country: US
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.64212792.xyz
  ws-headers:
    HOST: www.64212792.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' 美国圣河塞Twitter61129602939311033753034'
  server: cm.syhwdz.top
  port: 41511
  type: vmess
  uuid: 7cb95511-67e5-35a0-a093-96fde16be539
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /cdnxys
  ws-headers:
    Host: music.163.com
- name: US156882701
  server: 107.167.9.122
  type: vmess
  country: US
  port: 443
  uuid: 2566d00f-218c-48f7-9a36-13d3d6f1a724
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  servername: www.17080100.xyz
  ws-headers:
    HOST: www.17080100.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: US1814112442852
  server: 199.193.126.73
  type: vmess
  country: US
  port: 26917
  uuid: 3bc30c04-4854-47bc-80b5-4fbb2364006e
  alterId: 8
  cipher: auto
  network: tcp
  ws-path: t.me/vpnpool
  servername: t.me/vpnhat
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: US156702683
  server: 199.193.126.11
  type: vmess
  country: US
  port: 10606
  uuid: c474da00-e28b-40b0-8356-8f62e5eb71e2
  alterId: 8
  cipher: auto
  network: tcp
  ws-path: t.me/vpnpool
  servername: t.me/vpnhat
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: US15582281232262926
  server: 23.225.153.26
  type: vmess
  country: US
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.91852313.xyz
  ws-headers:
    HOST: www.91852313.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: PoolUS183871126
  server: 192.74.238.99
  type: vmess
  country: US
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /path/310910211916
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
