proxies:
- name: 5.81| 新加坡02 2
  server: azhk.zz123.xyz
  port: 35724
  type: vmess
  uuid: 4aa916ea-c6b9-3e4c-ba36-7c7c2cbcd903
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /zz
  ws-headers:
    Host: azhk.zz123.xyz
  udp: true
- name: 5.15| 新加坡01 2
  server: azhk.zz123.xyz
  port: 38141
  type: vmess
  uuid: 4a4afac5-1d6c-3014-be38-a7f79a0b8e7a
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /zz
  ws-headers:
    Host: azhk.zz123.xyz
  udp: true
- name: 5.03| 香港免流03 2
  server: hk03.zz123.xyz
  port: 80
  type: vmess
  uuid: 4aa916ea-c6b9-3e4c-ba36-7c7c2cbcd903
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /zz
  ws-headers:
    Host: a.189.cn
  udp: true
- name: 4.95| I6xHKHKTBGPVC36234
  server: yqy36234.china-cdn-net.com
  port: 36234
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36234.china-cdn-net.com
- name: 4.91| I6xTW台北HiNetVC31138
  server: yqy31138.china-cdn-net.com
  port: 31138
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31138.china-cdn-net.com
- name: 4.56| H3xTW台北HiNetVC31135
  server: yqy31135.china-cdn-net.com
  port: 31135
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31135.china-cdn-net.com
- name: 4.51| 日本03 2
  server: azhk.zz123.xyz
  port: 36813
  type: vmess
  uuid: 4aa916ea-c6b9-3e4c-ba36-7c7c2cbcd903
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /zz
  ws-headers:
    Host: azhk.zz123.xyz
  udp: true
- name: 4.43| H25xTW台北HiNetVC31132
  server: yqy31132.china-cdn-net.com
  port: 31132
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31132.china-cdn-net.com
- name: 4.06| 印度01
  server: azhk.zz123.xyz
  port: 33959
  type: vmess
  uuid: 4a4afac5-1d6c-3014-be38-a7f79a0b8e7a
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /zz
  ws-headers:
    Host: azhk.zz123.xyz
  udp: true
- name: 3.97| 韩国 2
  server: azhk.zz123.xyz
  port: 42799
  type: vmess
  uuid: 4aa916ea-c6b9-3e4c-ba36-7c7c2cbcd903
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /zz
  ws-headers:
    Host: azhk.zz123.xyz
  udp: true
- name: 3.96| H3xHKHKTBGPVC36233
  server: yqy36233.china-cdn-net.com
  port: 36233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36233.china-cdn-net.com
- name: 3.88| I6xTW台北HiNetVC31137
  server: yqy31137.china-cdn-net.com
  port: 31137
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31137.china-cdn-net.com
- name: 3.88| 香港免流01 2
  server: hk01.zz123.xyz
  port: 80
  type: vmess
  uuid: 4aa916ea-c6b9-3e4c-ba36-7c7c2cbcd903
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /zz
  ws-headers:
    Host: a.189.cn
  udp: true
- name: 3.81| 香港免流02
  server: hk02.zz123.xyz
  port: 80
  type: vmess
  uuid: 4a4afac5-1d6c-3014-be38-a7f79a0b8e7a
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /zz
  ws-headers:
    Host: a.189.cn
  udp: true
- name: 3.32| 香港3三网优化
  server: 615hk2.fans8.xyz
  port: 80
  type: vmess
  uuid: dd1e127b-7068-384f-98ac-b0358163017f
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /v2ray
  ws-headers:
    Host: 615hk2.fans8.xyz
  udp: true
- name: 3.14| 香港1三网优化
  server: 909hk1.fans8.xyz
  port: 80
  type: vmess
  uuid: dd1e127b-7068-384f-98ac-b0358163017f
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /v2ray
  ws-headers:
    Host: 909hk1.fans8.xyz
  udp: true
- name: 2.95|台湾01
  type: vmess
  server: jike-cccn2.ddns-only.xyz
  port: 39205
  uuid: b8da3f41-58ec-3294-891e-cc27ecb1244a
  alterId: 2
  cipher: auto
  udp: true
  network: ws
  ws-path: /jike1
  ws-headers:
    Host: jike1-hinet03.ddns-only.xyz
- name: 2.74| v2ray 马来西亚移动 Netflix
  server: cm.cheapv2.xyz
  port: 26610
  type: vmess
  uuid: 888215a8-77d4-3f31-8826-960470aa38af
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /index
  ws-headers:
    Host: cm.cheapv2.xyz
  udp: true
- name: 2.71|直连 新加坡1 Netflix SG
  type: vmess
  server: 165.22.61.210
  port: 21888
  uuid: 6ae2e994-2018-4f9f-a5bb-4639c14ba05f
  alterId: 1
  cipher: auto
  udp: true
  network: ws
- name: 2.62| HTW高雄龍抬頭HiNetVC33131
  server: yqy33131.china-cdn-net.com
  port: 33131
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33131.china-cdn-net.com
- name: 2.60| 美国02 2
  server: azhk.zz123.xyz
  port: 54188
  type: vmess
  uuid: 4aa916ea-c6b9-3e4c-ba36-7c7c2cbcd903
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /zz
  ws-headers:
    Host: azhk.zz123.xyz
  udp: true
- name: 2.51| ITW高雄龍抬頭HiNetVC33132
  server: yqy33132.china-cdn-net.com
  port: 33132
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33132.china-cdn-net.com
- name: 2.33| 马来西亚1三网优化
  server: 923my.fans8.xyz
  port: 80
  type: vmess
  uuid: dd1e127b-7068-384f-98ac-b0358163017f
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /v2ray
  ws-headers:
    Host: 923my.fans8.xyz
  udp: true
- name: 2.29| H3xTW台北HiNetVC31136
  server: yqy31136.china-cdn-net.com
  port: 31136
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31136.china-cdn-net.com
- name: 2.24| 香港免流05 2
  server: hk05.zz123.xyz
  port: 80
  type: vmess
  uuid: 4aa916ea-c6b9-3e4c-ba36-7c7c2cbcd903
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /zz
  ws-headers:
    Host: a.189.cn
  udp: true
- name: 2.21| HTW高雄龍抬頭HiNetVC33237
  server: yqy33237.china-cdn-net.com
  port: 33237
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33237.china-cdn-net.com
- name: 2.20|US16304
  server: 66.42.107.33
  type: vmess
  country: US
  port: 80
  uuid: 562398c8-cb7f-4850-90eb-2fd17dccb13a
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 2.16| I5xTW台北HiNetVC31131
  server: yqy31131.china-cdn-net.com
  port: 31131
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31131.china-cdn-net.com
- name: 2.15|US16330
  server: 150.230.43.190
  type: vmess
  country: US
  port: 80
  uuid: 476c12d2-676b-4ee3-bed7-1430f8e93589
  alterId: 16
  cipher: auto
  network: ws
  ws-path: /BEN
  servername: 150.230.43.190
  ws-headers:
    HOST: 150.230.43.190
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 2.05| ITW高雄龍抬頭HiNetVC33137
  server: yqy33137.china-cdn-net.com
  port: 33137
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33137.china-cdn-net.com
- name: 2.00|4566157195tcp
  server: 45.66.157.195
  port: 12233
  type: vmess
  uuid: 4cbb0ce4-1ec3-11ec-b76f-00163c06ad53
  alterId: 0
  cipher: auto
  tls: false
- name: 1.99|RelayAUAU287
  server: 168.138.28.215
  type: vmess
  country: AU
  port: 80
  uuid: 0e1b66d4-97a0-46f4-e8ee-ea2c15860ac6
  alterId: 16
  cipher: auto
  network: ws
  ws-path: /BEN
  servername: 168.138.28.215
  ws-headers:
    HOST: 168.138.28.215
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 1.98| 德国01
  server: azhk.zz123.xyz
  port: 46101
  type: vmess
  uuid: 4aa916ea-c6b9-3e4c-ba36-7c7c2cbcd903
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /zz
  ws-headers:
    Host: azhk.zz123.xyz
  udp: true
- name: 1.95| ITW高雄龍抬頭HiNetVC33138
  server: yqy33138.china-cdn-net.com
  port: 33138
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33138.china-cdn-net.com
- name: 1.58|US16320
  server: awsrb2.mooncloud.bike
  type: vmess
  country: US
  port: 10022
  uuid: 792f7496-a1e2-4694-96f4-5fbe5e13d68b
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 1.51|US16321
  server: aws.mooncloud.bike
  type: vmess
  country: US
  port: 10021
  uuid: 792f7496-a1e2-4694-96f4-5fbe5e13d68b
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- alterId: 1
  cipher: auto
  name: 1.50|1012oslook中国香港中国台湾CNChinaChangning可能是中转节点24
  network: tcp
  port: 10018
  server: us1.np.qjnodeip.xyz
  tls: false
  type: vmess
  uuid: 02c05e4c-3092-41e3-be4b-b49e9acbab21
  ws-path: /
- name: 1.48| HTW高雄龍抬頭HiNetVC33135
  server: yqy33135.china-cdn-net.com
  port: 33135
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy33135.china-cdn-net.com
- name: 1.47| H25xTW彰化HiNetVC32132
  server: yqy32132.china-cdn-net.com
  port: 32132
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32132.china-cdn-net.com
- name: 1.44|俄罗斯01
  type: vmess
  server: jike-shlt.ddns-only.xyz
  port: 39307
  uuid: b8da3f41-58ec-3294-891e-cc27ecb1244a
  alterId: 2
  cipher: auto
  udp: true
  network: ws
  ws-path: /jike1
  ws-headers:
    Host: jike1-ru04.ddns-only.xyz
- name: 1.42| cfmemcomRU俄罗斯联邦1
  server: ruml.jjyun.ren
  port: 80
  type: vmess
  uuid: 56a60bab-bcb5-4408-a956-59cb9987a784
  alterId: 10
  cipher: auto
  tls: false
  network: ws
  ws-path: /jjyun
  ws-headers:
    Host: ruml.jjyun.ren
- name: 1.40|4513513516tcp
  server: 45.135.135.16
  port: 11223
  type: vmess
  uuid: 5958e1e6-10af-11ec-9a8f-1aa60786834b
  alterId: 0
  cipher: auto
  tls: false
- name: 1.39|216105168138tcp
  server: 216.105.168.138
  port: 10964
  type: vmess
  uuid: b874d3a8-1ff8-11ec-9fc6-0cc47a52170a
  alterId: 0
  cipher: auto
  tls: false
- name: 1.38|259214249tcp
  server: 2.59.214.249
  port: 33445
  type: vmess
  uuid: aaad4b5a-1f4f-11ec-a856-82b57278959a
  alterId: 0
  cipher: auto
  tls: false
- alterId: 10
  cipher: auto
  name: 1.34|1012oslook英国GBUnited KiongdomLondon73
  network: ws
  port: 88
  server: ukml.52jjyun.top
  tls: false
  type: vmess
  uuid: 56a60bab-bcb5-4408-a956-59cb9987a784
  ws-path: /jjyun
- name: 1.28| I5xTW彰化HiNetVC32233
  server: yqy32233.china-cdn-net.com
  port: 32233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32233.china-cdn-net.com
- name: 1.27| 新加坡三网优化
  server: 1009sg.fans8.xyz
  port: 80
  type: vmess
  uuid: dd1e127b-7068-384f-98ac-b0358163017f
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /v2ray
  ws-headers:
    Host: 1009sg.fans8.xyz
  udp: true
- name: 1.17|JP7012  050Mb
  server: 146.56.118.208
  type: vmess
  country: JP
  port: 80
  uuid: 1d6e5f77-9af4-4709-dcbc-4fa280b32110
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /ben
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 1.13| I5xTW彰化HiNetVC32131
  server: yqy32131.china-cdn-net.com
  port: 32131
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32131.china-cdn-net.com
- name: 1.09|JP6948  609Mb
  server: 146.56.187.13
  type: vmess
  country: JP
  port: 80
  uuid: 562398c8-cb7f-4850-90eb-2fd17dccb13a
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
