proxies:
- name: ' vip3v2rayIplc专线 深圳香港 ②HULUHBO1749'
  server: 4.ssrj.xyz
  port: 65104
  type: vmess
  uuid: 24ea3f63-d495-3a0a-a7de-f92a4e6fb9ae
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
- name: HK54751972938
  server: azure.trass.mwjg.xyz
  type: vmess
  country: HK
  port: 51111
  uuid: b7fd79eb-5e0f-4ad2-b0b5-f74716a88d8c
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' vip3v2rayIplc专线 深圳香港 ⑥ DMITNETFLIXHULUHBO1751'
  server: 8.ssrj.xyz
  port: 65108
  type: vmess
  uuid: 24ea3f63-d495-3a0a-a7de-f92a4e6fb9ae
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
- name: ' vip1V2ray 新加坡 ⑮解锁Netflix1739'
  server: 65.ssrj.xyz
  port: 65165
  type: vmess
  uuid: 24ea3f63-d495-3a0a-a7de-f92a4e6fb9ae
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
- name: ' vip1V2ray新加坡 ③1742'
  server: 49.ssrj.xyz
  port: 61149
  type: vmess
  uuid: 24ea3f63-d495-3a0a-a7de-f92a4e6fb9ae
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
- name: US1560428013090
  server: 23.224.191.13
  type: vmess
  country: US
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /footers
  servername: www.64212792.xyz
  ws-headers:
    HOST: www.64212792.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' vip1V2ray 新加坡 ⑬解锁Netflix1738'
  server: 63.ssrj.xyz
  port: 65163
  type: vmess
  uuid: 24ea3f63-d495-3a0a-a7de-f92a4e6fb9ae
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
- name: ' 新加坡小白610295929383109'
  server: cm.syhwdz.top
  port: 40858
  type: vmess
  uuid: 7cb95511-67e5-35a0-a093-96fde16be539
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /cdnxxy
  ws-headers:
    Host: music.163.com
- name: ' I6xHKHKTBGPVC3613422203056'
  server: yqy36134.china-cdn-net.com
  port: 36134
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36134.china-cdn-net.com
- name: ' H25xTW彰化HiNetVC3213221723026'
  server: yqy32132.china-cdn-net.com
  port: 32132
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32132.china-cdn-net.com
- name: ' H3xTW彰化HiNetVC3213622023043'
  server: yqy32136.china-cdn-net.com
  port: 32136
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32136.china-cdn-net.com
- name: ' H25xTW台北HiNetVC3123221693023'
  server: yqy31232.china-cdn-net.com
  port: 31232
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31232.china-cdn-net.com
- server: 13.75.55.34
  network: ws
  port: 10085
  name: 中国香港0v2ray13755534100851575
  uuid: b2053f19-19d8-4776-bd10-2b4191105648
  type: vmess
  cipher: auto
  alterId: 4
  tls: false
  ws-path: /
- name: ' 香港1原生ip负载均衡解锁流媒体614296329423113'
  server: hk1.earths.team
  port: 10085
  type: vmess
  uuid: b2053f19-19d8-4776-bd10-2b4191105648
  alterId: 1
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /
  ws-headers:
    Host: hk1.earths.team
- name: RelayCNSG9025623072
  server: rxzgzq.moox.icu
  type: vmess
  country: CN
  port: 34015
  uuid: 6c61989e-00a7-406e-b8c7-df2d6592ed18
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: HK548018129193097
  server: 903hk01.fans8.xyz
  type: vmess
  country: HK
  port: 80
  uuid: 1b1b45d1-d5ab-34df-830e-d2d2d62664df
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /v2ray
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' I5xTW台北HiNetVC3113122073046'
  server: yqy31131.china-cdn-net.com
  port: 31131
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31131.china-cdn-net.com
- name: ' H3xTW台北HiNetVC3113521973038'
  server: yqy31135.china-cdn-net.com
  port: 31135
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31135.china-cdn-net.com
- name: ' I5xTW彰化HiNetVC3213122113050'
  server: yqy32131.china-cdn-net.com
  port: 32131
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32131.china-cdn-net.com
- name: ' I6xTW台北HiNetVC3113722253060'
  server: yqy31137.china-cdn-net.com
  port: 31137
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31137.china-cdn-net.com
- name: ' H3xTW彰化HiNetVC3213522013042'
  server: yqy32135.china-cdn-net.com
  port: 32135
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32135.china-cdn-net.com
- name: ' I5xTW彰化HiNetVC3223322123051'
  server: yqy32233.china-cdn-net.com
  port: 32233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32233.china-cdn-net.com
- name: ' H25xTW彰化HiNetVC3223221733027'
  server: yqy32232.china-cdn-net.com
  port: 32232
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy32232.china-cdn-net.com
- name: RelayCNJP254510242957
  server: cmgz1.racernet.link
  type: vmess
  country: CN
  port: 1443
  uuid: 92e7a42e-e8a6-31b2-bfd8-68f517bd3266
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /cm/gz1/jp1
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: RelayAUAU16949912948
  server: blog.chaoge.cool
  type: vmess
  country: AU
  port: 29543
  uuid: 8d9184d2-ec19-47d3-81a1-a3f43cf40bd9
  alterId: 64
  cipher: auto
  network: ws
  ws-path: /
  servername: pull.free.video.10010.com
  ws-headers:
    HOST: pull.free.video.10010.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: RelayCNSG35 2301Mb26493075
  server: ngzyd-1.okex-tradebot.xyz
  type: vmess
  country: CN
  port: 30004
  uuid: 8c0f98f0-692e-48f9-9c25-af743089ea31
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' I6xTW台北HiNetVC3113822263061'
  server: yqy31138.china-cdn-net.com
  port: 31138
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31138.china-cdn-net.com
- name: RelayCNTW676052943
  server: rxzgzq.moox.icu
  type: vmess
  country: CN
  port: 40025
  uuid: 6c61989e-00a7-406e-b8c7-df2d6592ed18
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 37长期套餐覆盖IPLC专线838298329593129
  server: yqy2337.china-cdn-net.com
  port: 2337
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2337.china-cdn-net.com
- name: ' H3xHKHKTBGPVC3633321943035'
  server: yqy36333.china-cdn-net.com
  port: 36333
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36333.china-cdn-net.com
- name: RelayUSUS1787012122982
  server: c10s4.jamjams.net
  type: vmess
  country: US
  port: 15838
  uuid: f7d47295-4d30-475e-8eeb-76cb8e4c49c0
  alterId: 8
  cipher: auto
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' H3xHKHKTBGPVC3613321923033'
  server: yqy36133.china-cdn-net.com
  port: 36133
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36133.china-cdn-net.com
- name: ' 新加坡4ip负载均衡解锁流媒体617296629453116'
  server: sg2.earths.team
  port: 10085
  type: vmess
  uuid: b2053f19-19d8-4776-bd10-2b4191105648
  alterId: 1
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /
  ws-headers:
    Host: sg2.earths.team
- name: RelayCNHK5992243
  server: rxzgzq.moox.icu
  type: vmess
  country: CN
  port: 34001
  uuid: 6c61989e-00a7-406e-b8c7-df2d6592ed18
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: RelayCNTW6052249
  server: gy1-120.lhcloud.xyz
  type: vmess
  country: CN
  port: 40003
  uuid: 16e56b3c-888c-4a52-9363-7ea2ba771041
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' I5xTW台北HiNetVC3123322083047'
  server: yqy31233.china-cdn-net.com
  port: 31233
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31233.china-cdn-net.com
- name: ' 香港5309623297029493120'
  server: 52.229.154.191
  port: 80
  type: vmess
  uuid: acee9a77-5023-4793-8c3b-46b464ba10b6
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /
  ws-headers:
    Host: 52.229.154.191
- name: 36中继中转隧道线路覆盖837298229583128
  server: yqy2336.china-cdn-net.com
  port: 2336
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2336.china-cdn-net.com
- name: 34捐赠解锁更多协议线路835298029573127
  server: yqy2334.china-cdn-net.com
  port: 2334
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2334.china-cdn-net.com
- name: ' H25xTW台北HiNetVC3113221683022'
  server: yqy31132.china-cdn-net.com
  port: 31132
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy31132.china-cdn-net.com
- name: ' 印度1 107Mbps 729ms 奈飞自制剧631297129503121'
  server: gzcm.sspro.nl
  port: 10799
  type: vmess
  uuid: fd252902-aac0-36be-8420-a3b23fe803af
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /ssrgr-in02
  ws-headers:
    Host: none
- name: 台湾012035
  type: vmess
  server: jike-cccn2.ddns-only.xyz
  port: 39205
  uuid: b8da3f41-58ec-3294-891e-cc27ecb1244a
  alterId: 2
  cipher: auto
  udp: true
  network: ws
  ws-path: /jike1
  ws-headers:
    Host: jike1-hinet03.ddns-only.xyz
- name: 33公益等级線路嚴格限速834297929563126
  server: yqy2333.china-cdn-net.com
  port: 2333
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /
  ws-headers:
    Host: yqy2333.china-cdn-net.com
- name: 35包括V2ray和Trojan21593018
  server: yqy2335.china-cdn-net.com
  port: 2335
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy2335.china-cdn-net.com
- name: CN2550165
  server: 139.155.22.227
  type: vmess
  country: CN
  port: 49110
  uuid: f7675b7e-59bf-435c-ac03-dc2482f27e5d
  alterId: 64
  cipher: auto
  network: tcp
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' 新加坡1ip负载均衡解锁流媒体616296529443115'
  server: sg1.earths.team
  port: 10085
  type: vmess
  uuid: b2053f19-19d8-4776-bd10-2b4191105648
  alterId: 1
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /
  ws-headers:
    Host: sg1.earths.team
- name: ' 中转RUS俄国 A  宁波电信18533007'
  server: 115.231.187.1
  port: 80
  type: vmess
  uuid: ee786623-dc46-4461-a45a-3b326dbc2e8d
  alterId: 1
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /
  ws-headers:
    Host: 007.cdn.8x.cx.hit.edu.cn
- name: ' I6xHKHKTBGPVC3623422213057'
  server: yqy36234.china-cdn-net.com
  port: 36234
  type: vmess
  uuid: 27d52299-cc4e-3a79-830a-bc7ee4c81a8e
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /iso
  ws-headers:
    Host: yqy36234.china-cdn-net.com
- name: ' 韩国1负载均衡解锁流媒体619296829473118'
  server: kr1.earths.team
  port: 10085
  type: vmess
  uuid: b2053f19-19d8-4776-bd10-2b4191105648
  alterId: 1
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /
  ws-headers:
    Host: kr1.earths.team
- name: ' JP644326953079'
  server: 18.183.184.29
  type: vmess
  country: ' JP'
  port: 23333
  uuid: b7fd79eb-5e0f-4ad2-b0b5-f74716a88d8c
  alterId: 1
  cipher: auto
  network: ws
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
