proxies:
- name: 4513513516tcp3
  server: 45.135.135.16
  port: 11226
  type: vmess
  uuid: 5958e1e6-10af-11ec-9a8f-1aa60786834b
  alterId: 0
  cipher: auto
  tls: false
- name: ' mattkaydiarycom中国香港特别行政区HKHongkong SAR ChinaHong Kong2134'
  server: azure-f4s-hk.transfer-xray.tk
  port: 50166
  type: vmess
  uuid: 7f935d17-1ab7-11ec-977e-edc61c6efe8b
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-path: /4e1pxo3m/
  ws-headers:
    Host: azure-f4s-hk.transfer-xray.tk
