proxies:
- name: ' mattkaydiarycom中国香港特别行政区HKHongkong SAR ChinaHong Kong2406'
  server: tk.shcn2.tkddns.xyz
  port: 22642
  type: vmess
  uuid: 98e96c9f-4bb3-39d4-9a2c-fac04257f7c7
  alterId: 2
  cipher: auto
  tls: true
  network: ws
  ws-path: /
  ws-headers:
    Host: zxjp-b.tkong.cc
- name: ' mattkaydiarycom美国USUSASanta Clarita2539'
  server: 173.82.55.94
  port: 443
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-path: /footers
  ws-headers:
    Host: www.01787634.xyz
- name: ' mattkaydiarycom美国USUSASan Jose2518'
  server: 107.148.198.53
  port: 443
  type: vmess
  uuid: 4c7923df-700f-4bf2-918e-08c6e141037c
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-path: /footers
  ws-headers:
    Host: www.78577665.xyz
- name: ' mattkaydiarycom美国USUSASanta Clarita2335'
  server: 173.82.55.93
  port: 443
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-path: /footers
  ws-headers:
    Host: www.01787634.xyz
