proxies:
- name: 4.03|Relay7534Mb
  server: hkt.jslist.tk
  type: vmess
  country: US
  port: 8880
  uuid: efe08abe-e627-4f72-f02f-af00692a0bf4
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /api/images
  servername: hkt.jslist.tk
  ws-headers:
    HOST: hkt.jslist.tk
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 3.58|Relay 650Mb
  server: arm.50k.one
  type: vmess
  country: JP
  port: 39966
  uuid: 608408f6-fd79-49a3-96ef-003266a773a0
  alterId: 0
  cipher: auto
  network: tcp
  ws-path: /
  servername: arm.50k.one
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 3.39| 韩国 2
  server: amd.50k.one
  port: 30943
  type: vmess
  uuid: a0654eba-7b58-4d64-cfdb-c006e5d38324
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: false
  udp: true
- name: 1.75| RelaySESE1132
  server: se.oceancloud.asia
  port: 12100
  type: vmess
  uuid: adfc4bf6-8f7d-393e-9997-7dd969d9ea88
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-path: /se
  ws-headers:
    Host: se.oceancloud.asia
- name: 1.34|AE193123951141244
  server: 193.123.95.114
  port: 21999
  type: vmess
  uuid: 061a5ca3-09f7-413e-8d4d-35775bb5c0eb
  alterId: 0
  cipher: auto
  skip-cert-vertify: false
  network: ws
  ws-path: /
  tls: false
  ws-headers:
    Host: 193.123.95.114
