proxies:
- name: 6.20|Relay 661Mb
  server: 113.wowogg.cyou
  type: vmess
  country: US
  port: 52213
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: /
  servername: 113.wowogg.cyou
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 5.85|Relay6670Mb
  server: 99.wowogg.cyou
  type: vmess
  country: HK
  port: 52299
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: t.me/vpnpool
  servername: 99.wowogg.cyou
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 5.36|Relay 693Mb
  server: 128.wowogg.cyou
  type: vmess
  country: HK
  port: 52228
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: t.me/vpnpool
  servername: 128.wowogg.cyou
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 5.29| RelayHKJP830 4001Mb
  server: 96.wgong.xyz
  port: 52296
  type: vmess
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  tls: false
- name: 5.17|香港Youtube技术分享室
  server: 128.wgong.xyz
  port: 52228
  type: vmess
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: true
  udp: true
- name: 5.14|Relay6465Mb
  server: 108.wowogg.cyou
  type: vmess
  country: HK
  port: 11224
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: t.me/vpnpool
  servername: 108.wowogg.cyou
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 5.13| US151 TGpeekfun
  server: 20.24.103.39
  port: 52437
  type: vmess
  country: ' US'
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: tcp
  http-opts: {}
  ws-path: /
  ws-headers:
    HOST: 137.wgong.xyz
  skip-cert-verify: true
  servername: 137.wgong.xyz
- name: 5.12| HK80 TGpeekfun
  server: 20.187.117.67
  port: 52332
  type: vmess
  country: ' HK'
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: tcp
  http-opts: {}
  ws-path: /
  ws-headers:
    HOST: 132.wgong.xyz
  skip-cert-verify: true
  servername: 132.wgong.xyz
- name: 5.04| HK81 TGpeekfun
  server: 104.208.79.110
  port: 52210
  type: vmess
  country: ' HK'
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  http-opts: {}
  ws-path: /
  skip-cert-verify: true
- name: 5.03|Relay 492Mb
  server: 20.187.115.172
  type: vmess
  country: HK
  port: 52228
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: t.me/vpnpool
  servername: 20.187.115.172
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 5.03|Relay 199Mb
  server: 91.wowogg.cyou
  type: vmess
  country: HK
  port: 52291
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: t.me/vpnpool
  servername: 91.wowogg.cyou
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 5.03|HK2020561510901
  server: 89.wowogg.cyou
  port: 52289
  type: vmess
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  skip-cert-vertify: false
  network: none
  ws-path: /
  tls: false
  ws-headers:
    Host: 89.wowogg.cyou
- name: 5.02|Relay 704Mb
  server: 88.wowogg.cyou
  type: vmess
  country: HK
  port: 52288
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: t.me/vpnpool
  servername: 88.wowogg.cyou
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 5.02|Relay2654Mb
  server: 102.wowogg.cyou
  type: vmess
  country: HK
  port: 11221
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: /
  servername: 102.wowogg.cyou
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 5.01|Relay1661Mb
  server: 133.wowogg.cyou
  type: vmess
  country: HK
  port: 52333
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: t.me/vpnpool
  servername: 133.wowogg.cyou
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 5.01|HK20187752160062
  server: 95.wowogg.cyou
  port: 52295
  type: vmess
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  skip-cert-vertify: false
  network: tcp
  ws-path: /
  tls: false
  ws-headers:
    Host: 95.wowogg.cyou
- name: 5.00|Relay6797Mb
  server: 85.wowogg.cyou
  type: vmess
  country: HK
  port: 52285
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: t.me/vpnpool
  servername: 85.wowogg.cyou
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 4.98|Relay1795Mb
  server: 107.wowogg.cyou
  type: vmess
  country: US
  port: 52207
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: /
  servername: 107.wowogg.cyou
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 4.88|Relay2045Mb
  server: 130.wowogg.cyou
  type: vmess
  country: HK
  port: 52330
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: t.me/vpnpool
  servername: 130.wowogg.cyou
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 4.83|Relay7602Mb
  server: 134.wowogg.cyou
  type: vmess
  country: HK
  port: 52334
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: t.me/vpnpool
  servername: 134.wowogg.cyou
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 3.97|Relay1416Mb
  server: 117.28.243.173
  type: ss
  country: CN
  port: 4173
  password: passinfo123
  cipher: rc4-md5
- name: 3.54|韩国阿伟科技TG油管
  server: dali-hz.8n4t.cn
  port: 37211
  type: vmess
  uuid: 061a5ca3-09f7-413e-8d4d-35775bb5c0eb
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /theuploadapi
  ws-headers:
    Host: oracle.kr.tgproxy.wtf
  udp: true
- name: 3.51|RELAY104226680679
  server: 104.22.66.8
  port: 443
  type: vmess
  uuid: a2c47c59-a4c8-4d66-9456-966ba37dedcc
  alterId: 0
  cipher: auto
  skip-cert-vertify: false
  network: ws
  ws-path: /The-Great-Awakening_vws
  tls: true
  ws-headers:
    Host: vincent-jackson2021.ga
- name: 3.43|RELAY10427197630763
  server: 104.27.197.63
  port: 443
  type: vmess
  uuid: 188741f2-1f14-43cb-be7a-1200a9f4332e
  alterId: 0
  cipher: auto
  skip-cert-vertify: false
  network: ws
  ws-path: /The-Great-Awakening_vws
  tls: true
  ws-headers:
    Host: vincent-jackson2022.ml
- name: 3.35|RelayZZZZ3548 2761Mb
  server: 198.41.221.169
  port: 443
  type: vmess
  uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /sakura/
  ws-headers:
    Host: zero1.a-yu.xyz
- name: 3.32| RelayCNKR422 2566Mb
  server: 111.28.3.117
  port: 60018
  type: vmess
  uuid: 19ff88ff-a3c1-3a90-82fd-e7daf29f7b11
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-path: /
  ws-headers:
    Host: download.cn.connecat.com
- name: 3.30|Relay1105Mb
  server: shonlinecu.proconcn.xyz
  type: ssr
  country: CN
  port: 560
  password: mblank1port
  cipher: chacha20-ietf
  protocol: auth_aes128_md5
  protocol-param: 50374:ff112233
  obfs: plain
- name: 3.27|RelayZZZZ3544 2766Mb
  server: 198.41.212.14
  port: 443
  type: vmess
  uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /sakura/
  ws-headers:
    Host: zero1.a-yu.xyz
- name: 3.18|RelayZZZZ3546 2501Mb
  server: 198.41.212.8
  port: 443
  type: vmess
  uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /sakura/
  ws-headers:
    Host: zero1.a-yu.xyz
- name: 3.17|Relay1017Mb
  server: 0107hk.fans8.xyz
  type: vmess
  country: ZZ
  port: 80
  uuid: 5c70da5d-e641-3bf8-b7dc-5babd843ff3c
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /v2ray
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 3.13| RelayCNSG443
  server: 111.28.3.117
  port: 60019
  type: vmess
  uuid: 19ff88ff-a3c1-3a90-82fd-e7daf29f7b11
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-path: /
  ws-headers:
    Host: download.cn.connecat.com
- name: 3.11|RelayZZZZ3549 2379Mb
  server: 198.41.212.18
  port: 443
  type: vmess
  uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /sakura/
  ws-headers:
    Host: zero1.a-yu.xyz
- name: 2.94|RELAY10416182150571
  server: 104.16.182.15
  port: 443
  type: vmess
  uuid: a2c47c59-a4c8-4d66-9456-966ba37dedcc
  alterId: 0
  cipher: auto
  skip-cert-vertify: false
  network: ws
  ws-path: /The-Great-Awakening_vws
  tls: true
  ws-headers:
    Host: vincent-jackson2021.ga
- name: 2.88| githubcomfreefq  美国CloudFlare节点 19
  server: 198.41.212.9
  port: 443
  type: vmess
  uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /sakura/
  ws-headers:
    Host: zero1.a-yu.xyz
- name: 2.86|RelayZZZZ3550 2691Mb
  server: 198.41.212.2
  port: 443
  type: vmess
  uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /sakura/
  ws-headers:
    Host: zero1.a-yu.xyz
- name: 2.85|Relay2763Mb
  server: download.cn.connecat.com
  type: vmess
  country: CN
  port: 60017
  uuid: 19ff88ff-a3c1-3a90-82fd-e7daf29f7b11
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /
  servername: '%7B%22Host%22:%22download.cn.connecat.com%22%7D'
  ws-headers:
    HOST: '%7B%22Host%22:%22download.cn.connecat.com%22%7D'
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 2.81|RELAY17267541930594
  server: 172.67.54.193
  port: 443
  type: vmess
  uuid: 5f4b2e42-ff2b-4342-86fc-b7ba1b5361e8
  alterId: 0
  cipher: auto
  skip-cert-vertify: false
  network: ws
  ws-path: /The-Great-Awakening_vws
  tls: true
  ws-headers:
    Host: vincent-jackson2022.ga
- name: 2.81|RELAY104251042400711
  server: 104.25.104.240
  port: 443
  type: vmess
  uuid: a2c47c59-a4c8-4d66-9456-966ba37dedcc
  alterId: 0
  cipher: auto
  skip-cert-vertify: false
  network: ws
  ws-path: /The-Great-Awakening_vws
  tls: true
  ws-headers:
    Host: vincent-jackson2021.ga
- name: 2.79|RELAY19841212110305
  server: 198.41.212.11
  port: 443
  type: vmess
  uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60
  alterId: 0
  cipher: auto
  skip-cert-vertify: false
  network: ws
  ws-path: /sakura/
  tls: true
  ws-headers:
    Host: zero1.a-yu.xyz
- name: 2.78| RelayCNMO417
  server: 111.28.3.117
  port: 60011
  type: vmess
  uuid: 19ff88ff-a3c1-3a90-82fd-e7daf29f7b11
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-path: /
  ws-headers:
    Host: download.cn.connecat.com
- name: 2.68|Relay 166Mb
  server: sxqxj.cn
  type: vmess
  country: CN
  port: 2164
  uuid: aba50dd4-5484-3b05-b14a-4661caf862d5
  alterId: 4
  cipher: auto
  network: ws
  ws-path: /ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 2.65| RelayUSZZ2805 2418Mb
  server: cloudflare.a-yu.xyz
  port: 443
  type: vmess
  uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /sakura/
  ws-headers:
    Host: zero2.a-yu.xyz
- name: 2.64| 韩国 1
  server: vn.mumi.bid
  port: 10125
  type: vmess
  uuid: 83ae9f04-47f0-4e34-9a1c-9c2e5161f586
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: vn.mumi.bid
  udp: true
- name: 2.60|Relay4319Mb
  server: 111.28.3.106
  type: vmess
  country: CN
  port: 60017
  uuid: 19ff88ff-a3c1-3a90-82fd-e7daf29f7b11
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /
  servername: download.cn.connecat.com
  ws-headers:
    HOST: download.cn.connecat.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 2.55|RELAY104251401530593
  server: 104.25.140.153
  port: 443
  type: vmess
  uuid: 5f4b2e42-ff2b-4342-86fc-b7ba1b5361e8
  alterId: 0
  cipher: auto
  skip-cert-vertify: false
  network: ws
  ws-path: /The-Great-Awakening_vws
  tls: true
  ws-headers:
    Host: vincent-jackson2022.ga
- name: 2.44|Relay2294Mb
  server: 1222mnl.fans8.xyz
  type: vmess
  country: CA
  port: 80
  uuid: 5c70da5d-e641-3bf8-b7dc-5babd843ff3c
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /v2ray
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 2.36| RelayCNSG414
  server: 111.28.3.106
  port: 60020
  type: vmess
  uuid: 19ff88ff-a3c1-3a90-82fd-e7daf29f7b11
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-path: /
  ws-headers:
    Host: download.cn.connecat.com
- name: 2.29| RelayCNSG423 2732Mb
  server: 111.28.3.117
  port: 60020
  type: vmess
  uuid: 19ff88ff-a3c1-3a90-82fd-e7daf29f7b11
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-path: /
  ws-headers:
    Host: download.cn.connecat.com
- name: 2.28|RelayCNHK12
  server: 120.232.208.195
  type: vmess
  country: CN
  port: 19085
  uuid: 1b9b7dfc-d92b-35f0-88a3-587c7798d9e3
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /dahjwuh
  servername: cdn-cn.nekocloud.cn
  ws-headers:
    HOST: cdn-cn.nekocloud.cn
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 2.28| RelayCNSG430
  server: 111.28.3.106
  port: 60019
  type: vmess
  uuid: 19ff88ff-a3c1-3a90-82fd-e7daf29f7b11
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-path: /
  ws-headers:
    Host: download.cn.connecat.com
