proxies:
- name: 3.87|CYL科技20220213 16
  server: 3.35.206.85
  port: 8080
  type: vmess
  uuid: bec0f7e4-500f-4746-8e22-ce1430e51bcf
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /
  ws-headers:
    Host: 3.35.206.85
  udp: true
- name: 3.27|Relay  575Mb
  server: xmlinodejp.aifx.eu.org
  port: 11019
  type: vmess
  uuid: 69b0c606-a218-434d-99c0-331cb3c2762a
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-path: /freebaipiao
  ws-headers:
    Host: www.yyxi.ml
- name: 2.78|CYL科技20220213 2
  server: 3.112.20.77
  port: 8080
  type: vmess
  uuid: bec0f7e4-500f-4746-8e22-ce1430e51bcf
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /
  ws-headers:
    Host: 3.112.20.77
  udp: true
- name: 2.10| 台湾阿伟科技TG油管 3
  server: tw01.lilyco.cc
  port: 59801
  type: vmess
  uuid: a209854a-30ed-4887-e7d2-70c7e45f814c
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /
  ws-headers:
    Host: tw01.lilyco.cc
- name: 1.76| 瑞典阿伟科技TG油管
  server: se.oceancloud.asia
  port: 12100
  type: vmess
  uuid: adfc4bf6-8f7d-393e-9997-7dd969d9ea88
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /se
  ws-headers:
    Host: se.oceancloud.asia
- name: 1.58| 瑞典阿伟科技TG油管 2
  server: 176.126.70.189
  port: 12100
  type: vmess
  uuid: adfc4bf6-8f7d-393e-9997-7dd969d9ea88
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: false
  network: ws
  ws-path: /se
  ws-headers:
    Host: se.oceancloud.asia
