proxies:
- name: 7.29|上海CN2
  type: ss
  server: cn2.gzhpxb.com
  port: 20166
  cipher: aes-128-gcm
  password: yangchaoyue
  udp: true
  skip-cert-verify: true
- name: 6.87|CYL科技20220213 16
  server: 117.28.243.220
  port: 8254
  type: ss
  cipher: rc4-md5
  password: passinfo123
  udp: true
- name: 6.52|Relay  786Mb
  server: sxqxj.cn
  type: vmess
  country: CN
  port: 2164
  uuid: aba50dd4-5484-3b05-b14a-4661caf862d5
  alterId: 4
  cipher: auto
  network: ws
  ws-path: /ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: 6.43|ss
  type: ss
  server: fkgfw-prod.i.sxl.cn
  port: 443
  cipher: aes-256-cfb
  password: E4DNMf73kHPrd8Qq7aqGPf7f
  _index: 0
- name: 6.25| 11448Mb
  server: 18.162.222.253
  type: ss
  country: HK
  port: 38273
  password: 3b07447e-94cf-4d72-96c6-d0a539098049
  cipher: aes-256-gcm
- name: 6.00|Relay 1179Mb
  server: shonlinecu.proconcn.xyz
  type: ssr
  country: CN
  port: 561
  password: mblank1port
  cipher: chacha20-ietf
  protocol: auth_aes128_md5
  protocol-param: 50374:ff112233
  obfs: plain
- name: 5.86|Relay 5098Mb
  server: shonlinesandcu03.proconcn.xyz
  type: ssr
  country: CN
  port: 561
  password: mblank1port
  cipher: chacha20-ietf
  protocol: auth_aes128_md5
  protocol-param: 50374:ff112233
  obfs: plain
- name: 5.80|Relay 4807Mb
  server: 99.wowogg.cyou
  type: vmess
  country: HK
  port: 52299
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: t.me/vpnpool
  servername: 99.wowogg.cyou
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 5.38| US170 TGpeekfun
  server: 20.24.103.39
  port: 52437
  type: vmess
  country: ' US'
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: tcp
  http-opts: {}
  ws-path: /
  ws-headers:
    HOST: 137.wgong.xyz
  skip-cert-verify: true
  servername: 137.wgong.xyz
- name: 5.29|Relay 7948Mb
  server: hkt.jslist.tk
  type: vmess
  country: US
  port: 8880
  uuid: efe08abe-e627-4f72-f02f-af00692a0bf4
  alterId: 0
  cipher: auto
  network: ws
  ws-path: /api/images
  servername: hkt.jslist.tk
  ws-headers:
    HOST: hkt.jslist.tk
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 5.25|Relay 2241Mb
  server: 135.wgong.xyz
  type: vmess
  country: HK
  port: 52335
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: tcp
  ws-path: /
  servername: 135.wgong.xyz
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 5.24| httpsgitiov9999ip3香港19
  server: 95.wowogg.cyou
  port: 52295
  type: vmess
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  tls: false
- name: 5.20| HK85 TGpeekfun
  server: 20.187.117.67
  port: 52332
  type: vmess
  country: ' HK'
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: tcp
  http-opts: {}
  ws-path: /
  ws-headers:
    HOST: 132.wgong.xyz
  skip-cert-verify: true
  servername: 132.wgong.xyz
- name: 5.20|Relay 1093Mb
  server: v115.wgong.xyz
  type: vmess
  country: HK
  port: 52215
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: tcp
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 5.14|RELAY1984121220340
  server: 198.41.212.2
  port: 443
  type: vmess
  uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60
  alterId: 0
  cipher: auto
  skip-cert-vertify: false
  network: ws
  ws-path: /sakura/
  tls: true
  ws-headers:
    Host: zero1.a-yu.xyz
- name: 5.12|Relay 2231Mb
  server: 115.wowogg.cyou
  type: vmess
  country: HK
  port: 52215
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: tcp
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 5.11|Relay 2390Mb
  server: 130.wowogg.cyou
  type: vmess
  country: HK
  port: 52330
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: t.me/vpnpool
  servername: 130.wowogg.cyou
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 5.11|小汐搬运1513W用户覆盖节点名称广告转化tmebyxiaoxi
  server: 198.41.212.5
  port: 443
  type: vmess
  uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /sakura/
  ws-headers:
    Host: zero1.a-yu.xyz
- name: 5.05|Relay  199Mb
  server: 91.wowogg.cyou
  type: vmess
  country: HK
  port: 52291
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: t.me/vpnpool
  servername: 91.wowogg.cyou
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 5.03|RELAY19841212181065
  server: 198.41.212.18
  port: 443
  type: vmess
  uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60
  alterId: 0
  cipher: auto
  skip-cert-vertify: false
  network: ws
  ws-path: /sakura/
  tls: true
  ws-headers:
    Host: zero1.a-yu.xyz
- name: 5.00|小汐搬运1413W用户覆盖节点名称广告转化tmebyxiaoxi
  server: 198.41.221.169
  port: 443
  type: vmess
  uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /sakura/
  ws-headers:
    Host: zero1.a-yu.xyz
- name: 4.99|Relay 7275Mb
  server: 107.wowogg.cyou
  type: vmess
  country: US
  port: 52207
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: /
  servername: 107.wowogg.cyou
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 4.99|Relay  632Mb
  server: ppycn1.ddnsnode.com
  type: vmess
  country: CN
  port: 26010
  uuid: 4b8010fb-60b7-341a-b1b6-135ed84ced4a
  alterId: 0
  cipher: auto
  network: none
  ws-path: /
  servername: ppycn1.ddnsnode.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 4.96| HK86 TGpeekfun
  server: 104.208.79.110
  port: 52210
  type: vmess
  country: ' HK'
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  http-opts: {}
  ws-path: /
  skip-cert-verify: true
- name: 4.93|韩国阿伟科技TG油管
  server: dali-hz.8n4t.cn
  port: 37211
  type: vmess
  uuid: 061a5ca3-09f7-413e-8d4d-35775bb5c0eb
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  network: ws
  ws-path: /theuploadapi
  ws-headers:
    Host: oracle.kr.tgproxy.wtf
  udp: true
- name: 4.87| httpsgitiov9999ip3香港23
  server: 110.wowogg.cyou
  port: 52210
  type: vmess
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  tls: false
- name: 4.86|httpsgitiov9999ip312
  server: 198.41.212.13
  port: 443
  type: vmess
  uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /sakura/
    headers:
      Host: zero1.a-yu.xyz
- name: 4.86|Relay 3033Mb
  server: 20.187.115.172
  type: vmess
  country: HK
  port: 52228
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: t.me/vpnpool
  servername: 20.187.115.172
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 4.86|Relay 5725Mb
  server: 87.wowogg.cyou
  type: vmess
  country: US
  port: 52287
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: tcp
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 4.78|Relay 5524Mb
  server: 134.wowogg.cyou
  type: vmess
  country: HK
  port: 52334
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: t.me/vpnpool
  servername: 134.wowogg.cyou
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 4.74|Relay 2504Mb
  server: 128.wowogg.cyou
  type: vmess
  country: HK
  port: 52228
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: t.me/vpnpool
  servername: 128.wowogg.cyou
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 4.71|Relay 3591Mb
  server: gz2.52168.xyz
  type: ssr
  country: CN
  port: 2106
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
- name: 4.64|RelayCNJP286
  server: gz2.52168.xyz
  type: ssr
  country: CN
  port: 2107
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
- name: 4.62|Relay 1043Mb
  server: 137.wgong.xyz
  type: vmess
  country: HK
  port: 52437
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: tcp
  ws-path: /
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 4.55|Relay 4616Mb
  server: 132.wgong.xyz
  type: vmess
  country: HK
  port: 52332
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: tcp
  ws-path: /
  servername: 132.wgong.xyz
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 4.49|Relay 8831Mb
  server: 85.wowogg.cyou
  type: vmess
  country: HK
  port: 52285
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: t.me/vpnpool
  servername: 85.wowogg.cyou
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 4.48|RELAY1984121280728
  server: 198.41.212.8
  port: 443
  type: vmess
  uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60
  alterId: 0
  cipher: auto
  skip-cert-vertify: false
  network: ws
  ws-path: /sakura/
  tls: true
  ws-headers:
    Host: zero1.a-yu.xyz
- name: 4.43|Relay  725Mb
  server: gz1.52168.xyz
  type: ssr
  country: CN
  port: 1114
  password: epChJS35fV
  cipher: aes-256-cfb
  protocol: auth_aes128_sha1
  protocol-param: 149:y711wfz6uln
  obfs: tls1.2_ticket_auth
  obfs-param: 30a2a149.baidu.com
- name: 4.41|Relay 5539Mb
  server: 136.wowogg.cyou
  type: vmess
  country: HK
  port: 52436
  uuid: 08103798-414e-32b6-8748-2507732d2c51
  alterId: 2
  cipher: auto
  network: none
  ws-path: t.me/vpnpool
  servername: 136.wowogg.cyou
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 4.38|RelayCNKR339 2228Mb
  server: 183.232.56.161
  type: vmess
  country: CN
  port: 1602
  uuid: 7ff41058-b662-3352-9e7f-643ef2d78344
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /v2ray
  servername: microsoft.com
  ws-headers:
    HOST: microsoft.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 4.32|RelayJPJP930
  server: lrb1.moonfree.top
  port: 2053
  type: vmess
  uuid: 5638fc1a-c3c0-41fd-acb6-2e302e7be794
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /
    host: lrb1.moonfree.top
- name: 4.27| 小汐搬运000213更新广告投放tmebyxiaoxi
  server: 198.41.212.9
  port: 443
  type: vmess
  uuid: a8910831-f56b-4ac4-c68f-e4dd83f71e60
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-path: /sakura/
  ws-headers:
    Host: zero1.a-yu.xyz
- name: 4.18|RELAY104161102380705
  server: 104.16.110.238
  port: 443
  type: vmess
  uuid: a2c47c59-a4c8-4d66-9456-966ba37dedcc
  alterId: 0
  cipher: auto
  skip-cert-vertify: false
  network: ws
  ws-path: /The-Great-Awakening_vws
  tls: true
  ws-headers:
    Host: vincent-jackson2021.ga
- name: 4.16|RELAY1726760780699
  server: 172.67.60.78
  port: 443
  type: vmess
  uuid: 188741f2-1f14-43cb-be7a-1200a9f4332e
  alterId: 0
  cipher: auto
  skip-cert-vertify: false
  network: ws
  ws-path: /The-Great-Awakening_vws
  tls: true
  ws-headers:
    Host: vincent-jackson2022.ml
- name: 4.15|CN11214221040519
  server: 112.14.22.104
  port: 19057
  type: vmess
  uuid: 1b9b7dfc-d92b-35f0-88a3-587c7798d9e3
  alterId: 0
  cipher: auto
  skip-cert-vertify: false
  network: ws
  ws-path: /catnet
  tls: false
  ws-headers:
    Host: cdn-cn.nekocloud.cn
- name: 4.15|CYL科技20220213 53
  server: 1211hk1.fans8.xyz
  port: 80
  type: vmess
  uuid: 5c70da5d-e641-3bf8-b7dc-5babd843ff3c
  alterId: 2
  cipher: auto
  tls: false
  skip-cert-verify: true
  network: ws
  ws-path: /v2ray
  ws-headers:
    Host: 1211hk1.fans8.xyz
  udp: true
- name: 4.04|Relay  862Mb
  server: 128hk8.fans8.xyz
  type: vmess
  country: CA
  port: 80
  uuid: 5c70da5d-e641-3bf8-b7dc-5babd843ff3c
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /v2ray
  servername: 128hk8.fans8.xyz
  ws-headers:
    HOST: 128hk8.fans8.xyz
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 4.03|RelayCNUS331 2976Mb
  server: 183.232.56.161
  type: vmess
  country: CN
  port: 1202
  uuid: 7ff41058-b662-3352-9e7f-643ef2d78344
  alterId: 2
  cipher: auto
  network: ws
  ws-path: /v2ray
  servername: microsoft.com
  ws-headers:
    HOST: microsoft.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: 4.03|RELAY104251042400711
  server: 104.25.104.240
  port: 443
  type: vmess
  uuid: a2c47c59-a4c8-4d66-9456-966ba37dedcc
  alterId: 0
  cipher: auto
  skip-cert-vertify: false
  network: ws
  ws-path: /The-Great-Awakening_vws
  tls: true
  ws-headers:
    Host: vincent-jackson2021.ga
- name: 3.93|RELAY104226680679
  server: 104.22.66.8
  port: 443
  type: vmess
  uuid: a2c47c59-a4c8-4d66-9456-966ba37dedcc
  alterId: 0
  cipher: auto
  skip-cert-vertify: false
  network: ws
  ws-path: /The-Great-Awakening_vws
  tls: true
  ws-headers:
    Host: vincent-jackson2021.ga
